create table if not exists public.turnos_pacientes (
	id_turno bigint generated by default as identity primary key,
	id_paciente integer references public.pacientes(id_paciente) on update cascade on delete set null,
	id_cita integer references public.citas(id_cita) on update cascade on delete set null,
	codigo_turno text not null,
	nombre_paciente text not null,
	area text not null default 'Recepcion',
	destino text,
	estado text not null default 'esperando'
		check (estado in ('esperando', 'llamado', 'en_atencion', 'atendido', 'ausente', 'cancelado')),
	prioridad integer not null default 0,
	fecha_programada timestamptz not null default now(),
	llamado_en timestamptz,
	atendido_en timestamptz,
	creado_por uuid references auth.users(id) on update cascade on delete set null,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create index if not exists idx_turnos_pacientes_estado_fecha
	on public.turnos_pacientes (estado, fecha_programada);

create index if not exists idx_turnos_pacientes_llamado
	on public.turnos_pacientes (llamado_en desc);

create index if not exists idx_turnos_pacientes_paciente
	on public.turnos_pacientes (id_paciente);

create index if not exists idx_turnos_pacientes_codigo
	on public.turnos_pacientes (codigo_turno);

create or replace function public.set_turnos_pacientes_updated_at()
returns trigger
language plpgsql
as $$
begin
	new.updated_at = now();
	return new;
end;
$$;

drop trigger if exists trg_turnos_pacientes_updated_at on public.turnos_pacientes;
create trigger trg_turnos_pacientes_updated_at
	before update on public.turnos_pacientes
	for each row
	execute function public.set_turnos_pacientes_updated_at();

do $$
begin
	if not exists (
		select 1
		from pg_publication_tables
		where pubname = 'supabase_realtime'
			and schemaname = 'public'
			and tablename = 'turnos_pacientes'
	) then
		alter publication supabase_realtime add table public.turnos_pacientes;
	end if;
exception
	when undefined_object then
		null;
end;
$$;
