delete from public.precios_estudios
where cliente = 'Particular'
	and clave in (
		'EC-ARTERIOGRAFIA-FEMORAL-BILATERAL',
		'EC-ARTERIOGRAFIA-FEMORAL-UNILATERAL',
		'EC-COLANGIOGRAFIA-SONDA-T',
		'EC-COLON-ENEMA-DOBLE-CONTRASTE',
		'EC-COLON-ENEMA-COLOSTOMIA',
		'EC-FISTULOGRAFIA-AP-LATERAL-OBLICUAS',
		'EC-FLEBOGRAFIA-BILATERAL',
		'EC-FLEBOGRAFIA-UNILATERAL',
		'EC-HISTEROSALPINGOSGRAFIA',
		'EC-SERIE-EGD-HIDROSOLUBLE',
		'EC-SERIE-EGD',
		'EC-SERIE-GASTRODUODENAL-BEBES-MENORES-1',
		'EC-SERIE-GASTRODUODENAL-CONTRASTE-HIDROSOLUBLE',
		'EC-SIALOGRAFIA-BILATERAL',
		'EC-SIALOGRAFIA-UNILATERAL',
		'EC-TRANSITO-INTESTINAL',
		'EC-URETROCISTOGRAMA-RETROGRADA-MICCIONAL',
		'EC-UROGRAFIA-EXCRETORA',
		'EC-UROGRAFIA-EXCRETORA-MAXWELL-ARATA'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'EC-ARTERIOGRAFIA-FEMORAL-BILATERAL', 'ARTERIOGRAFIA FEMORAL BILATERAL', 'Particular', 9740.00, now()),
	('Estudio', 'EC-ARTERIOGRAFIA-FEMORAL-UNILATERAL', 'ARTERIOGRAFIA FEMORAL UNILATERAL', 'Particular', 6530.00, now()),
	('Estudio', 'EC-COLANGIOGRAFIA-SONDA-T', 'COLANGIOGRAFIA POR SONDA EN T', 'Particular', 2260.00, now()),
	('Estudio', 'EC-COLON-ENEMA-DOBLE-CONTRASTE', 'COLON POR ENEMA DOBLE CONTRASTE', 'Particular', 2970.00, now()),
	('Estudio', 'EC-COLON-ENEMA-COLOSTOMIA', 'COLON POR ENEMA POR COLOSTOMIA', 'Particular', 3210.00, now()),
	('Estudio', 'EC-FISTULOGRAFIA-AP-LATERAL-OBLICUAS', 'FISTULOGRAFIA (AP, LATERAL Y OBLICUAS)', 'Particular', 2610.00, now()),
	('Estudio', 'EC-FLEBOGRAFIA-BILATERAL', 'FLEBOGRAFIA BILATERAL', 'Particular', 4040.00, now()),
	('Estudio', 'EC-FLEBOGRAFIA-UNILATERAL', 'FLEBOGRAFIA UNILATERAL', 'Particular', 3450.00, now()),
	('Estudio', 'EC-HISTEROSALPINGOSGRAFIA', 'HISTEROSALPINGOSGRAFIA', 'Particular', 2790.00, now()),
	('Estudio', 'EC-SERIE-EGD-HIDROSOLUBLE', 'SERIE EGD HIDROSOLUBLE', 'Particular', 3020.00, now()),
	('Estudio', 'EC-SERIE-EGD', 'SERIE ESOFAGO GASTRODUODENAL', 'Particular', 2610.00, now()),
	('Estudio', 'EC-SERIE-GASTRODUODENAL-BEBES-MENORES-1', 'SERIE GASTRODUODENAL BEBES MENORES 1', 'Particular', 1940.00, now()),
	('Estudio', 'EC-SERIE-GASTRODUODENAL-CONTRASTE-HIDROSOLUBLE', 'SERIE GASTRODUODENAL/CONTRASTE HIDROSOLUBLE', 'Particular', 2920.00, now()),
	('Estudio', 'EC-SIALOGRAFIA-BILATERAL', 'SIALOGRAFIA BILATERAL', 'Particular', 3920.00, now()),
	('Estudio', 'EC-SIALOGRAFIA-UNILATERAL', 'SIALOGRAFIA UNILATERAL', 'Particular', 2730.00, now()),
	('Estudio', 'EC-TRANSITO-INTESTINAL', 'TRANSITO INTESTINAL', 'Particular', 3090.00, now()),
	('Estudio', 'EC-URETROCISTOGRAMA-RETROGRADA-MICCIONAL', 'URETROCISTOGRAMA RETROGRADA Y MICCIONAL', 'Particular', 2850.00, now()),
	('Estudio', 'EC-UROGRAFIA-EXCRETORA', 'UROGRAFIA EXCRETORA', 'Particular', 2970.00, now()),
	('Estudio', 'EC-UROGRAFIA-EXCRETORA-MAXWELL-ARATA', 'UROGRAFIA EXCRETORA (MAXWELL O ARATA)', 'Particular', 3210.00, now());
