insert into public.estudios_imagen_catalogo (
	clave,
	descripcion,
	empresa_operativa,
	modalidad,
	area,
	region_anatomica,
	requiere_contraste,
	requiere_interpretacion,
	dias_proceso,
	activo
)
values
	('RX-ABDOMEN-1-PLACA', 'ABDOMEN 1 PLACA', 'CDI', 'radiografia', 'Radiologia', 'Abdomen', false, true, 1, true),
	('RX-ABDOMEN-2-PLACAS', 'ABDOMEN 2 PLACAS', 'CDI', 'radiografia', 'Radiologia', 'Abdomen', false, true, 1, true),
	('RX-AMBAS-MANOS-AP-LATERAL-OBLICUAS', 'AMBAS MANOS AP, LATERAL Y OBLICUAS', 'CDI', 'radiografia', 'Radiologia', 'Manos', false, true, 1, true),
	('RX-AMBAS-MANOS-DORSOPALMAR', 'AMBAS MANOS DORSOPALMAR', 'CDI', 'radiografia', 'Radiologia', 'Manos', false, true, 1, true),
	('RX-AMBAS-MANOS-DORSOPALMAR-OBLICUAS', 'AMBAS MANOS DORSOPALMAR Y OBLICUAS', 'CDI', 'radiografia', 'Radiologia', 'Manos', false, true, 1, true),
	('RX-AMBOS-CODOS-AP-LAT', 'AMBOS CODOS A.P. Y LAT.', 'CDI', 'radiografia', 'Radiologia', 'Codos', false, true, 1, true),
	('RX-AMBOS-PIES-1-POSICION', 'AMBOS PIES 1 POSICION', 'CDI', 'radiografia', 'Radiologia', 'Pies', false, true, 1, true),
	('RX-AMBOS-PIES-2-POSICIONES', 'AMBOS PIES 2 POSICIONES', 'CDI', 'radiografia', 'Radiologia', 'Pies', false, true, 1, true),
	('RX-ANTEBRAZO-AP-LAT', 'ANTEBRAZO A.P. Y LAT.', 'CDI', 'radiografia', 'Radiologia', 'Antebrazo', false, true, 1, true),
	('RX-ANTEBRAZO-AP', 'ANTEBRAZO AP', 'CDI', 'radiografia', 'Radiologia', 'Antebrazo', false, true, 1, true),
	('RX-AP-LATERAL-OBLICUA-TOBILLO', 'AP LATERAL Y OBLICUA DE TOBILLO', 'CDI', 'radiografia', 'Radiologia', 'Tobillo', false, true, 1, true),
	('RX-ARTICULACION-TEMPOROMANDIBULAR', 'ARTICULACION TEMPOROMANDIBULAR', 'CDI', 'radiografia', 'Radiologia', 'Articulacion temporomandibular', false, true, 1, true),
	('RX-ARTICULACION-TEMPOROMANDIBULAR-4-POSICIONES', 'ARTICULACION TEMPOROMANDIBULAR 4 POSICIONES', 'CDI', 'radiografia', 'Radiologia', 'Articulacion temporomandibular', false, true, 1, true),
	('RX-BRAZO-AP-LAT', 'BRAZO A.P. Y LAT.', 'CDI', 'radiografia', 'Radiologia', 'Brazo', false, true, 1, true),
	('RX-BRAZO-AP', 'BRAZO AP', 'CDI', 'radiografia', 'Radiologia', 'Brazo', false, true, 1, true),
	('RX-CODO-AP', 'CODO A.P.', 'CDI', 'radiografia', 'Radiologia', 'Codo', false, true, 1, true),
	('RX-CODO-AP-LAT', 'CODO A.P. Y LAT.', 'CDI', 'radiografia', 'Radiologia', 'Codo', false, true, 1, true),
	('RX-CODOS-AP', 'CODOS AP', 'CDI', 'radiografia', 'Radiologia', 'Codos', false, true, 1, true),
	('RX-COLUMNA-1-POSICION', 'COLUMNA 1 POSICION', 'CDI', 'radiografia', 'Radiologia', 'Columna', false, true, 1, true),
	('RX-COLUMNA-CERVICAL-2-POSICIONES', 'COLUMNA CERVICAL (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna cervical', false, true, 1, true),
	('RX-COLUMNA-CERVICAL-4-POSICIONES', 'COLUMNA CERVICAL( 4 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna cervical', false, true, 1, true),
	('RX-COLUMNA-DORSAL-2-POSICIONES', 'COLUMNA DORSAL (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna dorsal', false, true, 1, true),
	('RX-COLUMNA-DORSAL-4-POSICIONES', 'COLUMNA DORSAL (4 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna dorsal', false, true, 1, true),
	('RX-COLUMNA-DORSOLUMBAR-4-POSICIONES', 'COLUMNA DORSOLUMBAR ( 4 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna dorsolumbar', false, true, 1, true),
	('RX-COLUMNA-LUMBAR-2-POSICIONES', 'COLUMNA LUMBAR (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna lumbar', false, true, 1, true),
	('RX-COLUMNA-LUMBAR-4-POSICIONES', 'COLUMNA LUMBAR (4 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna lumbar', false, true, 1, true),
	('RX-COLUMNA-LUMBOSACRA-2-POSICIONES', 'COLUMNA LUMBOSACRA (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna lumbosacra', false, true, 1, true),
	('RX-COLUMNA-LUMBOSACRA-4-POSICIONES', 'COLUMNA LUMBOSACRA (4 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna lumbosacra', false, true, 1, true),
	('RX-COLUMNA-SACROCOXIGEA-2-POSICIONES', 'COLUMNA SACROCOXIGEA (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Columna sacrocoxigea', false, true, 1, true),
	('RX-COLUMNA-VERTEBRAL-TOTAL-AP', 'COLUMNA VERTEBRAL TOTAL AP', 'CDI', 'radiografia', 'Radiologia', 'Columna vertebral total', false, true, 1, true),
	('RX-COLUMNA-VERTEBRAL-TOTAL-AP-LATERAL', 'COLUMNA VERTEBRAL TOTAL AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Columna vertebral total', false, true, 1, true),
	('RX-COXIS-AP-LATERAL', 'COXIS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Coxis', false, true, 1, true),
	('RX-CRANEO-1-POSICION', 'CRANEO 1 POSICION', 'CDI', 'radiografia', 'Radiologia', 'Craneo', false, true, 1, true),
	('RX-CRANEO-AP-LATERAL', 'CRANEO AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Craneo', false, true, 1, true),
	('RX-CRANEO-AP-LAT-TOWNE', 'CRANEO AP, LAT Y TOWNE', 'CDI', 'radiografia', 'Radiologia', 'Craneo', false, true, 1, true),
	('RX-CUELLO-AP', 'CUELLO A.P', 'CDI', 'radiografia', 'Radiologia', 'Cuello', false, true, 1, true),
	('RX-ESCANOMETRIA', 'ESCANOMETRIA', 'CDI', 'radiografia', 'Radiologia', 'Miembros inferiores', false, true, 1, true),
	('RX-FEMUR-1-PLACA', 'FEMUR 1 PLACA', 'CDI', 'radiografia', 'Radiologia', 'Femur', false, true, 1, true),
	('RX-FEMUR-2-PLACAS', 'FEMUR 2 PLACAS', 'CDI', 'radiografia', 'Radiologia', 'Femur', false, true, 1, true),
	('RX-HOMBRO-AP', 'HOMBRO AP', 'CDI', 'radiografia', 'Radiologia', 'Hombro', false, true, 1, true),
	('RX-HOMBRO-AP-LATERAL', 'HOMBRO AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Hombro', false, true, 1, true),
	('RX-HOMBROS-AP', 'HOMBROS AP', 'CDI', 'radiografia', 'Radiologia', 'Hombros', false, true, 1, true),
	('RX-HOMBROS-AP-LATERAL', 'HOMBROS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Hombros', false, true, 1, true),
	('RX-HUESOS-PROPIOS-NARIZ-AP', 'HUESOS PROPIOS DE LA NARIZ AP', 'CDI', 'radiografia', 'Radiologia', 'Nariz', false, true, 1, true),
	('RX-LATERAL-RINOFARINGE-NASOFARINGE', 'LATERAL DE RINOFARINGE ( NASOFARINGE)', 'CDI', 'radiografia', 'Radiologia', 'Rinofaringe', false, true, 1, true),
	('RX-MANO-DORSOPALMAR', 'MANO DORSOPALMAR', 'CDI', 'radiografia', 'Radiologia', 'Mano', false, true, 1, true),
	('RX-MANO-DORSOPALMAR-AP-LATERAL-OBLICUA', 'MANO DORSOPALMAR AP, LATERAL Y OBLICUA', 'CDI', 'radiografia', 'Radiologia', 'Mano', false, true, 1, true),
	('RX-MANO-DORSOPALMAR-OBLICUA', 'MANO DORSOPALMAR Y OBLICUA', 'CDI', 'radiografia', 'Radiologia', 'Mano', false, true, 1, true),
	('RX-MASTOIDES-BILATERAL', 'MASTOIDES BILATERAL', 'CDI', 'radiografia', 'Radiologia', 'Mastoides', false, true, 1, true),
	('RX-MASTOIDES-UNILATERAL', 'MASTOIDES UNILATERAL', 'CDI', 'radiografia', 'Radiologia', 'Mastoides', false, true, 1, true),
	('RX-MUNECA-AP', 'MUNECA AP', 'CDI', 'radiografia', 'Radiologia', 'Muneca', false, true, 1, true),
	('RX-MUNECA-AP-LATERAL', 'MUNECA AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Muneca', false, true, 1, true),
	('RX-MUNECAS-AP', 'MUNECAS AP', 'CDI', 'radiografia', 'Radiologia', 'Munecas', false, true, 1, true),
	('RX-MUNECAS-AP-LATERAL', 'MUNECAS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Munecas', false, true, 1, true),
	('RX-PELVICEFALOMETRIA-2-PLACAS', 'PELVICEFALOMETRIA 2 PLACAS', 'CDI', 'radiografia', 'Radiologia', 'Pelvicefalometria', false, true, 1, true),
	('RX-PELVIS-1-PLACA', 'PELVIS 1 PLACA', 'CDI', 'radiografia', 'Radiologia', 'Pelvis', false, true, 1, true),
	('RX-PELVIS-2-PLACAS', 'PELVIS 2 PLACAS', 'CDI', 'radiografia', 'Radiologia', 'Pelvis', false, true, 1, true),
	('RX-PERFILOGRAMA', 'PERFILOGRAMA', 'CDI', 'radiografia', 'Radiologia', 'Perfilograma', false, true, 1, true),
	('RX-PIE-1-POSICION', 'PIE 1 POSICION', 'CDI', 'radiografia', 'Radiologia', 'Pie', false, true, 1, true),
	('RX-PIE-2-POSICIONES', 'PIE 2 POSICIONES', 'CDI', 'radiografia', 'Radiologia', 'Pie', false, true, 1, true),
	('RX-PIE-AP-LAT-OBLICUA', 'PIE AP, LAT Y OBLICUA', 'CDI', 'radiografia', 'Radiologia', 'Pie', false, true, 1, true),
	('RX-PIERNA-AP', 'PIERNA AP', 'CDI', 'radiografia', 'Radiologia', 'Pierna', false, true, 1, true),
	('RX-PIERNA-AP-LATERAL', 'PIERNA AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Pierna', false, true, 1, true),
	('RX-PIERNAS-AP', 'PIERNAS AP', 'CDI', 'radiografia', 'Radiologia', 'Piernas', false, true, 1, true),
	('RX-PIERNAS-AP-LATERAL', 'PIERNAS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Piernas', false, true, 1, true),
	('RX-PLACA-CUALQUIER-REGION', 'PLACA CUALQUIER REGION', 'CDI', 'radiografia', 'Radiologia', 'Cualquier region', false, true, 1, true),
	('RX-RODILLA-AP', 'RODILLA A.P', 'CDI', 'radiografia', 'Radiologia', 'Rodilla', false, true, 1, true),
	('RX-RODILLA-AP-LATERAL', 'RODILLA AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Rodilla', false, true, 1, true),
	('RX-RODILLAS-AP', 'RODILLAS AP', 'CDI', 'radiografia', 'Radiologia', 'Rodillas', false, true, 1, true),
	('RX-RODILLAS-COMPARATIVAS-AP-LATERAL', 'RODILLAS COMPARATIVAS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Rodillas comparativas', false, true, 1, true),
	('RX-ROTULAS-AXIALES-30-60-90-UN-LADO', 'ROTULAS AXIALES A 30, 60 Y 90 GRADOS (UN LADO)', 'CDI', 'radiografia', 'Radiologia', 'Rotulas', false, true, 1, true),
	('RX-SENOS-PARANASALES-1-POSICION', 'SENOS PARANASALES 1 POSICION', 'CDI', 'radiografia', 'Radiologia', 'Senos paranasales', false, true, 1, true),
	('RX-SENOS-PARANASALES-2-POSICIONES', 'SENOS PARANASALES 2 POSICIONES', 'CDI', 'radiografia', 'Radiologia', 'Senos paranasales', false, true, 1, true),
	('RX-SENOS-PARANASALES-3-POSICIONES', 'SENOS PARANASALES 3 POSICIONES', 'CDI', 'radiografia', 'Radiologia', 'Senos paranasales', false, true, 1, true),
	('RX-SERIE-CARDIACA', 'SERIE CARDIACA', 'CDI', 'radiografia', 'Radiologia', 'Cardiaca', false, true, 1, true),
	('RX-SERIE-OSEA-METASTASICA', 'SERIE OSEA METASTASICA', 'CDI', 'radiografia', 'Radiologia', 'Osea metastasica', false, true, 1, true),
	('RX-SHULLER-BILATERAL', 'SHULLER BILATERAL', 'CDI', 'radiografia', 'Radiologia', 'Schuller', false, true, 1, true),
	('RX-SHULLER-UNILATERAL', 'SHULLER UNILATERAL', 'CDI', 'radiografia', 'Radiologia', 'Schuller', false, true, 1, true),
	('RX-TOBILLO-AP', 'TOBILLO A.P.', 'CDI', 'radiografia', 'Radiologia', 'Tobillo', false, true, 1, true),
	('RX-TOBILLO-AP-LATERAL', 'TOBILLO AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Tobillo', false, true, 1, true),
	('RX-TOBILLOS-AP', 'TOBILLOS AP', 'CDI', 'radiografia', 'Radiologia', 'Tobillos', false, true, 1, true),
	('RX-TOBILLOS-AP-LATERAL', 'TOBILLOS AP Y LATERAL', 'CDI', 'radiografia', 'Radiologia', 'Tobillos', false, true, 1, true),
	('RX-TORAX-1-POSICION', 'TORAX (1 POSICION)', 'CDI', 'radiografia', 'Radiologia', 'Torax', false, true, 1, true),
	('RX-TORAX-2-POSICIONES', 'TORAX (2 POSICIONES)', 'CDI', 'radiografia', 'Radiologia', 'Torax', false, true, 1, true),
	('RX-TORAX-OSEO-OBLICUA', 'TORAX OSEO Y OBLICUA', 'CDI', 'radiografia', 'Radiologia', 'Torax oseo', false, true, 1, true),
	('RX-WATERS-LATERAL-CRANEO', 'WATERS Y LATERAL DE CRANEO', 'CDI', 'radiografia', 'Radiologia', 'Craneo', false, true, 1, true)
on conflict (clave) do update set
	descripcion = excluded.descripcion,
	empresa_operativa = excluded.empresa_operativa,
	modalidad = excluded.modalidad,
	area = excluded.area,
	region_anatomica = excluded.region_anatomica,
	requiere_contraste = excluded.requiere_contraste,
	requiere_interpretacion = excluded.requiere_interpretacion,
	dias_proceso = excluded.dias_proceso,
	activo = excluded.activo,
	updated_at = now();
