insert into public.estudios_imagen_catalogo (
	clave,
	descripcion,
	empresa_operativa,
	modalidad,
	area,
	region_anatomica,
	requiere_contraste,
	requiere_interpretacion,
	dias_proceso,
	activo
)
values
	('US-ABDOMEN-2-REGIONES', 'U.S. ABDOMEN 2 REGIONES', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Abdomen', false, true, 1, true),
	('US-AORTA-ABDOMINAL', 'U.S. AORTA ABDOMINAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Aorta abdominal', false, true, 1, true),
	('US-CAROTIDEO-BILATERAL-DOPPLER-COLOR', 'U.S. CAROTIDEO BILATERAL CON DOPPLER COLOR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Carotideo bilateral', false, true, 1, true),
	('US-CAROTIDEO-UNILATERAL-DOPPLER-COLOR', 'U.S. CAROTIDEO UNILATERAL CON DOPPLER COLOR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Carotideo unilateral', false, true, 1, true),
	('US-CUELLO', 'U.S. DE CUELLO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Cuello', false, true, 1, true),
	('US-PENE', 'U.S. DE PENE', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Pene', false, true, 1, true),
	('US-TIROIDES', 'U.S. DE TIROIDES', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Tiroides', false, true, 1, true),
	('US-DOPPLER-ARTERIAL-BILATERAL', 'U.S. DOPPLER ARTERIAL BILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Arterial bilateral', false, true, 1, true),
	('US-DOPPLER-ARTERIAL-UNILATERAL', 'U.S. DOPPLER ARTERIAL UNILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Arterial unilateral', false, true, 1, true),
	('US-DOPPLER-ARTERIAL-VENOSO-BILATERAL', 'U.S. DOPPLER ARTERIAL Y VENOSO BILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Arterial y venoso bilateral', false, true, 1, true),
	('US-DOPPLER-ARTERIAL-VENOSO-UNILATERAL', 'U.S. DOPPLER ARTERIAL Y VENOSO UNILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Arterial y venoso unilateral', false, true, 1, true),
	('US-DOPPLER-PENE', 'U.S. DOPPLER DE PENE', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Pene', false, true, 1, true),
	('US-DOPPLER-HEPATICO-ELASTOGRAFIA', 'U.S. DOPPLER HEPATICO CON ELASTOGRAFIA', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Hepatico', false, true, 1, true),
	('US-DOPPLER-HEPATO-VESICULAR', 'U.S. DOPPLER HEPATO VESICULAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Hepato vesicular', false, true, 1, true),
	('US-DOPPLER-MAMARIO', 'U.S. DOPPLER MAMARIO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Mamario', false, true, 1, true),
	('US-DOPPLER-OBSTETRICO', 'U.S. DOPPLER OBSTETRICO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico', false, true, 1, true),
	('US-DOPPLER-OBSTETRICO-GEMELAR', 'U.S. DOPPLER OBSTETRICO GEMELAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico gemelar', false, true, 1, true),
	('US-DOPPLER-RENAL', 'U.S. DOPPLER RENAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Renal', false, true, 1, true),
	('US-DOPPLER-TEJIDOS-BLANDOS', 'U.S. DOPPLER TEJIDOS BLANDOS', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Tejidos blandos', false, true, 1, true),
	('US-DOPPLER-TESTICULAR', 'U.S. DOPPLER TESTICULAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Testicular', false, true, 1, true),
	('US-DOPPLER-TIROIDEO', 'U.S. DOPPLER TIROIDEO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Tiroideo', false, true, 1, true),
	('US-DOPPLER-TRANSVAGINAL-ENDOVAGINAL', 'U.S. DOPPLER TRANSVAGINAL / ENDOVAGINAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Transvaginal / endovaginal', false, true, 1, true),
	('US-DOPPLER-VENOSO-BILATERAL', 'U.S. DOPPLER VENOSO BILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Venoso bilateral', false, true, 1, true),
	('US-DOPPLER-VENOSO-UNILATERAL', 'U.S. DOPPLER VENOSO UNILATERAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Venoso unilateral', false, true, 1, true),
	('US-HEPATO-VESICULAR', 'U.S. HEPATO VESICULAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Hepato vesicular', false, true, 1, true),
	('US-HEPATO-VESICULAR-PRUEBA-BOYDEN', 'U.S. HEPATO VESICULAR CON PRUEBA DE BOYDEN', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Hepato vesicular', false, true, 1, true),
	('US-INGUINAL', 'U.S. INGUINAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Inguinal', false, true, 1, true),
	('US-INGUINO-ESCROTAL', 'U.S. INGUINO-ESCROTAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Inguino escrotal', false, true, 1, true),
	('US-MAMARIO', 'U.S. MAMARIO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Mamario', false, true, 1, true),
	('US-MUSCULO-ESQUELETICO', 'U.S. MUSCULO ESQUELETICO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Musculo esqueletico', false, true, 1, true),
	('US-OBSTETRICO', 'U.S. OBSTETRICO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico', false, true, 1, true),
	('US-OBSTETRICO-ESTRUCTURAL', 'U.S. OBSTETRICO  ESTRUCTURAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico estructural', false, true, 1, true),
	('US-OBSTETRICO-3A-DIMENSION', 'U.S. OBSTETRICO 3A DIMENSION', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico 3a dimension', false, true, 1, true),
	('US-OBSTETRICO-5TA-DIMENSION-CD-FOTO', 'U.S. OBSTETRICO 5TA. DIMENSION CON CD Y FOTO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico 5ta dimension', false, true, 1, true),
	('US-OBSTETRICO-ENDOVAGINAL-DOPPLER-COLOR', 'U.S. OBSTETRICO ENDOVAGINAL CON DOPPLER COLOR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico endovaginal', false, true, 1, true),
	('US-OBSTETRICO-GEMELAR', 'U.S OBSTETRICO GEMELAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico gemelar', false, true, 1, true),
	('US-OBSTETRICO-PERFIL-BIOFISICO', 'U.S. OBSTETRICO PERFIL BIOFISICO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Obstetrico perfil biofisico', false, true, 1, true),
	('US-PELVICO-UTERO-ANEXOS', 'U.S. PELVICO / UTERO Y ANEXOS', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Pelvico / utero y anexos', false, true, 1, true),
	('US-PROSTATICO', 'U.S. PROSTATICO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Prostatico', false, true, 1, true),
	('US-PROSTATICO-ENDORECTAL', 'U.S. PROSTATICO ENDORECTAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Prostatico endorectal', false, true, 1, true),
	('US-RENAL', 'U.S. RENAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Renal', false, true, 1, true),
	('US-SEGUIMIENTO-FOLICULAR', 'U.S. SEGUIMIENTO FOLICULAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Seguimiento folicular', false, true, 1, true),
	('US-SONOHISTERO', 'U.S. SONOHISTERO', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Sonohistero', false, true, 1, true),
	('US-TEJIDOS-BLANDOS', 'U.S. TEJIDOS BLANDOS', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Tejidos blandos', false, true, 1, true),
	('US-TESTICULAR', 'U.S. TESTICULAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Testicular', false, true, 1, true),
	('US-TRANSFONTANELAR', 'U.S. TRANSFONTANELAR', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Transfontanelar', false, true, 1, true),
	('US-TRANSVAGINAL-ENDOVAGINAL', 'U.S. TRANSVAGINAL/ENDOVAGINAL', 'CDI', 'ultrasonido', 'Ultrasonidos', 'Transvaginal / endovaginal', false, true, 1, true)
on conflict (clave) do update set
	descripcion = excluded.descripcion,
	empresa_operativa = excluded.empresa_operativa,
	modalidad = excluded.modalidad,
	area = excluded.area,
	region_anatomica = excluded.region_anatomica,
	requiere_contraste = excluded.requiere_contraste,
	requiere_interpretacion = excluded.requiere_interpretacion,
	dias_proceso = excluded.dias_proceso,
	activo = excluded.activo,
	updated_at = now();
