-- Precios de laboratorio de SSA, tomados de la lista de precios vigente.
-- La mayoría ya estaban capturados; esta siembra corrige los que quedaron con
-- otro importe, así que primero se borra lo que haya de esas claves para ese
-- cliente y se vuelve a insertar. Eso la deja re-ejecutable y de paso limpia
-- los renglones repetidos que traía la lista.
--
-- La lista traía en la hoja de SSA cuatro renglones de la clave AcRO
-- (ANTICUERPOS ANTI-SSA Ro) que son de otros clientes, porque el nombre del
-- estudio contiene "SSA". Cada uno se carga con el cliente que le corresponde;
-- los de Particular e ISSSTE van en sus propias migraciones, con el mismo
-- importe.

delete from public.precios_estudios
where cliente = 'CENTRO MEDICO ANAMAYA'
	and clave in (
		'AcRO'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'AcRO', 'ANTICUERPOS ANTI-SSA Ro', 'CENTRO MEDICO ANAMAYA', 701.25, now());

delete from public.precios_estudios
where cliente = 'NAVAL'
	and clave in (
		'AcRO'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'AcRO', 'ANTICUERPOS ANTI-SSA Ro', 'NAVAL', 612.00, now());

delete from public.precios_estudios
where cliente = 'SSA'
	and clave in (
		'17ALFA',
		'AAC',
		'AACLA',
		'AACLG',
		'AACLM',
		'AAN18',
		'ACC',
		'ACL',
		'ACLY',
		'ACSMITH',
		'ACT',
		'ACTA',
		'ACTG',
		'ACTH',
		'ACTM',
		'ADNA',
		'ADST',
		'ADT',
		'AELO1',
		'AFOL',
		'AFP',
		'AGCOVID',
		'AGG',
		'ALB',
		'AMI',
		'AMIF',
		'AMON',
		'ANA',
		'ANCA',
		'ARRTSH',
		'AT3',
		'AU',
		'AcEHB',
		'AcHepC',
		'AcI',
		'BAAR',
		'BAAR3',
		'BCRABL',
		'BHC',
		'BILIS',
		'BNP',
		'C3',
		'C4',
		'CA125',
		'CA153',
		'CA199',
		'CAL',
		'CALACT',
		'CALCI',
		'CCP',
		'CD',
		'CEA',
		'CEXP',
		'CFE',
		'CI',
		'CISTATINA',
		'CITOLI',
		'CITOS',
		'CKMB',
		'CLAMY',
		'CLCR',
		'CMV',
		'CMVM',
		'COL',
		'COLHDL',
		'COLI',
		'COP1',
		'COP2',
		'COP3',
		'COPCUL',
		'COPROL',
		'CORT',
		'CORVES',
		'CPK',
		'CRE',
		'CTG',
		'CUCH',
		'CUSE',
		'CVAG',
		'DENG',
		'DEPU',
		'DHEAS',
		'DHL',
		'DHT',
		'DIM',
		'DNAN',
		'DOP3',
		'DOP6',
		'EGO',
		'EOS',
		'ES3',
		'ES6',
		'ESP',
		'EST',
		'ETOT',
		'FAC',
		'FAR',
		'FEB',
		'FERR',
		'FIBRI',
		'FOSFORO',
		'FR',
		'FRC',
		'FSH',
		'FTA',
		'GASART',
		'GASVEN',
		'GGT',
		'GLU',
		'GLUPOS',
		'GPO',
		'H1N1',
		'H2G',
		'H2M',
		'HBA1C',
		'HBsAg',
		'HC',
		'HCG',
		'HEMO',
		'HIERRO',
		'HIV1Y2',
		'HLAB27',
		'HOMIR',
		'HOMO',
		'HPYH',
		'HSEX',
		'HepAIgM',
		'HepAT',
		'HerpG',
		'HerpM',
		'INPOS',
		'INS',
		'IgA',
		'IgE',
		'IgG',
		'IgGGLIC',
		'IgM',
		'K',
		'LAC',
		'LE',
		'LH',
		'LIPA',
		'LIT',
		'MG',
		'MICRO24',
		'NA',
		'OSULL',
		'PANCA',
		'PAP',
		'PAPPCR',
		'PBASICO',
		'PCR',
		'PCRUL',
		'PCT',
		'PDIAB',
		'PETS',
		'PFH',
		'PH',
		'PIES',
		'PLG',
		'PLIP',
		'PLM',
		'POV5',
		'POV6',
		'PPD',
		'PPNAT',
		'PPRE',
		'PREOP',
		'PREUMA',
		'PROG',
		'PROL',
		'PROTC',
		'PROTS',
		'PSAE',
		'PSAF',
		'PSCOMP',
		'PSELE',
		'PSTIR',
		'PTORINA',
		'PTOT',
		'PYIgA',
		'PYIgG',
		'PYIgM',
		'QS12',
		'QS24',
		'QS3',
		'QS30',
		'QS3ALT',
		'QS4',
		'QS4ALT',
		'QS6',
		'RALCR',
		'RETI',
		'RICKIgG',
		'RICKIgM',
		'ROSA',
		'SLC70',
		'SOH',
		'T3C',
		'T3L',
		'T3T',
		'T4L',
		'T4T',
		'TAM',
		'TC',
		'TESTO',
		'TGO',
		'TGP',
		'TIRO',
		'TIROG',
		'TOMDOM',
		'TORCHIII',
		'TP',
		'TRANS',
		'TRIG',
		'TRIP',
		'TROI',
		'TS',
		'TSH',
		'TTP',
		'TUBIgG',
		'TUBIgM',
		'URE',
		'UREAO',
		'URO',
		'VB12',
		'VDRL',
		'VITD25',
		'VITD3',
		'VSG',
		'ZINC',
		'aTPO',
		'testlibre2'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', '17ALFA', '17 ALFA HIDROXIPROGESTERONA EN SUERO', 'SSA', 731.50, now()),
	('Estudio', 'AAC', 'ANTICUERPOS ANTI-CENTROMERO', 'SSA', 891.00, now()),
	('Estudio', 'AACLA', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgA', 'SSA', 1093.50, now()),
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'SSA', 608.00, now()),
	('Estudio', 'AACLM', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgM', 'SSA', 702.00, now()),
	('Estudio', 'AAN18', 'INMUNOESPECIFICIDAD DE AAN 18 DETERM', 'SSA', 6075.00, now()),
	('Estudio', 'ACC', 'AC ANTI CISTICERCO EN LCR', 'SSA', 632.50, now()),
	('Estudio', 'ACL', 'ANTICOAGULANTE LUPICO', 'SSA', 1012.00, now()),
	('Estudio', 'ACLY', 'ANTICUERPOS ANTI-BORRELIA BURGDORFERI IgG e IgM', 'SSA', 1998.00, now()),
	('Estudio', 'ACSMITH', 'AC. ANTI-SMITH', 'SSA', 677.00, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'SSA', 632.50, now()),
	('Estudio', 'ACTA', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgA', 'SSA', 764.50, now()),
	('Estudio', 'ACTG', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgG', 'SSA', 764.50, now()),
	('Estudio', 'ACTH', 'HORMONA ADRENOCORTICOTROFICA ACTH', 'SSA', 665.50, now()),
	('Estudio', 'ACTM', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgM', 'SSA', 764.50, now()),
	('Estudio', 'ADNA', 'ANTICUERPOS ANTI-DNA DOBLE CADENA', 'SSA', 774.00, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'SSA', 1053.00, now()),
	('Estudio', 'ADT', 'ANDROSTENEDIONA', 'SSA', 544.50, now()),
	('Estudio', 'AELO1', 'ANTI-ESTREPTOLISINA "O"', 'SSA', 186.34, now()),
	('Estudio', 'AFOL', 'ACIDO FOLICO (FOLATOS)', 'SSA', 890.00, now()),
	('Estudio', 'AFP', 'ALFAFETOPROTEINAS', 'SSA', 392.00, now()),
	('Estudio', 'AGCOVID', 'PRUEBA DE ANTIGENO DE SARS-CoV-2 (COVID-19)', 'SSA', 495.00, now()),
	('Estudio', 'AGG', 'ANTIGENO GIARDIA LAMBLIA', 'SSA', 1330.00, now()),
	('Estudio', 'ALB', 'ALBUMINA SERICA', 'SSA', 107.80, now()),
	('Estudio', 'AMI', 'AMILASA SERICA', 'SSA', 177.10, now()),
	('Estudio', 'AMIF', 'AMIBA EN FRESCO', 'SSA', 107.80, now()),
	('Estudio', 'AMON', 'AMONIO EN PLASMA', 'SSA', 355.30, now()),
	('Estudio', 'ANA', 'ANTICUERPOS ANTINUCLEARES', 'SSA', 700.00, now()),
	('Estudio', 'ANCA', 'ANTICUERPOS ANTI-CITOPLASMA C-ANCA', 'SSA', 1566.00, now()),
	('Estudio', 'ARRTSH', 'ANTICUERPOS ANTI RECEPTORES DE TSH', 'SSA', 2090.00, now()),
	('Estudio', 'AT3', 'ANTITROMBINA III', 'SSA', 1204.50, now()),
	('Estudio', 'AU', 'ACIDO URICO', 'SSA', 107.80, now()),
	('Estudio', 'AcEHB', 'ANTICUERPOS CONTRA EL  ANTIGENO E DE HEPATITIS B', 'SSA', 486.00, now()),
	('Estudio', 'AcHepC', 'ANTICUERPOS ANTI-HEPATITIS C (CUALITATIVO)', 'SSA', 342.65, now()),
	('Estudio', 'AcI', 'ANTICUERPOS ANTI-INSULINA', 'SSA', 735.90, now()),
	('Estudio', 'BAAR', 'BACILOSCOPIA DE 1 MUESTRA (BAAR)', 'SSA', 226.27, now()),
	('Estudio', 'BAAR3', 'BACILOSCOPIA DE 3 MUESTRAS (BAAR)', 'SSA', 671.00, now()),
	('Estudio', 'BCRABL', 'CROMOSOMA FILADELFIA ( BCR/ABL)', 'SSA', 8000.00, now()),
	('Estudio', 'BHC', 'BIOMETRIA HEMATICA COMPLETA (BHC)', 'SSA', 115.50, now()),
	('Estudio', 'BILIS', 'BILIRRUBINAS', 'SSA', 216.70, now()),
	('Estudio', 'BNP', 'PEPTIDO NATRIURETICO (BNP)', 'SSA', 2200.00, now()),
	('Estudio', 'C3', 'COMPLEMENTO C3', 'SSA', 430.10, now()),
	('Estudio', 'C4', 'COMPLEMENTO C4', 'SSA', 430.10, now()),
	('Estudio', 'CA125', 'AG. CARCINOMA OVARICO CA-125', 'SSA', 590.92, now()),
	('Estudio', 'CA153', 'AG. CARCINOMA DE MAMA CA 15-3', 'SSA', 617.11, now()),
	('Estudio', 'CA199', 'AG. CARCINOMA DE PANCREAS Y COLON CA 19-9', 'SSA', 726.00, now()),
	('Estudio', 'CAL', 'CALCIO SERICO', 'SSA', 154.00, now()),
	('Estudio', 'CALACT', 'CALPROTECTINA Y LACTOFERRINA HUMANA', 'SSA', 1342.00, now()),
	('Estudio', 'CALCI', 'CALCITONINA', 'SSA', 627.00, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'SSA', 1517.51, now()),
	('Estudio', 'CD', 'COOMBS DIRECTO', 'SSA', 258.06, now()),
	('Estudio', 'CEA', 'ANTIGENO CARCINOEMBRIONARIO', 'SSA', 376.81, now()),
	('Estudio', 'CEXP', 'CULTIVO DE EXPECTORACION', 'SSA', 600.00, now()),
	('Estudio', 'CFE', 'CINETICA DE HIERRO', 'SSA', 1413.50, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'SSA', 273.96, now()),
	('Estudio', 'CISTATINA', 'CISTATINA C', 'SSA', 946.00, now()),
	('Estudio', 'CITOLI', 'CITOLOGICO DE LIQUIDOS', 'SSA', 652.00, now()),
	('Estudio', 'CITOS', 'CITOQUIMICO DE LIQUIDO', 'SSA', 672.00, now()),
	('Estudio', 'CKMB', 'CREATIN-FOSFOQUINASA MB (CK-MB)', 'SSA', 280.50, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'SSA', 4700.00, now()),
	('Estudio', 'CLCR', 'CULTIVO DE LIQUIDO CEFALORRAQUIDEO', 'SSA', 813.45, now()),
	('Estudio', 'CMV', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgG', 'SSA', 621.00, now()),
	('Estudio', 'CMVM', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgM', 'SSA', 621.00, now()),
	('Estudio', 'COL', 'COLESTEROL', 'SSA', 107.00, now()),
	('Estudio', 'COLHDL', 'COLESTEROL HDL', 'SSA', 107.00, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'SSA', 473.11, now()),
	('Estudio', 'COP1', 'COPROPARASITOSCOPICO (1 MUESTRA)', 'SSA', 88.55, now()),
	('Estudio', 'COP2', 'COPROPARASITOSCOPICO (2 MUESTRAS)', 'SSA', 177.10, now()),
	('Estudio', 'COP3', 'COPROPARASITOSCOPICO (3 MUESTRAS)', 'SSA', 246.40, now()),
	('Estudio', 'COPCUL', 'COPROCULTIVO - CULTIVO DE HECES', 'SSA', 792.00, now()),
	('Estudio', 'COPROL', 'COPROLOGICO GENERAL', 'SSA', 177.10, now()),
	('Estudio', 'CORT', 'CORTISOL SERICO', 'SSA', 255.64, now()),
	('Estudio', 'CORVES', 'CORTISOL VESPERTINO', 'SSA', 255.64, now()),
	('Estudio', 'CPK', 'CREATIN-FOSFOQUINASA (CPK)', 'SSA', 233.75, now()),
	('Estudio', 'CRE', 'CREATININA', 'SSA', 107.80, now()),
	('Estudio', 'CTG', 'CURVA DE TOLERANCIA A LA GLUCOSA 2 HORAS', 'SSA', 514.25, now()),
	('Estudio', 'CUCH', 'CULTIVO DE EXUADO URETRAL C/CHLAMYDIA', 'SSA', 820.00, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'SSA', 572.00, now()),
	('Estudio', 'CVAG', 'CULTIVO DE EXUDADO CERVICO VAGINAL', 'SSA', 572.00, now()),
	('Estudio', 'DENG', 'DENGUE DUO', 'SSA', 486.20, now()),
	('Estudio', 'DEPU', 'DEPURACION DE CREATININA EN ORINA DE 24 HORAS', 'SSA', 307.62, now()),
	('Estudio', 'DHEAS', 'DHEA-S DEHIDROEPIANDROSTERONA SULFATO', 'SSA', 451.61, now()),
	('Estudio', 'DHL', 'DESHIDROGENASA LACTICA DHL', 'SSA', 204.05, now()),
	('Estudio', 'DHT', 'DIHIDROTESTOSTERONA', 'SSA', 743.00, now()),
	('Estudio', 'DIM', 'DIMERO D', 'SSA', 678.81, now()),
	('Estudio', 'DNAN', 'ANTICUERPOS ANTI-DNA', 'SSA', 1148.00, now()),
	('Estudio', 'DOP3', 'ANTIDOPING DE 3 PARAMETROS', 'SSA', 299.20, now()),
	('Estudio', 'DOP6', 'ANTIDOPING DE 6 PARAMETROS', 'SSA', 627.00, now()),
	('Estudio', 'EGO', 'EXAMEN GENERAL DE ORINA', 'SSA', 115.50, now()),
	('Estudio', 'EOS', 'EOSINOFILOS DE MOCO NASAL', 'SSA', 209.00, now()),
	('Estudio', 'ES3', 'ELECTROLITOS SERICOS DE 3 PARAMETROS', 'SSA', 288.75, now()),
	('Estudio', 'ES6', 'ELECTROLITOS SERICOS DE 6 PARAMETROS', 'SSA', 402.71, now()),
	('Estudio', 'ESP', 'ESPERMATOBIOSCOPIA', 'SSA', 392.70, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'SSA', 275.00, now()),
	('Estudio', 'ETOT', 'ESTROGENOS TOTALES', 'SSA', 495.00, now()),
	('Estudio', 'FAC', 'FOSFATASA ALCALINA', 'SSA', 107.80, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'SSA', 486.20, now()),
	('Estudio', 'FEB', 'REACCIONES FEBRILES', 'SSA', 161.70, now()),
	('Estudio', 'FERR', 'FERRITINA', 'SSA', 643.00, now()),
	('Estudio', 'FIBRI', 'FIBRINOGENO', 'SSA', 359.98, now()),
	('Estudio', 'FOSFORO', 'FOSFORO', 'SSA', 128.59, now()),
	('Estudio', 'FR', 'FACTOR REUMATOIDE (LATEX)', 'SSA', 215.05, now()),
	('Estudio', 'FRC', 'FACTOR REUMATOIDE CUANTITATIVO', 'SSA', 338.00, now()),
	('Estudio', 'FSH', 'HORMONA FOLICULO ESTIMULANTE', 'SSA', 275.00, now()),
	('Estudio', 'FTA', 'AC. ANTI-TREPONEMA PALLIDUM  (FTA-ABS)', 'SSA', 704.06, now()),
	('Estudio', 'GASART', 'GASOMETRIA ARTERIAL', 'SSA', 1500.00, now()),
	('Estudio', 'GASVEN', 'GASOMETRIA VENOSA', 'SSA', 1500.00, now()),
	('Estudio', 'GGT', 'GAMA GLUTAMIL TRANSPEPTIDASA (GGT)', 'SSA', 107.80, now()),
	('Estudio', 'GLU', 'GLUCOSA', 'SSA', 107.80, now()),
	('Estudio', 'GLUPOS', 'GLUCOSA PRE Y POST PRANDIAL (2HRS)', 'SSA', 487.30, now()),
	('Estudio', 'GPO', 'GRUPO SANGUINEO', 'SSA', 110.00, now()),
	('Estudio', 'H1N1', 'PRUEBA PARA ANTIGENO DE LA INFLUENZA A, B, H1N1', 'SSA', 691.90, now()),
	('Estudio', 'H2G', 'ANTICUERPOS ANTI-HERPES II IgG', 'SSA', 511.00, now()),
	('Estudio', 'H2M', 'ANTICUERPOS ANTI-HERPES II IgM', 'SSA', 500.00, now()),
	('Estudio', 'HBA1C', 'HEMOGLOBINA GLICOSILADA (HbA1c)', 'SSA', 350.63, now()),
	('Estudio', 'HBsAg', 'ANTIGENO DE SUPERFICIE PARA HEPATITIS B (CUALITATIVO)', 'SSA', 342.65, now()),
	('Estudio', 'HC', 'HORMONA DE CRECIMIENTO', 'SSA', 619.00, now()),
	('Estudio', 'HCG', 'CUANTIFICACION DE FRAC. BETA GONADOTROPINA CORIONICA HUMANA (B-HCG)', 'SSA', 269.50, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'SSA', 1215.00, now()),
	('Estudio', 'HIERRO', 'HIERRO SERICO', 'SSA', 312.29, now()),
	('Estudio', 'HIV1Y2', 'AC. ANTI HIV 1 Y HIV 2', 'SSA', 292.60, now()),
	('Estudio', 'HLAB27', 'ANTIGENO HLA-B27', 'SSA', 1853.50, now()),
	('Estudio', 'HOMIR', 'INDICE DE RESISTENCIA A LA INSULINA (HOMA-IR)', 'SSA', 500.00, now()),
	('Estudio', 'HOMO', 'HOMOCISTEINA', 'SSA', 1168.20, now()),
	('Estudio', 'HPYH', 'ANTIGENO DE HELICOBACTER PYLORI EN HECES', 'SSA', 813.45, now()),
	('Estudio', 'HSEX', 'GLOBULINA FIJADORA DE HORMONAS SEXUALES', 'SSA', 1340.00, now()),
	('Estudio', 'HepAIgM', 'ANTICUERPOS ANTI-HEPATITIS A IgM', 'SSA', 675.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'SSA', 1148.00, now()),
	('Estudio', 'HerpG', 'ANTICUERPOS ANTI-HERPES I IgG', 'SSA', 569.00, now()),
	('Estudio', 'HerpM', 'ANTICUERPOS ANTI-HERPES I IgM', 'SSA', 569.00, now()),
	('Estudio', 'INPOS', 'INSULINA POST PANDRIAL', 'SSA', 654.50, now()),
	('Estudio', 'INS', 'INSULINA SERICA', 'SSA', 359.70, now()),
	('Estudio', 'IgA', 'INMUNOGLOBULINA A IgA', 'SSA', 486.00, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'SSA', 486.00, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'SSA', 486.00, now()),
	('Estudio', 'IgGGLIC', 'BETA 2 GLICOPROTEINA IgG', 'SSA', 1138.50, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'SSA', 486.00, now()),
	('Estudio', 'K', 'POTASIO', 'SSA', 288.75, now()),
	('Estudio', 'LAC', 'ACIDO LACTICO', 'SSA', 440.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'SSA', 295.46, now()),
	('Estudio', 'LH', 'HORMONA LUTEINIZANTE', 'SSA', 275.00, now()),
	('Estudio', 'LIPA', 'LIPASA', 'SSA', 177.10, now()),
	('Estudio', 'LIT', 'LITIO', 'SSA', 396.44, now()),
	('Estudio', 'MG', 'MAGNESIO SERICO', 'SSA', 128.59, now()),
	('Estudio', 'MICRO24', 'MICROALBUMINA EN ORINA DE 24 HORAS', 'SSA', 400.00, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'SSA', 288.75, now()),
	('Estudio', 'OSULL', 'PRUEBA O''SULLIVAN', 'SSA', 514.00, now()),
	('Estudio', 'PANCA', 'ANTICUERPOS ANTI-CITOPLASMA P-ANCA', 'SSA', 1566.00, now()),
	('Estudio', 'PAP', 'PAPANICOLAOU', 'SSA', 440.00, now()),
	('Estudio', 'PAPPCR', 'VIRUS DEL PAPILOMA HUMANO POR PCR', 'SSA', 2571.25, now()),
	('Paquete', 'PBASICO', 'PERFIL BASICO', 'SSA', 1089.00, now()),
	('Estudio', 'PCR', 'PROTEINA "C" REACTIVA (LATEX)', 'SSA', 186.34, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'SSA', 440.00, now()),
	('Estudio', 'PCT', 'PROCALCITONINA', 'SSA', 645.15, now()),
	('Paquete', 'PDIAB', 'PERFIL DIABETICO', 'SSA', 980.10, now()),
	('Paquete', 'PETS', 'PERFIL ETS', 'SSA', 1039.50, now()),
	('Estudio', 'PFH', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO', 'SSA', 792.00, now()),
	('Estudio', 'PH', 'PARATHORMONA (MOLECULA INTACTA)', 'SSA', 5730.00, now()),
	('Estudio', 'PIES', 'PRUEBA DE EMBARAZO EN SANGRE', 'SSA', 161.70, now()),
	('Estudio', 'PLG', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgG', 'SSA', 695.20, now()),
	('Estudio', 'PLIP', 'PERFIL DE LIPIDOS', 'SSA', 350.35, now()),
	('Estudio', 'PLM', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgM', 'SSA', 695.20, now()),
	('Estudio', 'POV5', 'PERFIL OVARICO 5', 'SSA', 1305.15, now()),
	('Estudio', 'POV6', 'PERFIL OVARICO 6', 'SSA', 1548.80, now()),
	('Estudio', 'PPD', 'PRUEBA CUTANEA DE TUBERCULINA', 'SSA', 1000.00, now()),
	('Paquete', 'PPNAT', 'PERFIL PRENATAL', 'SSA', 962.50, now()),
	('Paquete', 'PPRE', 'PERFIL PRENUPCIAL', 'SSA', 330.00, now()),
	('Paquete', 'PREOP', 'PERFIL PREOPERATORIO (solo lab)', 'SSA', 803.00, now()),
	('Paquete', 'PREUMA', 'PERFIL REUMATOLOGICO', 'SSA', 726.00, now()),
	('Estudio', 'PROG', 'PROGESTERONA', 'SSA', 275.00, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'SSA', 275.00, now()),
	('Estudio', 'PROTC', 'PROTEINA "C" DE LA COAGULACION', 'SSA', 2277.00, now()),
	('Estudio', 'PROTS', 'PROTEINA "S" DE LA COAGULACION', 'SSA', 2541.00, now()),
	('Estudio', 'PSAE', 'ANTIGENO PROSTATICO ESPECIFICO (PSA)', 'SSA', 412.50, now()),
	('Estudio', 'PSAF', 'ANTIGENO PROSTATICO LIBRE', 'SSA', 370.26, now()),
	('Paquete', 'PSCOMP', 'PERFIL SMAC/COMPLETO', 'SSA', 2904.00, now()),
	('Paquete', 'PSELE', 'PERFIL SMAC/ELECTROLITOS', 'SSA', 2075.70, now()),
	('Paquete', 'PSTIR', 'PERFIL SMAC/TIROIDEO', 'SSA', 2534.40, now()),
	('Estudio', 'PTORINA', 'PROTEINAS EN ORINA DE 24 HRS', 'SSA', 392.70, now()),
	('Estudio', 'PTOT', 'PROTEINAS TOTALES SERICAS', 'SSA', 138.60, now()),
	('Estudio', 'PYIgA', 'ANTICUERPOS HELICOBACTER PYLORI IgA', 'SSA', 607.75, now()),
	('Estudio', 'PYIgG', 'ANTICUERPOS HELICOBACTER PYLORI IgG', 'SSA', 607.75, now()),
	('Estudio', 'PYIgM', 'ANTICUERPOS HELICOBACTER PYLORI IgM', 'SSA', 607.75, now()),
	('Estudio', 'QS12', 'QUIMICA SANGUINEA DE 12 ELEMENTOS', 'SSA', 986.70, now()),
	('Estudio', 'QS24', 'QUIMICA SANGUINEA DE 24 ELEMENTOS', 'SSA', 1639.00, now()),
	('Estudio', 'QS3', 'QUIMICA SANGUINEA DE 3 ELEMENTOS', 'SSA', 265.65, now()),
	('Estudio', 'QS30', 'QUIMICA SANGUINEA DE 30 ELEMENTOS', 'SSA', 2400.00, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'SSA', 265.65, now()),
	('Estudio', 'QS4', 'QUIMICA  SANGUINEA DE 4 ELEMENTOS', 'SSA', 373.45, now()),
	('Estudio', 'QS4ALT', 'QUIMICA SANGUINEA DE 4 ELEMENTOS (COL, TRIG)', 'SSA', 373.45, now()),
	('Estudio', 'QS6', 'QUIMICA SANGUINEA DE 6 ELEMENTOS', 'SSA', 605.00, now()),
	('Estudio', 'RALCR', 'RELACION ALBUMINA/CREATININA', 'SSA', 540.00, now()),
	('Estudio', 'RETI', 'RETICULOCITOS', 'SSA', 115.50, now()),
	('Estudio', 'RICKIgG', 'ANTICUERPOS ANTI-RICKETTSIA IgG', 'SSA', 2133.00, now()),
	('Estudio', 'RICKIgM', 'ANTICUERPOS ANTI-RICKETTSIA IgM', 'SSA', 2133.00, now()),
	('Estudio', 'ROSA', 'ROSA DE BENGALA', 'SSA', 572.00, now()),
	('Estudio', 'SLC70', 'ANTICUERPOS ANTI-SCL-70', 'SSA', 945.00, now()),
	('Estudio', 'SOH', 'SANGRE OCULTA EN HECES', 'SSA', 107.80, now()),
	('Estudio', 'T3C', 'T3 CAPTACION', 'SSA', 333.80, now()),
	('Estudio', 'T3L', 'TRIYODOTIRONINA LIBRE (T3 libre)', 'SSA', 274.89, now()),
	('Estudio', 'T3T', 'TRIYODOTIRONINA (T3 total)', 'SSA', 275.00, now()),
	('Estudio', 'T4L', 'TIROXINA LIBRE (T4 libre)', 'SSA', 274.89, now()),
	('Estudio', 'T4T', 'TIROXINA (T4 total)', 'SSA', 275.00, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'SSA', 1424.50, now()),
	('Estudio', 'TC', 'TIEMPO DE COAGULACION', 'SSA', 154.00, now()),
	('Estudio', 'TESTO', 'TESTOSTERONA TOTAL', 'SSA', 304.92, now()),
	('Estudio', 'TGO', 'TRANSAMINASA GLUTAMICO OXALOACETICA (TGO)', 'SSA', 146.30, now()),
	('Estudio', 'TGP', 'TRANSAMINASA GLUTAMICO PIRUVICA (TGP)', 'SSA', 146.30, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'SSA', 957.00, now()),
	('Estudio', 'TIROG', 'TIROGLOBULINA', 'SSA', 466.40, now()),
	('Estudio', 'TOMDOM', 'SERVICIO A DOMICILIO', 'SSA', 495.00, now()),
	('Estudio', 'TORCHIII', 'PERFIL DE TORCH III IgM E IgG CUANTITATIVO', 'SSA', 3020.00, now()),
	('Estudio', 'TP', 'TIEMPO DE PROTROMBINA TP', 'SSA', 177.10, now()),
	('Estudio', 'TRANS', 'TRANSFERRINA', 'SSA', 385.00, now()),
	('Estudio', 'TRIG', 'TRIGLICERIDOS', 'SSA', 107.80, now()),
	('Estudio', 'TRIP', 'ANTICUERPOS ANTI-TRIPANOSOMA (CHAGAS)', 'SSA', 762.30, now()),
	('Estudio', 'TROI', 'TROPONINA I', 'SSA', 1870.00, now()),
	('Estudio', 'TS', 'TIEMPO DE SANGRADO', 'SSA', 154.00, now()),
	('Estudio', 'TSH', 'HORMONA ESTIMULANTE DE LA TIROIDES', 'SSA', 275.00, now()),
	('Estudio', 'TTP', 'TIEMPO DE TROMBOPLASTINA PARCIAL TTP', 'SSA', 177.10, now()),
	('Estudio', 'TUBIgG', 'AC. ANTI MYCOBACTERIUM TUBERCULOSIS (IgG)', 'SSA', 940.00, now()),
	('Estudio', 'TUBIgM', 'AC ANTI MYCOBACTERIUM TUBERCULOSIS IgM', 'SSA', 713.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'SSA', 107.80, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'SSA', 300.00, now()),
	('Estudio', 'URO', 'UROCULTIVO', 'SSA', 486.20, now()),
	('Estudio', 'VB12', 'VITAMINA B12', 'SSA', 764.50, now()),
	('Estudio', 'VDRL', 'VDRL', 'SSA', 115.50, now()),
	('Estudio', 'VITD25', 'VITAMINA D 25-OH', 'SSA', 850.00, now()),
	('Estudio', 'VITD3', 'VITAMINA D3', 'SSA', 2570.00, now()),
	('Estudio', 'VSG', 'VELOCIDAD DE SEDIMENTACION GLOBULAR VSG', 'SSA', 100.10, now()),
	('Estudio', 'ZINC', 'ZINC', 'SSA', 979.00, now()),
	('Estudio', 'aTPO', 'AC. ANTI PEROXIDASA  TIROIDEA (a-TPO)', 'SSA', 632.50, now()),
	('Estudio', 'testlibre2', 'TESTOSTERONA LIBRE', 'SSA', 544.50, now());

NOTIFY pgrst, 'reload schema';
