-- Precios de laboratorio de ISSSTE, tomados de la lista de precios vigente.
-- La mayoría ya estaban capturados; esta siembra corrige los que quedaron con
-- otro importe, así que primero se borra lo que haya de esas claves para ese
-- cliente y se vuelve a insertar. Eso la deja re-ejecutable y de paso limpia
-- los renglones repetidos que traía la lista.

delete from public.precios_estudios
where cliente = 'ISSSTE'
	and clave in (
		'17ALFA',
		'17HC24',
		'17HCO',
		'17HPN',
		'A1TRIP',
		'AAC',
		'AACLG',
		'AACLM',
		'AAP',
		'ACETONA',
		'ACL',
		'ACLE',
		'ACLY',
		'ACM',
		'ACPG',
		'ACSA',
		'ACSMITH',
		'ACT',
		'ACTA',
		'ACTB',
		'ACTG',
		'ACTH',
		'ACTM',
		'ADNA',
		'ADRE',
		'ADST',
		'ADT',
		'AELO1',
		'AFOL',
		'AFP',
		'AGCOVID',
		'AH',
		'ALB',
		'ALUMINIO',
		'AMI',
		'AMIF',
		'AMINO',
		'AMINOOR',
		'AMON',
		'ANA',
		'ANCA',
		'ANDRO',
		'ANFETA',
		'ANG',
		'ANTIRH',
		'APM',
		'APOA1',
		'APOB',
		'ARNA',
		'ARSOR24',
		'AT3',
		'AU',
		'AVMO',
		'AcEBARR',
		'AcEBG',
		'AcEBM',
		'AcEBN',
		'AcHI',
		'AcHepC',
		'AcI',
		'AcMG',
		'AcMIT',
		'AcMYC',
		'AcRM',
		'AcRO',
		'AcRUB',
		'AcSM',
		'AgEHB',
		'BARBIORI',
		'BD',
		'BENCE',
		'BENZODIA',
		'BETA2',
		'BHC',
		'BICARBONATO',
		'BILIS',
		'BNG',
		'BNP',
		'BSP',
		'BT',
		'BUSQBLAST',
		'C3',
		'C4',
		'CA125',
		'CA153',
		'CA199',
		'CA27',
		'CA724',
		'CABS',
		'CAIO',
		'CAL',
		'CALCI',
		'CALCRENBIL',
		'CARB',
		'CARBOX',
		'CARGA',
		'CATE',
		'CATEO',
		'CCP',
		'CD',
		'CEA',
		'CELPA',
		'CEXP',
		'CFE',
		'CH50',
		'CI',
		'CICLO',
		'CISTATINA',
		'CITOLI',
		'CITOS',
		'CITOURET',
		'CKMB',
		'CLAMY',
		'CLIQ',
		'CLONAZ',
		'CLOST',
		'CMV',
		'CMVM',
		'CNASA',
		'CO',
		'COBSER',
		'COCAINORIN',
		'COCIM',
		'COLI',
		'COP1',
		'COP2',
		'COP3',
		'COPCUL',
		'COPROL',
		'COPROT',
		'CORT',
		'CORU',
		'CPK',
		'CRE',
		'CREO',
		'CRISTLITO',
		'CRMC',
		'CROM',
		'CRYNEO',
		'CSEMEN',
		'CTG',
		'CULMYC',
		'CUOFT',
		'CURET',
		'CUSE',
		'CVAG',
		'CVAGMIC',
		'CVC',
		'CVIB',
		'CVIH',
		'CVIRAL',
		'DENG',
		'DEPU',
		'DFH',
		'DHEA',
		'DHEAS',
		'DHL',
		'DHT',
		'DIGO',
		'DIM',
		'DIOXCAR',
		'DNAN',
		'DOP3',
		'DOP6',
		'DOPA',
		'DXILO',
		'EGO',
		'EHISTOL',
		'ELECPRO',
		'ERIT',
		'ES3',
		'ES6',
		'ESP',
		'ESPDIR',
		'ESPIND',
		'EST',
		'ESTRO',
		'ESTSNOCON',
		'ETOT',
		'FAC',
		'FAC2',
		'FAC4',
		'FACI',
		'FAR',
		'FEB',
		'FENO',
		'FERR',
		'FIBRI',
		'FIX',
		'FOSAP',
		'FOSFORO',
		'FRC',
		'FROTIS',
		'FSH',
		'FTA',
		'FVII',
		'FVIII',
		'FVW',
		'FX',
		'FXI',
		'FXII',
		'GASART',
		'GAST',
		'GASVEN',
		'GGT',
		'GLU',
		'GLUCA',
		'GOTA',
		'GPO',
		'H1N1',
		'H2G',
		'H2M',
		'HAMU',
		'HBA1C',
		'HBsAg',
		'HC',
		'HCG',
		'HEMO',
		'HEMOAB',
		'HEMOAN',
		'HEPATE',
		'HEPBS',
		'HEPD',
		'HIERRO',
		'HIST',
		'HISTA',
		'HIV1Y2',
		'HIV4',
		'HLAB27',
		'HOMO',
		'HPYH',
		'HepAIgM',
		'HepAT',
		'HerpG',
		'HerpM',
		'IDROXINDO',
		'IFG',
		'IGF',
		'IGFBP',
		'IGS',
		'INH',
		'INPOS',
		'INS',
		'ISOCPK',
		'IgA',
		'IgD',
		'IgE',
		'IgG',
		'IgGGLIC',
		'IgM',
		'K',
		'KAPPLAMBSANG',
		'KAPPLAMORI',
		'LAMO',
		'LE',
		'LH',
		'LINFOCD',
		'LIPA',
		'LIT',
		'LKM',
		'MEMBAS',
		'MET24',
		'METAN',
		'MG',
		'MICRO',
		'MICROSD',
		'MYCO',
		'NA',
		'NDP',
		'OTI',
		'OXCARB',
		'PANCA',
		'PARVB19',
		'PCR',
		'PCRUL',
		'PCT',
		'PEPC',
		'PFH',
		'PGRA',
		'PH',
		'PHMASC',
		'PIES',
		'PLG',
		'PLIP',
		'PLM',
		'PLO',
		'POV6',
		'PPD',
		'PREUMA',
		'PROG',
		'PROL',
		'PROTC',
		'PROTS',
		'PSAE',
		'PTOT',
		'PYIgA',
		'PYIgG',
		'PYIgM',
		'QS12',
		'QS24',
		'QS27',
		'QS3',
		'QS3ALT',
		'QS4',
		'QS6',
		'REDU',
		'RENI',
		'RETI',
		'RPN',
		'SALSP',
		'SERO',
		'SLC70',
		'SOH',
		'SSB',
		'T4L',
		'T4T',
		'TAM',
		'TC',
		'TEO',
		'TESTO',
		'TGO',
		'TGP',
		'THC',
		'TINCHIN',
		'TINGRA',
		'TINWRI',
		'TIRO',
		'TIROG',
		'TORCHIII',
		'TOXG',
		'TOXM',
		'TOXO',
		'TP',
		'TRANS',
		'TRANSGLUM',
		'TRIP',
		'TROI',
		'TS',
		'TSH',
		'TT',
		'TTP',
		'TUBIgG',
		'URE',
		'UREAO',
		'URO',
		'VAG',
		'VALP',
		'VAM',
		'VAS',
		'VDRL',
		'VITD25',
		'VSG',
		'WBHIV2',
		'WBVIH1',
		'ZIKA',
		'aTPO',
		'cov19',
		'testlibre2'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', '17ALFA', '17 ALFA HIDROXIPROGESTERONA EN SUERO', 'ISSSTE', 693.00, now()),
	('Estudio', '17HC24', '17 HIDROXICORTICOESTEROIDES EN ORINA DE 24 HORAS', 'ISSSTE', 700.00, now()),
	('Estudio', '17HCO', '17 HIDROXICORTICOESTEROIDES EN SUERO', 'ISSSTE', 700.00, now()),
	('Estudio', '17HPN', '17 HIDROXIPROGESTERONA NEONATAL', 'ISSSTE', 700.00, now()),
	('Estudio', 'A1TRIP', 'ALFA-1 ANTI TRIPSINA', 'ISSSTE', 1204.00, now()),
	('Estudio', 'AAC', 'ANTICUERPOS ANTI-CENTROMERO', 'ISSSTE', 422.00, now()),
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'ISSSTE', 575.00, now()),
	('Estudio', 'AACLM', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgM', 'ISSSTE', 575.00, now()),
	('Estudio', 'AAP', 'ANTICUERPOS ANTI-PLAQUETARIOS', 'ISSSTE', 3169.00, now()),
	('Estudio', 'ACETONA', 'ACETONA', 'ISSSTE', 1594.00, now()),
	('Estudio', 'ACL', 'ANTICOAGULANTE LUPICO', 'ISSSTE', 821.00, now()),
	('Estudio', 'ACLE', 'ANTICUERPOS ANTI-LEPTOSPIRA', 'ISSSTE', 1070.00, now()),
	('Estudio', 'ACLY', 'ANTICUERPOS ANTI-BORRELIA BURGDORFERI IgG e IgM', 'ISSSTE', 1350.00, now()),
	('Estudio', 'ACM', 'ANTICUERPOS ANTI-MUSCULO LISO', 'ISSSTE', 810.00, now()),
	('Estudio', 'ACPG', 'ANTICUERPOS ANTI-PAROTIDITIS IgG', 'ISSSTE', 2026.00, now()),
	('Estudio', 'ACSA', 'ANTICUERPOS ANTI-SARAMPION IgG', 'ISSSTE', 916.00, now()),
	('Estudio', 'ACSMITH', 'AC. ANTI-SMITH', 'ISSSTE', 750.00, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'ISSSTE', 613.00, now()),
	('Estudio', 'ACTA', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgA', 'ISSSTE', 540.00, now()),
	('Estudio', 'ACTB', 'ANTICUERPOS ANTI-TUBERCULOSIS', 'ISSSTE', 1776.00, now()),
	('Estudio', 'ACTG', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgG', 'ISSSTE', 70.00, now()),
	('Estudio', 'ACTH', 'HORMONA ADRENOCORTICOTROFICA ACTH', 'ISSSTE', 590.00, now()),
	('Estudio', 'ACTM', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgM', 'ISSSTE', 920.00, now()),
	('Estudio', 'ADNA', 'ANTICUERPOS ANTI-DNA DOBLE CADENA', 'ISSSTE', 813.00, now()),
	('Estudio', 'ADRE', 'ADRENALINA EN PLASMA', 'ISSSTE', 670.00, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'ISSSTE', 1041.00, now()),
	('Estudio', 'ADT', 'ANDROSTENEDIONA', 'ISSSTE', 741.00, now()),
	('Estudio', 'AELO1', 'ANTI-ESTREPTOLISINA "O"', 'ISSSTE', 225.00, now()),
	('Estudio', 'AFOL', 'ACIDO FOLICO (FOLATOS)', 'ISSSTE', 539.00, now()),
	('Estudio', 'AFP', 'ALFAFETOPROTEINAS', 'ISSSTE', 418.00, now()),
	('Estudio', 'AGCOVID', 'PRUEBA DE ANTIGENO DE SARS-CoV-2 (COVID-19)', 'ISSSTE', 440.00, now()),
	('Estudio', 'AH', 'ANTICUERPOS HETEROFILOS (PAUL BUNNELL)', 'ISSSTE', 1050.00, now()),
	('Estudio', 'ALB', 'ALBUMINA SERICA', 'ISSSTE', 110.00, now()),
	('Estudio', 'ALUMINIO', 'ALUMINIO', 'ISSSTE', 1115.00, now()),
	('Estudio', 'AMI', 'AMILASA SERICA', 'ISSSTE', 181.00, now()),
	('Estudio', 'AMIF', 'AMIBA EN FRESCO', 'ISSSTE', 124.00, now()),
	('Estudio', 'AMINO', 'AMINOACIDOS EN SANGRE', 'ISSSTE', 3982.00, now()),
	('Estudio', 'AMINOOR', 'AMINOACIDOS EN ORINA DE 24HRS', 'ISSSTE', 1150.00, now()),
	('Estudio', 'AMON', 'AMONIO EN PLASMA', 'ISSSTE', 269.00, now()),
	('Estudio', 'ANA', 'ANTICUERPOS ANTINUCLEARES', 'ISSSTE', 651.00, now()),
	('Estudio', 'ANCA', 'ANTICUERPOS ANTI-CITOPLASMA C-ANCA', 'ISSSTE', 1395.00, now()),
	('Estudio', 'ANDRO', 'ANDROGENOS TOTALES', 'ISSSTE', 1750.00, now()),
	('Estudio', 'ANFETA', 'ANFETAMINAS EN ORINA', 'ISSSTE', 185.00, now()),
	('Estudio', 'ANG', 'ANGIOTENSINA', 'ISSSTE', 2022.00, now()),
	('Estudio', 'ANTIRH', 'ANTICUERPOS ANTI RH', 'ISSSTE', 156.00, now()),
	('Estudio', 'APM', 'ANTICUERPOS ANTI-PAROTIDITIS IgM', 'ISSSTE', 2026.00, now()),
	('Estudio', 'APOA1', 'APOLIPOPROTEINAS A-1', 'ISSSTE', 616.00, now()),
	('Estudio', 'APOB', 'APOLIPOPROTEINA B', 'ISSSTE', 1316.00, now()),
	('Estudio', 'ARNA', 'ANTICUERPOS ANTI-RNA', 'ISSSTE', 950.00, now()),
	('Estudio', 'ARSOR24', 'ARSENICO EN ORINA 24 HRS', 'ISSSTE', 1300.00, now()),
	('Estudio', 'AT3', 'ANTITROMBINA III', 'ISSSTE', 977.00, now()),
	('Estudio', 'AU', 'ACIDO URICO', 'ISSSTE', 111.00, now()),
	('Estudio', 'AVMO', 'ACIDO VANILMANDELICO EN ORINA DE  24 HORAS', 'ISSSTE', 1440.00, now()),
	('Estudio', 'AcEBARR', 'AC.ANTI-EPSTEIN BARR Ag TEMPRANO IgG(EA)', 'ISSSTE', 778.00, now()),
	('Estudio', 'AcEBG', 'AC. ANTI-EPSTEIN BARR IgG (CAPSIDE)', 'ISSSTE', 740.00, now()),
	('Estudio', 'AcEBM', 'AC. ANTI-EPSTEIN BARR IgM (CAPSIDE)', 'ISSSTE', 690.00, now()),
	('Estudio', 'AcEBN', 'ANTICUERPOS ANTI-EPSTEIN BARR Ag NUCLEAR IgG (EBNA-IgG)', 'ISSSTE', 718.00, now()),
	('Estudio', 'AcHI', 'ANTICUERPOS ANTI-HISTOPLASMA', 'ISSSTE', 1687.00, now()),
	('Estudio', 'AcHepC', 'ANTICUERPOS ANTI-HEPATITIS C (CUALITATIVO)', 'ISSSTE', 471.00, now()),
	('Estudio', 'AcI', 'ANTICUERPOS ANTI-INSULINA', 'ISSSTE', 1402.00, now()),
	('Estudio', 'AcMG', 'ANTICUERPOS ANTI-MYCOPLASMA PNEUMONIAE IgM', 'ISSSTE', 1563.00, now()),
	('Estudio', 'AcMIT', 'ANTICUERPOS ANTI-MITOCONDRIALES', 'ISSSTE', 810.00, now()),
	('Estudio', 'AcMYC', 'ANTICUERPOS ANTI-MYCOPLASMA PNEUMONIAE IgG', 'ISSSTE', 1563.00, now()),
	('Estudio', 'AcRM', 'ANTICUERPOS ANTI-RUBEOLA IgM', 'ISSSTE', 494.00, now()),
	('Estudio', 'AcRO', 'ANTICUERPOS ANTI-SSA Ro', 'ISSSTE', 720.00, now()),
	('Estudio', 'AcRUB', 'ANTICUERPOS ANTI-RUBEOLA IgG', 'ISSSTE', 494.00, now()),
	('Estudio', 'AcSM', 'ANTICUERPOS ANTI-SARAMPION IgM', 'ISSSTE', 916.00, now()),
	('Estudio', 'AgEHB', 'ANTIGENO E DE HEPATITIS B', 'ISSSTE', 613.00, now()),
	('Estudio', 'BARBIORI', 'BARBITURICOS EN ORINA', 'ISSSTE', 113.00, now()),
	('Estudio', 'BD', 'BILIRRUBINA DIRECTA', 'ISSSTE', 124.00, now()),
	('Estudio', 'BENCE', 'PROTEINA DE BENCE JONES', 'ISSSTE', 190.00, now()),
	('Estudio', 'BENZODIA', 'BENZODIACEPINAS', 'ISSSTE', 133.00, now()),
	('Estudio', 'BETA2', 'BETA 2 MICROGLOBULINA', 'ISSSTE', 2638.00, now()),
	('Estudio', 'BHC', 'BIOMETRIA HEMATICA COMPLETA (BHC)', 'ISSSTE', 133.00, now()),
	('Estudio', 'BICARBONATO', 'BICARBONATO (HC03)', 'ISSSTE', 668.00, now()),
	('Estudio', 'BILIS', 'BILIRRUBINAS', 'ISSSTE', 161.00, now()),
	('Estudio', 'BNG', 'BAAF DE NODULO GLANDULA', 'ISSSTE', 736.00, now()),
	('Estudio', 'BNP', 'PEPTIDO NATRIURETICO (BNP)', 'ISSSTE', 2053.00, now()),
	('Estudio', 'BSP', 'BAAF DE SECRECION DE PEZON', 'ISSSTE', 736.00, now()),
	('Estudio', 'BT', 'BILIRRUBINA TOTAL', 'ISSSTE', 134.00, now()),
	('Estudio', 'BUSQBLAST', 'BUSQUEDA DE BLASTOS', 'ISSSTE', 208.00, now()),
	('Estudio', 'C3', 'COMPLEMENTO C3', 'ISSSTE', 510.00, now()),
	('Estudio', 'C4', 'COMPLEMENTO C4', 'ISSSTE', 510.00, now()),
	('Estudio', 'CA125', 'AG. CARCINOMA OVARICO CA-125', 'ISSSTE', 463.00, now()),
	('Estudio', 'CA153', 'AG. CARCINOMA DE MAMA CA 15-3', 'ISSSTE', 589.00, now()),
	('Estudio', 'CA199', 'AG. CARCINOMA DE PANCREAS Y COLON CA 19-9', 'ISSSTE', 789.00, now()),
	('Estudio', 'CA27', 'AG. CARCINOMA DE MAMA CA 27-29', 'ISSSTE', 1158.00, now()),
	('Estudio', 'CA724', 'AG. CARCINOMA DE ESTOMAGO CA 72-4', 'ISSSTE', 982.00, now()),
	('Estudio', 'CABS', 'CULTIVO DE ABSCESO', 'ISSSTE', 437.00, now()),
	('Estudio', 'CAIO', 'CALCIO IOINIZADO', 'ISSSTE', 409.00, now()),
	('Estudio', 'CAL', 'CALCIO SERICO', 'ISSSTE', 142.00, now()),
	('Estudio', 'CALCI', 'CALCITONINA', 'ISSSTE', 809.00, now()),
	('Estudio', 'CALCRENBIL', 'CALCULO RENAL O BILIAR (ESTUDIO FISIOQUIMICO)', 'ISSSTE', 813.00, now()),
	('Estudio', 'CARB', 'CARBAMAZEPINA', 'ISSSTE', 710.00, now()),
	('Estudio', 'CARBOX', 'CARBOXIHEMOGLOBINA', 'ISSSTE', 705.00, now()),
	('Estudio', 'CARGA', 'CARGA VIRAL HEPATITIS C (RNA-VCH)', 'ISSSTE', 3010.00, now()),
	('Estudio', 'CATE', 'CATECOLAMINAS TOTALES', 'ISSSTE', 1736.00, now()),
	('Estudio', 'CATEO', 'CATECOLAMINAS TOTALES EN ORINA 24 HRS', 'ISSSTE', 1625.00, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'ISSSTE', 1100.00, now()),
	('Estudio', 'CD', 'COOMBS DIRECTO', 'ISSSTE', 190.00, now()),
	('Estudio', 'CEA', 'ANTIGENO CARCINOEMBRIONARIO', 'ISSSTE', 390.00, now()),
	('Estudio', 'CELPA', 'AC. ANTI-CELULAS PARIETALES', 'ISSSTE', 1120.00, now()),
	('Estudio', 'CEXP', 'CULTIVO DE EXPECTORACION', 'ISSSTE', 437.00, now()),
	('Estudio', 'CFE', 'CINETICA DE HIERRO', 'ISSSTE', 505.00, now()),
	('Estudio', 'CH50', 'COMPLEMENTO HEMOLITICO CH50', 'ISSSTE', 603.00, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'ISSSTE', 190.00, now()),
	('Estudio', 'CICLO', 'CICLOSPORINA TOTAL', 'ISSSTE', 1980.00, now()),
	('Estudio', 'CISTATINA', 'CISTATINA C', 'ISSSTE', 767.00, now()),
	('Estudio', 'CITOLI', 'CITOLOGICO DE LIQUIDOS', 'ISSSTE', 778.00, now()),
	('Estudio', 'CITOS', 'CITOQUIMICO DE LIQUIDO', 'ISSSTE', 589.00, now()),
	('Estudio', 'CITOURET', 'CITOLOGIA URETRAL', 'ISSSTE', 455.00, now()),
	('Estudio', 'CKMB', 'CREATIN-FOSFOQUINASA MB (CK-MB)', 'ISSSTE', 538.00, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'ISSSTE', 1290.00, now()),
	('Estudio', 'CLIQ', 'CULTIVO DE LIQUIDOS CORPORALES', 'ISSSTE', 455.00, now()),
	('Estudio', 'CLONAZ', 'CLONAZEPAN (RIVOTRIL)', 'ISSSTE', 985.00, now()),
	('Estudio', 'CLOST', 'CLOSTRIDIUM DIFFICILE TOXINA A, TOXINA B, + GDH', 'ISSSTE', 1010.00, now()),
	('Estudio', 'CMV', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgG', 'ISSSTE', 590.00, now()),
	('Estudio', 'CMVM', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgM', 'ISSSTE', 590.00, now()),
	('Estudio', 'CNASA', 'CULTIVO DE EXUDADO NASAL', 'ISSSTE', 455.00, now()),
	('Estudio', 'CO', 'CULTIVO DE HONGOS (MYCOLOGICO)', 'ISSSTE', 769.00, now()),
	('Estudio', 'COBSER', 'COBRE SERICO', 'ISSSTE', 935.00, now()),
	('Estudio', 'COCAINORIN', 'COCAINA EN ORINA', 'ISSSTE', 285.00, now()),
	('Estudio', 'COCIM', 'AC. ANTI-COCCIDIOIDES IMMITIS', 'ISSSTE', 2350.00, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'ISSSTE', 491.00, now()),
	('Estudio', 'COP1', 'COPROPARASITOSCOPICO (1 MUESTRA)', 'ISSSTE', 122.00, now()),
	('Estudio', 'COP2', 'COPROPARASITOSCOPICO (2 MUESTRAS)', 'ISSSTE', 198.00, now()),
	('Estudio', 'COP3', 'COPROPARASITOSCOPICO (3 MUESTRAS)', 'ISSSTE', 299.00, now()),
	('Estudio', 'COPCUL', 'COPROCULTIVO - CULTIVO DE HECES', 'ISSSTE', 510.00, now()),
	('Estudio', 'COPROL', 'COPROLOGICO GENERAL', 'ISSSTE', 250.00, now()),
	('Estudio', 'COPROT', 'COPROLOGICO CON ROTAVIRUS', 'ISSSTE', 670.00, now()),
	('Estudio', 'CORT', 'CORTISOL SERICO', 'ISSSTE', 395.00, now()),
	('Estudio', 'CORU', 'CORTISOL EN ORINA DE 24 HRS', 'ISSSTE', 532.00, now()),
	('Estudio', 'CPK', 'CREATIN-FOSFOQUINASA (CPK)', 'ISSSTE', 231.00, now()),
	('Estudio', 'CRE', 'CREATININA', 'ISSSTE', 111.00, now()),
	('Estudio', 'CREO', 'CREATININA EN ORINA DE UNA MICCION', 'ISSSTE', 105.00, now()),
	('Estudio', 'CRISTLITO', 'CRISTALOGRAFIA DE LITO', 'ISSSTE', 648.00, now()),
	('Estudio', 'CRMC', 'CRISTALOGRAFIA EN MOCO CERVICAL', 'ISSSTE', 451.00, now()),
	('Estudio', 'CROM', 'CROMO', 'ISSSTE', 1771.00, now()),
	('Estudio', 'CRYNEO', 'AC. ANTI-CRYPTOCOCCUS NEOFORMANS', 'ISSSTE', 2350.00, now()),
	('Estudio', 'CSEMEN', 'CULTIVO DE SEMEN (ESPERMOCULTIVO)', 'ISSSTE', 464.00, now()),
	('Estudio', 'CTG', 'CURVA DE TOLERANCIA A LA GLUCOSA 2 HORAS', 'ISSSTE', 230.00, now()),
	('Estudio', 'CULMYC', 'CULTIVO DE MYCOBACTERIUM TB.', 'ISSSTE', 769.00, now()),
	('Estudio', 'CUOFT', 'CULTIVO OFTALMICO', 'ISSSTE', 455.00, now()),
	('Estudio', 'CURET', 'CULTIVO URETRAL', 'ISSSTE', 455.00, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'ISSSTE', 534.00, now()),
	('Estudio', 'CVAG', 'CULTIVO DE EXUDADO CERVICO VAGINAL', 'ISSSTE', 523.00, now()),
	('Estudio', 'CVAGMIC', 'CULTIVO MYCOPLASMA/UREAPLASMA', 'ISSSTE', 570.00, now()),
	('Estudio', 'CVC', 'PCR CARGA VIRAL DE CITOMEGALOVIRUS (CMV)', 'ISSSTE', 4200.00, now()),
	('Estudio', 'CVIB', 'CULTIVO PARA VIBRIO CHOLERAE', 'ISSSTE', 570.00, now()),
	('Estudio', 'CVIH', 'CARGA VIRAL DE VIH-1', 'ISSSTE', 4600.00, now()),
	('Estudio', 'CVIRAL', 'CARGA VIRAL DE HEPATITIS B', 'ISSSTE', 3100.00, now()),
	('Estudio', 'DENG', 'DENGUE DUO', 'ISSSTE', 625.00, now()),
	('Estudio', 'DEPU', 'DEPURACION DE CREATININA EN ORINA DE 24 HORAS', 'ISSSTE', 200.00, now()),
	('Estudio', 'DFH', 'FENITOINA (DIFENILHIDANTOINA)', 'ISSSTE', 700.00, now()),
	('Estudio', 'DHEA', 'DHEA DEHIDROEPIANDROSTERONA', 'ISSSTE', 478.00, now()),
	('Estudio', 'DHEAS', 'DHEA-S DEHIDROEPIANDROSTERONA SULFATO', 'ISSSTE', 531.00, now()),
	('Estudio', 'DHL', 'DESHIDROGENASA LACTICA DHL', 'ISSSTE', 164.00, now()),
	('Estudio', 'DHT', 'DIHIDROTESTOSTERONA', 'ISSSTE', 1061.00, now()),
	('Estudio', 'DIGO', 'DIGOXINA', 'ISSSTE', 851.00, now()),
	('Estudio', 'DIM', 'DIMERO D', 'ISSSTE', 848.00, now()),
	('Estudio', 'DIOXCAR', 'DIOXIDO DE CARBONO (CO2)', 'ISSSTE', 256.00, now()),
	('Estudio', 'DNAN', 'ANTICUERPOS ANTI-DNA', 'ISSSTE', 613.00, now()),
	('Estudio', 'DOP3', 'ANTIDOPING DE 3 PARAMETROS', 'ISSSTE', 285.00, now()),
	('Estudio', 'DOP6', 'ANTIDOPING DE 6 PARAMETROS', 'ISSSTE', 609.00, now()),
	('Estudio', 'DOPA', 'DOPAMINA EN PLASMA', 'ISSSTE', 1150.00, now()),
	('Estudio', 'DXILO', 'D´XILOSA', 'ISSSTE', 1308.00, now()),
	('Estudio', 'EGO', 'EXAMEN GENERAL DE ORINA', 'ISSSTE', 135.00, now()),
	('Estudio', 'EHISTOL', 'AC. ANTI E HISTOLYTICA (SERAMEBA)', 'ISSSTE', 716.00, now()),
	('Estudio', 'ELECPRO', 'ELECTROFORESIS DE PROTEINAS', 'ISSSTE', 980.00, now()),
	('Estudio', 'ERIT', 'ERITROPOYETINA (EPO)', 'ISSSTE', 1141.00, now()),
	('Estudio', 'ES3', 'ELECTROLITOS SERICOS DE 3 PARAMETROS', 'ISSSTE', 390.00, now()),
	('Estudio', 'ES6', 'ELECTROLITOS SERICOS DE 6 PARAMETROS', 'ISSSTE', 750.00, now()),
	('Estudio', 'ESP', 'ESPERMATOBIOSCOPIA', 'ISSSTE', 430.00, now()),
	('Estudio', 'ESPDIR', 'AC. ANTI-ESPERMATOZOIDES (DIRECTOS)', 'ISSSTE', 1509.00, now()),
	('Estudio', 'ESPIND', 'AC. ANTI-ESPERMATOZOIDES(INDIRECTOS)', 'ISSSTE', 1509.00, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'ISSSTE', 251.00, now()),
	('Estudio', 'ESTRO', 'ESTRONA (E1)', 'ISSSTE', 1461.00, now()),
	('Estudio', 'ESTSNOCON', 'ESTRIOL SERICO NO CONJUGADO (E3)', 'ISSSTE', 641.00, now()),
	('Estudio', 'ETOT', 'ESTROGENOS TOTALES', 'ISSSTE', 401.00, now()),
	('Estudio', 'FAC', 'FOSFATASA ALCALINA', 'ISSSTE', 134.00, now()),
	('Estudio', 'FAC2', 'FACTOR II DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'FAC4', 'FACTOR V DE LA COAGULACIÓN', 'ISSSTE', 2669.00, now()),
	('Estudio', 'FACI', 'FOSFATASA ACIDA TOTAL', 'ISSSTE', 284.00, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'ISSSTE', 525.00, now()),
	('Estudio', 'FEB', 'REACCIONES FEBRILES', 'ISSSTE', 161.00, now()),
	('Estudio', 'FENO', 'FENOBARBITAL', 'ISSSTE', 818.00, now()),
	('Estudio', 'FERR', 'FERRITINA', 'ISSSTE', 481.00, now()),
	('Estudio', 'FIBRI', 'FIBRINOGENO', 'ISSSTE', 343.00, now()),
	('Estudio', 'FIX', 'FACTOR IX DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'FOSAP', 'FOSFATASA ACIDA FRACCION PROSTATICA', 'ISSSTE', 1343.00, now()),
	('Estudio', 'FOSFORO', 'FOSFORO', 'ISSSTE', 149.00, now()),
	('Estudio', 'FRC', 'FACTOR REUMATOIDE CUANTITATIVO', 'ISSSTE', 225.00, now()),
	('Estudio', 'FROTIS', 'FROTIS DE SANGRE PERIFERICA', 'ISSSTE', 124.00, now()),
	('Estudio', 'FSH', 'HORMONA FOLICULO ESTIMULANTE', 'ISSSTE', 240.00, now()),
	('Estudio', 'FTA', 'AC. ANTI-TREPONEMA PALLIDUM  (FTA-ABS)', 'ISSSTE', 772.00, now()),
	('Estudio', 'FVII', 'FACTOR VII DE LA COAGULACION', 'ISSSTE', 1079.00, now()),
	('Estudio', 'FVIII', 'FACTOR VIII DE LA COAGULACION', 'ISSSTE', 1079.00, now()),
	('Estudio', 'FVW', 'FACTOR VON WILLWBRAND', 'ISSSTE', 2374.00, now()),
	('Estudio', 'FX', 'FACTOR X DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'FXI', 'FACTOR XI DE LA COAGULACIÓN', 'ISSSTE', 1179.00, now()),
	('Estudio', 'FXII', 'FACTOR XII DE LA COAGULACIÓN', 'ISSSTE', 1179.00, now()),
	('Estudio', 'GASART', 'GASOMETRIA ARTERIAL', 'ISSSTE', 1350.00, now()),
	('Estudio', 'GAST', 'GASTRINA', 'ISSSTE', 712.00, now()),
	('Estudio', 'GASVEN', 'GASOMETRIA VENOSA', 'ISSSTE', 1350.00, now()),
	('Estudio', 'GGT', 'GAMA GLUTAMIL TRANSPEPTIDASA (GGT)', 'ISSSTE', 139.00, now()),
	('Estudio', 'GLU', 'GLUCOSA', 'ISSSTE', 124.00, now()),
	('Estudio', 'GLUCA', 'GLUCAGON', 'ISSSTE', 1955.00, now()),
	('Estudio', 'GOTA', 'GOTA GRUESA (PLASMODIUM)', 'ISSSTE', 205.00, now()),
	('Estudio', 'GPO', 'GRUPO SANGUINEO', 'ISSSTE', 128.00, now()),
	('Estudio', 'H1N1', 'PRUEBA PARA ANTIGENO DE LA INFLUENZA A, B, H1N1', 'ISSSTE', 735.00, now()),
	('Estudio', 'H2G', 'ANTICUERPOS ANTI-HERPES II IgG', 'ISSSTE', 673.00, now()),
	('Estudio', 'H2M', 'ANTICUERPOS ANTI-HERPES II IgM', 'ISSSTE', 673.00, now()),
	('Estudio', 'HAMU', 'HORMONA ANTIMULLERIANA', 'ISSSTE', 2803.00, now()),
	('Estudio', 'HBA1C', 'HEMOGLOBINA GLICOSILADA (HbA1c)', 'ISSSTE', 334.00, now()),
	('Estudio', 'HBsAg', 'ANTIGENO DE SUPERFICIE PARA HEPATITIS B (CUALITATIVO)', 'ISSSTE', 375.00, now()),
	('Estudio', 'HC', 'HORMONA DE CRECIMIENTO', 'ISSSTE', 502.00, now()),
	('Estudio', 'HCG', 'CUANTIFICACION DE FRAC. BETA GONADOTROPINA CORIONICA HUMANA (B-HCG)', 'ISSSTE', 390.00, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'ISSSTE', 1400.00, now()),
	('Estudio', 'HEMOAB', 'HEMOCULTIVO AEROBIO', 'ISSSTE', 1400.00, now()),
	('Estudio', 'HEMOAN', 'HEMOCULTIVO ANAEROBIOS', 'ISSSTE', 1400.00, now()),
	('Estudio', 'HEPATE', 'AC. ANTI-HEPATITIS E (IGM)', 'ISSSTE', 824.00, now()),
	('Estudio', 'HEPBS', 'AG. S DE HEPATITIS B (HBSAG)', 'ISSSTE', 370.00, now()),
	('Estudio', 'HEPD', 'AC.ANTI-HEPATITIS D (HDV)', 'ISSSTE', 3513.00, now()),
	('Estudio', 'HIERRO', 'HIERRO SERICO', 'ISSSTE', 198.00, now()),
	('Estudio', 'HIST', 'AC. ATI- HISTONAS', 'ISSSTE', 1042.00, now()),
	('Estudio', 'HISTA', 'HISTAMINA', 'ISSSTE', 1985.00, now()),
	('Estudio', 'HIV1Y2', 'AC. ANTI HIV 1 Y HIV 2', 'ISSSTE', 332.00, now()),
	('Estudio', 'HIV4', 'HIV 4TA GENERACIÓN', 'ISSSTE', 357.00, now()),
	('Estudio', 'HLAB27', 'ANTIGENO HLA-B27', 'ISSSTE', 2204.00, now()),
	('Estudio', 'HOMO', 'HOMOCISTEINA', 'ISSSTE', 1148.00, now()),
	('Estudio', 'HPYH', 'ANTIGENO DE HELICOBACTER PYLORI EN HECES', 'ISSSTE', 560.00, now()),
	('Estudio', 'HepAIgM', 'ANTICUERPOS ANTI-HEPATITIS A IgM', 'ISSSTE', 562.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'ISSSTE', 669.00, now()),
	('Estudio', 'HerpG', 'ANTICUERPOS ANTI-HERPES I IgG', 'ISSSTE', 673.00, now()),
	('Estudio', 'HerpM', 'ANTICUERPOS ANTI-HERPES I IgM', 'ISSSTE', 673.00, now()),
	('Estudio', 'IDROXINDO', 'ACIDO 5 -IDROXI-INDOLACETICO', 'ISSSTE', 1767.00, now()),
	('Estudio', 'IFG', 'INDICE DE FILTRADO GLOMERULAR (GFR)', 'ISSSTE', 700.00, now()),
	('Estudio', 'IGF', 'SOMATOMEDINA C (IGF-1)', 'ISSSTE', 785.00, now()),
	('Estudio', 'IGFBP', 'FACTOR HUMANO DE CRECIMIENTO SIMILAR A LA INSULINA(IGFBP-3)', 'ISSSTE', 1050.00, now()),
	('Estudio', 'IGS', 'INMUNOGLOBULINAS "A", "G","M" Y "E"', 'ISSSTE', 1097.00, now()),
	('Estudio', 'INH', 'INHIBINA A', 'ISSSTE', 1866.00, now()),
	('Estudio', 'INPOS', 'INSULINA POST PANDRIAL', 'ISSSTE', 625.00, now()),
	('Estudio', 'INS', 'INSULINA SERICA', 'ISSSTE', 343.00, now()),
	('Estudio', 'ISOCPK', 'ISOENZIMAS DE CPK', 'ISSSTE', 1200.00, now()),
	('Estudio', 'IgA', 'INMUNOGLOBULINA A IgA', 'ISSSTE', 394.00, now()),
	('Estudio', 'IgD', 'INMUNOGLOBULINA D IgD', 'ISSSTE', 1394.00, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'ISSSTE', 453.00, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'ISSSTE', 394.00, now()),
	('Estudio', 'IgGGLIC', 'BETA 2 GLICOPROTEINA IgG', 'ISSSTE', 924.00, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'ISSSTE', 394.00, now()),
	('Estudio', 'K', 'POTASIO', 'ISSSTE', 149.00, now()),
	('Estudio', 'KAPPLAMBSANG', 'CADENAS KAPPA/LAMBDA (LIGERAS) EN SANGRE', 'ISSSTE', 1405.00, now()),
	('Estudio', 'KAPPLAMORI', 'CADENAS KAPPA/LAMBDA (LIGERAS) EN ORINA', 'ISSSTE', 1105.00, now()),
	('Estudio', 'LAMO', 'LAMOTRIGINA', 'ISSSTE', 1762.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'ISSSTE', 282.00, now()),
	('Estudio', 'LH', 'HORMONA LUTEINIZANTE', 'ISSSTE', 250.00, now()),
	('Estudio', 'LINFOCD', 'LINFOCITOS CD4/CD8', 'ISSSTE', 4418.00, now()),
	('Estudio', 'LIPA', 'LIPASA', 'ISSSTE', 254.00, now()),
	('Estudio', 'LIT', 'LITIO', 'ISSSTE', 378.00, now()),
	('Estudio', 'LKM', 'AC. ANTI LKM/1 (IGG) (MICROSOMALES HIGADO Y RIÑON)', 'ISSSTE', 1295.00, now()),
	('Estudio', 'MEMBAS', 'AC.ANTI - MEMBRANA BASAL GLOMERULAR', 'ISSSTE', 1294.00, now()),
	('Estudio', 'MET24', 'METANEFRINAS TOTALES EN ORINA DE 24 HORAS', 'ISSSTE', 1696.00, now()),
	('Estudio', 'METAN', 'METANEFRINAS EN PLASMA', 'ISSSTE', 1696.00, now()),
	('Estudio', 'MG', 'MAGNESIO SERICO', 'ISSSTE', 149.00, now()),
	('Estudio', 'MICRO', 'MICROALBUMINA EN ORINA DE UNA SOLA MICCION', 'ISSSTE', 674.00, now()),
	('Estudio', 'MICROSD', 'MICROSCOPIA DIRECTA', 'ISSSTE', 220.00, now()),
	('Estudio', 'MYCO', 'MYCOBACTERIUM TUBERCULOSIS POR PCR', 'ISSSTE', 4124.00, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'ISSSTE', 334.00, now()),
	('Estudio', 'NDP', 'NORADRENALINA EN PLASMA', 'ISSSTE', 1150.00, now()),
	('Estudio', 'OTI', 'CULTIVO OTICO', 'ISSSTE', 446.00, now()),
	('Estudio', 'OXCARB', 'OXCARBAZEPINA', 'ISSSTE', 2300.00, now()),
	('Estudio', 'PANCA', 'ANTICUERPOS ANTI-CITOPLASMA P-ANCA', 'ISSSTE', 1395.00, now()),
	('Estudio', 'PARVB19', 'PARVOVIRUS B19', 'ISSSTE', 2250.00, now()),
	('Estudio', 'PCR', 'PROTEINA "C" REACTIVA (LATEX)', 'ISSSTE', 215.00, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'ISSSTE', 540.00, now()),
	('Estudio', 'PCT', 'PROCALCITONINA', 'ISSSTE', 816.00, now()),
	('Estudio', 'PEPC', 'PEPTIDO C', 'ISSSTE', 813.00, now()),
	('Estudio', 'PFH', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO', 'ISSSTE', 688.00, now()),
	('Estudio', 'PGRA', 'PRUEBA DE GRAHAM', 'ISSSTE', 125.00, now()),
	('Estudio', 'PH', 'PARATHORMONA (MOLECULA INTACTA)', 'ISSSTE', 984.00, now()),
	('Estudio', 'PHMASC', 'PERFIL HORMONAL MASCULINO', 'ISSSTE', 1190.00, now()),
	('Estudio', 'PIES', 'PRUEBA DE EMBARAZO EN SANGRE', 'ISSSTE', 245.00, now()),
	('Estudio', 'PLG', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgG', 'ISSSTE', 663.00, now()),
	('Estudio', 'PLIP', 'PERFIL DE LIPIDOS', 'ISSSTE', 437.00, now()),
	('Estudio', 'PLM', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgM', 'ISSSTE', 663.00, now()),
	('Estudio', 'PLO', 'PLOMO EN SANGRE', 'ISSSTE', 736.00, now()),
	('Estudio', 'POV6', 'PERFIL OVARICO 6', 'ISSSTE', 1015.00, now()),
	('Estudio', 'PPD', 'PRUEBA CUTANEA DE TUBERCULINA', 'ISSSTE', 1800.00, now()),
	('Paquete', 'PREUMA', 'PERFIL REUMATOLOGICO', 'ISSSTE', 741.00, now()),
	('Estudio', 'PROG', 'PROGESTERONA', 'ISSSTE', 250.00, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'ISSSTE', 250.00, now()),
	('Estudio', 'PROTC', 'PROTEINA "C" DE LA COAGULACION', 'ISSSTE', 2348.00, now()),
	('Estudio', 'PROTS', 'PROTEINA "S" DE LA COAGULACION', 'ISSSTE', 2348.00, now()),
	('Estudio', 'PSAE', 'ANTIGENO PROSTATICO ESPECIFICO (PSA)', 'ISSSTE', 375.00, now()),
	('Estudio', 'PTOT', 'PROTEINAS TOTALES SERICAS', 'ISSSTE', 141.00, now()),
	('Estudio', 'PYIgA', 'ANTICUERPOS HELICOBACTER PYLORI IgA', 'ISSSTE', 780.00, now()),
	('Estudio', 'PYIgG', 'ANTICUERPOS HELICOBACTER PYLORI IgG', 'ISSSTE', 660.00, now()),
	('Estudio', 'PYIgM', 'ANTICUERPOS HELICOBACTER PYLORI IgM', 'ISSSTE', 660.00, now()),
	('Estudio', 'QS12', 'QUIMICA SANGUINEA DE 12 ELEMENTOS', 'ISSSTE', 770.00, now()),
	('Estudio', 'QS24', 'QUIMICA SANGUINEA DE 24 ELEMENTOS', 'ISSSTE', 1114.00, now()),
	('Estudio', 'QS27', 'QUIMICA SANGUINEA DE 27 ELEMENTOS', 'ISSSTE', 1114.00, now()),
	('Estudio', 'QS3', 'QUIMICA SANGUINEA DE 3 ELEMENTOS', 'ISSSTE', 239.00, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'ISSSTE', 239.00, now()),
	('Estudio', 'QS4', 'QUIMICA  SANGUINEA DE 4 ELEMENTOS', 'ISSSTE', 248.00, now()),
	('Estudio', 'QS6', 'QUIMICA SANGUINEA DE 6 ELEMENTOS', 'ISSSTE', 411.00, now()),
	('Estudio', 'REDU', 'AZUCARES REDUCTORES EN HECES', 'ISSSTE', 124.00, now()),
	('Estudio', 'RENI', 'RENINA EN PLASMA', 'ISSSTE', 580.00, now()),
	('Estudio', 'RETI', 'RETICULOCITOS', 'ISSSTE', 128.00, now()),
	('Estudio', 'RPN', 'ANTICUERPOS ANTI-RNP', 'ISSSTE', 810.00, now()),
	('Estudio', 'SALSP', 'AC ANTI- SALMONELLA SP', 'ISSSTE', 2100.00, now()),
	('Estudio', 'SERO', 'SEROTONINA', 'ISSSTE', 1482.00, now()),
	('Estudio', 'SLC70', 'ANTICUERPOS ANTI-SCL-70', 'ISSSTE', 808.00, now()),
	('Estudio', 'SOH', 'SANGRE OCULTA EN HECES', 'ISSSTE', 179.00, now()),
	('Estudio', 'SSB', 'ANTICUERPOS ANTI-SSB La', 'ISSSTE', 720.00, now()),
	('Estudio', 'T4L', 'TIROXINA LIBRE (T4 libre)', 'ISSSTE', 240.00, now()),
	('Estudio', 'T4T', 'TIROXINA (T4 total)', 'ISSSTE', 240.00, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'ISSSTE', 1695.00, now()),
	('Estudio', 'TC', 'TIEMPO DE COAGULACION', 'ISSSTE', 80.00, now()),
	('Estudio', 'TEO', 'AMINOFILINA(TEOFILINA)', 'ISSSTE', 1307.00, now()),
	('Estudio', 'TESTO', 'TESTOSTERONA TOTAL', 'ISSSTE', 301.00, now()),
	('Estudio', 'TGO', 'TRANSAMINASA GLUTAMICO OXALOACETICA (TGO)', 'ISSSTE', 140.00, now()),
	('Estudio', 'TGP', 'TRANSAMINASA GLUTAMICO PIRUVICA (TGP)', 'ISSSTE', 140.00, now()),
	('Estudio', 'THC', 'CANNABINOIDES MARIHUANA', 'ISSSTE', 120.00, now()),
	('Estudio', 'TINCHIN', 'TINCION TINTA CHINA (CRIPTOCOCCUS)', 'ISSSTE', 220.00, now()),
	('Estudio', 'TINGRA', 'TINCION DE GRAAM', 'ISSSTE', 220.00, now()),
	('Estudio', 'TINWRI', 'TINCION DE WRIGHT', 'ISSSTE', 160.00, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'ISSSTE', 780.00, now()),
	('Estudio', 'TIROG', 'TIROGLOBULINA', 'ISSSTE', 378.00, now()),
	('Estudio', 'TORCHIII', 'PERFIL DE TORCH III IgM E IgG CUANTITATIVO', 'ISSSTE', 1785.00, now()),
	('Estudio', 'TOXG', 'ANTICUERPOS ANTI-TOXOPLASMA GONDII IgG', 'ISSSTE', 494.00, now()),
	('Estudio', 'TOXM', 'ANTICUERPOS ANTI-TOXOPLASMA GONDII IgM', 'ISSSTE', 494.00, now()),
	('Estudio', 'TOXO', 'ANTICUERPOS ANTI-TOXOCARA', 'ISSSTE', 1857.00, now()),
	('Estudio', 'TP', 'TIEMPO DE PROTROMBINA TP', 'ISSSTE', 194.00, now()),
	('Estudio', 'TRANS', 'TRANSFERRINA', 'ISSSTE', 412.00, now()),
	('Estudio', 'TRANSGLUM', 'AC. ANTI TRANSGLUTAMINASA (IgA)', 'ISSSTE', 1820.00, now()),
	('Estudio', 'TRIP', 'ANTICUERPOS ANTI-TRIPANOSOMA (CHAGAS)', 'ISSSTE', 718.00, now()),
	('Estudio', 'TROI', 'TROPONINA I', 'ISSSTE', 945.00, now()),
	('Estudio', 'TS', 'TIEMPO DE SANGRADO', 'ISSSTE', 80.00, now()),
	('Estudio', 'TSH', 'HORMONA ESTIMULANTE DE LA TIROIDES', 'ISSSTE', 235.00, now()),
	('Estudio', 'TT', 'TIEMPO DE TROMBINA', 'ISSSTE', 319.00, now()),
	('Estudio', 'TTP', 'TIEMPO DE TROMBOPLASTINA PARCIAL TTP', 'ISSSTE', 343.00, now()),
	('Estudio', 'TUBIgG', 'AC. ANTI MYCOBACTERIUM TUBERCULOSIS (IgG)', 'ISSSTE', 705.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'ISSSTE', 111.00, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'ISSSTE', 260.00, now()),
	('Estudio', 'URO', 'UROCULTIVO', 'ISSSTE', 480.00, now()),
	('Estudio', 'VAG', 'ANTICUERPOS ANTI-VARICELA IgG', 'ISSSTE', 1216.00, now()),
	('Estudio', 'VALP', 'ACIDO VALPROICO', 'ISSSTE', 750.00, now()),
	('Estudio', 'VAM', 'ANTICUERPOS ANTI-VARICELA IgM', 'ISSSTE', 1216.00, now()),
	('Estudio', 'VAS', 'HORMONA ANTIDIURETICA (VASOPRESINA)', 'ISSSTE', 2580.00, now()),
	('Estudio', 'VDRL', 'VDRL', 'ISSSTE', 142.00, now()),
	('Estudio', 'VITD25', 'VITAMINA D 25-OH', 'ISSSTE', 890.00, now()),
	('Estudio', 'VSG', 'VELOCIDAD DE SEDIMENTACION GLOBULAR VSG', 'ISSSTE', 115.00, now()),
	('Estudio', 'WBHIV2', 'WESTERN BLOT VIH 2', 'ISSSTE', 4050.00, now()),
	('Estudio', 'WBVIH1', 'WESTERN BLOT VIH 1', 'ISSSTE', 2610.00, now()),
	('Estudio', 'ZIKA', 'ANTICUERPOS VIRUS DE ZIKA', 'ISSSTE', 3600.00, now()),
	('Estudio', 'aTPO', 'AC. ANTI PEROXIDASA  TIROIDEA (a-TPO)', 'ISSSTE', 705.00, now()),
	('Estudio', 'cov19', 'ANTICUERPOS SARS-CoV-2 (COVID-19) IgM e IgG', 'ISSSTE', 1428.00, now()),
	('Estudio', 'testlibre2', 'TESTOSTERONA LIBRE', 'ISSSTE', 441.00, now());

NOTIFY pgrst, 'reload schema';
