delete from public.precios_estudios
where cliente = 'Particular'
	and clave in (
		'UO-REIMPRESION-CDS-USB',
		'UO-REIMPRESION-PLACA',
		'UO-URGENCIA-INTERPRETACION-ESTUDIO-CONTRASTADO',
		'UO-URGENCIA-INTERPRETACION-PLACA-RX',
		'UO-URGENCIA-INTERPRETACION-TOMOGRAFIA',
		'UO-URGENCIA-TECNICO-ESTUDIO-CONTRASTADO',
		'UO-URGENCIA-TECNICO-RADIOLOGO-RX',
		'UO-URGENCIA-TECNICO-TOMOGRAFIA',
		'UO-URGENCIA-ULTRASONIDO-CONVENCIONAL',
		'UO-URGENCIA-ULTRASONIDO-DOPPLER',
		'UO-URGENCIA-ULTRASONIDO-ENDOCAVITARIO'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'UO-REIMPRESION-CDS-USB', 'REIMPRESION DE CDS / USB', 'Particular', 110.00, now()),
	('Estudio', 'UO-REIMPRESION-PLACA', 'REIMPRESION DE PLACA', 'Particular', 320.00, now()),
	('Estudio', 'UO-URGENCIA-INTERPRETACION-ESTUDIO-CONTRASTADO', 'URGENCIA INTERPRETACION ESTUDIO CONTRASTADO', 'Particular', 1030.00, now()),
	('Estudio', 'UO-URGENCIA-INTERPRETACION-PLACA-RX', 'URGENCIA INTERPRETACION PLACA RX', 'Particular', 590.00, now()),
	('Estudio', 'UO-URGENCIA-INTERPRETACION-TOMOGRAFIA', 'URGENCIA INTERPRETACION TOMOGRAFIA', 'Particular', 1400.00, now()),
	('Estudio', 'UO-URGENCIA-TECNICO-ESTUDIO-CONTRASTADO', 'URGENCIA TECNICO ESTUDIO CONTRASTADO', 'Particular', 920.00, now()),
	('Estudio', 'UO-URGENCIA-TECNICO-RADIOLOGO-RX', 'URGENCIA TECNICO RADIOLOGO RX', 'Particular', 590.00, now()),
	('Estudio', 'UO-URGENCIA-TECNICO-TOMOGRAFIA', 'URGENCIA TECNICO TOMOGRAFIA', 'Particular', 970.00, now()),
	('Estudio', 'UO-URGENCIA-ULTRASONIDO-CONVENCIONAL', 'URGENCIA ULTRASONIDO CONVENCIONAL', 'Particular', 970.00, now()),
	('Estudio', 'UO-URGENCIA-ULTRASONIDO-DOPPLER', 'URGENCIA ULTRASONIDO DOPPLER', 'Particular', 2160.00, now()),
	('Estudio', 'UO-URGENCIA-ULTRASONIDO-ENDOCAVITARIO', 'URGENCIA ULTRASONIDO ENDOCAVITARIO', 'Particular', 1130.00, now());
