insert into public.estudios_imagen_catalogo (
	clave,
	descripcion,
	empresa_operativa,
	modalidad,
	area,
	region_anatomica,
	requiere_contraste,
	requiere_interpretacion,
	dias_proceso,
	activo
)
values
	('TAC-ANGIOTOMOGRAFIA-UNA-REGION', 'ANGIOTOMOGRAFIA UNA REGION', 'CDI', 'tomografia', 'Tomografia', 'Una region', true, true, 1, true),
	('TAC-ABDOMINOPELVICA-VALSALVA', 'TAC ABDOMINOPELVICA CON VALSALVA', 'CDI', 'tomografia', 'Tomografia', 'Abdominopelvica', false, true, 1, true),
	('TAC-ABDOMINOPELVICA-CONTRASTADA', 'TAC ABDOMINOPELVICA CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Abdominopelvica', true, true, 1, true),
	('TAC-ABDOMINOPELVICO-DOBLE-CONTRASTE', 'TAC ABDOMINO-PELVICO DOBLE CONTRASTE', 'CDI', 'tomografia', 'Tomografia', 'Abdominopelvica', true, true, 1, true),
	('TAC-ABDOMINOPELVICO-SIMPLE', 'TAC ABDOMINOPELVICO SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Abdominopelvica', false, true, 1, true),
	('TAC-ABDOMEN-CONTRASTADA', 'TAC DE ABDOMEN CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Abdomen', true, true, 1, true),
	('TAC-ABDOMEN-SIMPLE', 'TAC DE ABDOMEN SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Abdomen', false, true, 1, true),
	('TAC-CADERA', 'TAC DE CADERA', 'CDI', 'tomografia', 'Tomografia', 'Cadera', false, true, 1, true),
	('TAC-CADERA-CONTRASTADA', 'TAC DE CADERA CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Cadera', true, true, 1, true),
	('TAC-COLUMNA-CERVICAL', 'TAC DE COLUMNA CERVICAL', 'CDI', 'tomografia', 'Tomografia', 'Columna cervical', false, true, 1, true),
	('TAC-COLUMNA-CERVICAL-CONTRASTADA', 'TAC DE COLUMNA CERVICAL CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Columna cervical', true, true, 1, true),
	('TAC-COLUMNA-DORSAL', 'TAC DE COLUMNA DORSAL', 'CDI', 'tomografia', 'Tomografia', 'Columna dorsal', false, true, 1, true),
	('TAC-COLUMNA-DORSAL-CONTRASTADA', 'TAC DE COLUMNA DORSAL CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Columna dorsal', true, true, 1, true),
	('TAC-COLUMNA-LUMBAR', 'TAC DE COLUMNA LUMBAR', 'CDI', 'tomografia', 'Tomografia', 'Columna lumbar', false, true, 1, true),
	('TAC-COLUMNA-LUMBAR-CONTRASTADA', 'TAC DE COLUMNA LUMBAR CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Columna lumbar', true, true, 1, true),
	('TAC-CRANEO-VENTANA-OSEA', 'TAC DE CRANEO CON VENTANA OSEA', 'CDI', 'tomografia', 'Tomografia', 'Craneo', false, true, 1, true),
	('TAC-CRANEO-CONTRASTADA', 'TAC DE CRANEO CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Craneo', true, true, 1, true),
	('TAC-CRANEO-SIMPLE', 'TAC DE CRANEO SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Craneo', false, true, 1, true),
	('TAC-CUELLO-CON-CONTRASTE', 'TAC DE CUELLO CON CONTRASTE', 'CDI', 'tomografia', 'Tomografia', 'Cuello', true, true, 1, true),
	('TAC-CUELLO-SIMPLE', 'TAC DE CUELLO SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Cuello', false, true, 1, true),
	('TAC-FEMUR', 'TAC DE FEMUR', 'CDI', 'tomografia', 'Tomografia', 'Femur', false, true, 1, true),
	('TAC-FEMUR-CONTRASTADA', 'TAC DE FEMUR CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Femur', true, true, 1, true),
	('TAC-HOMBROS', 'TAC DE HOMBROS', 'CDI', 'tomografia', 'Tomografia', 'Hombros', false, true, 1, true),
	('TAC-HOMBROS-CONTRASTADA', 'TAC DE HOMBROS CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Hombros', true, true, 1, true),
	('TAC-MACIZO-FACIAL', 'TAC DE MACIZO FACIAL', 'CDI', 'tomografia', 'Tomografia', 'Macizo facial', false, true, 1, true),
	('TAC-MACIZO-FACIAL-CONTRASTADA', 'TAC DE MACIZO FACIAL CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Macizo facial', true, true, 1, true),
	('TAC-MASTOIDES', 'TAC DE MASTOIDES', 'CDI', 'tomografia', 'Tomografia', 'Mastoides', false, true, 1, true),
	('TAC-MIEMBROS-PELVICOS', 'TAC DE MIEMBROS PELVICOS', 'CDI', 'tomografia', 'Tomografia', 'Miembros pelvicos', false, true, 1, true),
	('TAC-MIEMBROS-PELVICOS-CONTRASTADA', 'TAC DE MIEMBROS PELVICOS CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Miembros pelvicos', true, true, 1, true),
	('TAC-OIDO', 'TAC DE OIDO', 'CDI', 'tomografia', 'Tomografia', 'Oido', false, true, 1, true),
	('TAC-OIDO-CONTRASTADA', 'TAC DE OIDO CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Oido', true, true, 1, true),
	('TAC-ORBITA', 'TAC DE ORBITA', 'CDI', 'tomografia', 'Tomografia', 'Orbita', false, true, 1, true),
	('TAC-ORBITA-CONTRASTADA', 'TAC DE ORBITA CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Orbita', true, true, 1, true),
	('TAC-PELVIS', 'TAC DE PELVIS', 'CDI', 'tomografia', 'Tomografia', 'Pelvis', false, true, 1, true),
	('TAC-PELVIS-CONTRASTADA', 'TAC DE PELVIS CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Pelvis', true, true, 1, true),
	('TAC-RODILLAS', 'TAC DE RODILLAS', 'CDI', 'tomografia', 'Tomografia', 'Rodillas', false, true, 1, true),
	('TAC-RODILLAS-CONTRASTADA', 'TAC DE RODILLAS CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Rodillas', true, true, 1, true),
	('TAC-SENOS-PARANASALES', 'TAC DE SENOS PARANASALES', 'CDI', 'tomografia', 'Tomografia', 'Senos paranasales', false, true, 1, true),
	('TAC-SENOS-PARANASALES-CONTRASTADA', 'TAC DE SENOS PARANASALES CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Senos paranasales', true, true, 1, true),
	('TAC-SILLA-TURCA', 'TAC DE SILLA TURCA', 'CDI', 'tomografia', 'Tomografia', 'Silla turca', false, true, 1, true),
	('TAC-TORAX-CONTRASTADA', 'TAC DE TORAX CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Torax', true, true, 1, true),
	('TAC-TORAX-SIMPLE', 'TAC DE TORAX SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Torax', false, true, 1, true),
	('TAC-TORACOABDOMINAL-CONTRASTADA', 'TAC TORACOABDOMINAL CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Toracoabdominal', true, true, 1, true),
	('TAC-TORACOABDOMINAL-SIMPLE', 'TAC TORACOABDOMINAL SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Toracoabdominal', false, true, 1, true),
	('TAC-TRIDIMENSIONAL-CUALQUIER-REGION', 'TAC TRIDIMENSIONAL CUALQUIER REGION', 'CDI', 'tomografia', 'Tomografia', 'Cualquier region', false, true, 1, true),
	('TAC-TRIFASICA', 'TAC TRIFASICA', 'CDI', 'tomografia', 'Tomografia', 'Trifasica', true, true, 1, true),
	('TAC-UROTOMOGRAFIA-CONTRASTADA', 'UROTOMOGRAFIA CONTRASTADA', 'CDI', 'tomografia', 'Tomografia', 'Sistema urinario', true, true, 1, true),
	('TAC-UROTOMOGRAFIA-SIMPLE', 'UROTOMOGRAFIA SIMPLE', 'CDI', 'tomografia', 'Tomografia', 'Sistema urinario', false, true, 1, true)
on conflict (clave) do update set
	descripcion = excluded.descripcion,
	empresa_operativa = excluded.empresa_operativa,
	modalidad = excluded.modalidad,
	area = excluded.area,
	region_anatomica = excluded.region_anatomica,
	requiere_contraste = excluded.requiere_contraste,
	requiere_interpretacion = excluded.requiere_interpretacion,
	dias_proceso = excluded.dias_proceso,
	activo = excluded.activo,
	updated_at = now();
