insert into public.estudios_imagen_catalogo (
	clave,
	descripcion,
	empresa_operativa,
	modalidad,
	area,
	region_anatomica,
	requiere_contraste,
	requiere_interpretacion,
	dias_proceso,
	activo
)
values
	('OT-AGUDEZA-VISUAL', 'AGUDEZA VISUAL', 'CDI', 'otro', 'Otros estudios', 'Visual', false, false, 1, true),
	('OT-AUDIOMETRIA', 'AUDIOMETRIA', 'CDI', 'otro', 'Otros estudios', 'Auditivo', false, false, 1, true),
	('OT-BIOPSIA-HIGADO-TRU-CUT-HISTOP', 'BIOPSIA DE HIGADO AGUJA TRU CUT con estudio histop', 'CDI', 'otro', 'Otros estudios', 'Higado', false, true, 1, true),
	('OT-BIOPSIA-MAMA-CON-ESTUDIO-PATOLOGICO', 'BIOPSIA DE MAMA CON ESTUDIO PATOLOGICO', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-BIOPSIA-MAMA-SIN-ESTUDIO-PATOLOGICO', 'BIOPSIA DE MAMA SIN ESTUDIO PATOLOGICO', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-BIOPSIA-TIROIDES-CON-EST-PATOLOGICO', 'BIOPSIA DE TIROIDES CON EST. PATOLOGICO', 'CDI', 'otro', 'Otros estudios', 'Tiroides', false, true, 1, true),
	('OT-BIOPSIA-MAMA-TRU-CUT-CON-HISTO', 'BIOPSIA MAMA AGUJA TRU CUT con estudio histo', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-BIOPSIA-MAMA-TRU-CUT-SIN-HISTOP', 'BIOPSIA MAMA AGUJA TRU CUT sin estudio histop', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-BIOPSIA-POR-TAC', 'BIOPSIA POR TAC', 'CDI', 'otro', 'Otros estudios', 'TAC', false, true, 1, true),
	('OT-BIOPSIA-PROSTATA-TRU-CUT-HISTOP', 'BIOPSIA PROSTATA AGUJA TRU CUT con estudio histop', 'CDI', 'otro', 'Otros estudios', 'Prostata', false, true, 1, true),
	('OT-CERTIFICADO-MEDICO', 'CERTIFICADO MEDICO', 'CDI', 'otro', 'Otros estudios', 'General', false, false, 1, true),
	('OT-COLONOSCOPIA', 'COLONOSCOPIA', 'CDI', 'otro', 'Otros estudios', 'Colon', false, true, 1, true),
	('OT-COLPOSCOPIA', 'COLPOSCOPIA', 'CDI', 'otro', 'Otros estudios', 'Ginecologia', false, true, 1, true),
	('OT-CONSULTA-CARDIOLOGO', 'CONSULTA CARDIOLOGO', 'CDI', 'otro', 'Otros estudios', 'Cardiologia', false, false, 1, true),
	('OT-CONSULTA-DR-CERVANTES', 'CONSULTA DR CERVANTES', 'CDI', 'otro', 'Otros estudios', 'Consulta', false, false, 1, true),
	('OT-DENSITOMETRIA-COLUMNA-CADERA', 'DENSITOMETRIA  DE COLUMNA Y CADERA', 'CDI', 'otro', 'Otros estudios', 'Columna y cadera', false, true, 1, true),
	('OT-DENSITOMETRIA-COMPLETA', 'DENSITOMETRIA COMPLETA', 'CDI', 'otro', 'Otros estudios', 'Densitometria', false, true, 1, true),
	('OT-ECOCARDIOGRAMA', 'ECOCARDIOGRAMA', 'CDI', 'otro', 'Otros estudios', 'Corazon', false, true, 1, true),
	('OT-ELECTROCARDIOGRAMA', 'ELECTROCARDIOGRAMA', 'CDI', 'otro', 'Otros estudios', 'Corazon', false, true, 1, true),
	('OT-ELECTROENCEFALOGRAMA', 'ELECTROENCEFALOGRAMA', 'CDI', 'otro', 'Otros estudios', 'Neurologia', false, true, 1, true),
	('OT-ELECTROENCEFALOGRAMA-CON-MAPEO', 'ELECTROENCEFALOGRAMA CON MAPEO', 'CDI', 'otro', 'Otros estudios', 'Neurologia', false, true, 1, true),
	('OT-ENDOSCOPIA', 'ENDOSCOPIA', 'CDI', 'otro', 'Otros estudios', 'Endoscopia', false, true, 1, true),
	('OT-ESPIROMETRIA', 'ESPIROMETRIA', 'CDI', 'otro', 'Otros estudios', 'Pulmonar', false, true, 1, true),
	('OT-ESPIROMETRIA-CXC-ODILE', 'ESPIROMETRIA (CXC ODILE)', 'CDI', 'otro', 'Otros estudios', 'Pulmonar', false, true, 1, true),
	('OT-ESPIROMETRIA-BD', 'ESPIROMETRIA BD', 'CDI', 'otro', 'Otros estudios', 'Pulmonar', false, true, 1, true),
	('OT-EXAMEN-CLINICO-MEDICO', 'EXAMEN CLINICO MEDICO', 'CDI', 'otro', 'Otros estudios', 'General', false, false, 1, true),
	('OT-HOLTER-CARDIOLOGO', 'HOLTER CARDIOLOGO', 'CDI', 'otro', 'Otros estudios', 'Cardiologia', false, true, 1, true),
	('OT-MAMOGRAFIA-DIGITAL-RASTREO-MAMARIO', 'MAMOGRAFIA DIGITAL / RASTREO MAMARIO', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-MAMOGRAFIA-DIGITAL-CON-ULTRASONIDO', 'MAMOGRAFIA DIGITAL CON ULTRASONIDO', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-MAPA', 'MAPA', 'CDI', 'otro', 'Otros estudios', 'Cardiologia', false, true, 1, true),
	('OT-PAQ-DENSITO-MASTOGRAFIA-RASTREO-MAMARIO', 'PAQ DENSITO, MASTOGRAFIA (RASTREO MAMARIO)', 'CDI', 'otro', 'Otros estudios', 'Mama', false, true, 1, true),
	('OT-PAQ-FEMENINO-CXC-ODILE', 'PAQ FEMENINO (CXC ODILE)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-MASCULINO-CXC-ODILE', 'PAQ MASCULINO (CXC ODILE)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-FEM-1-MAYORES-40', 'PAQ. BASICO FEM 1 ( APARTIR DE LOS 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-FEM-1-MENORES-40', 'PAQ. BASICO FEM 1 ( MENORES DE 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-FEM-2-MAYORES-40', 'PAQ. BASICO FEM 2 ( APARTIR DE LOS 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-FEM-2-MENORES-40', 'PAQ. BASICO FEM 2 ( MENORES DE 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-MAS-1-MAYORES-40', 'PAQ. BASICO MAS 1 ( APARTIR DE LOS 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PAQ-BASICO-MAS-2-MAYORES-40', 'PAQ. BASICO MAS 2 ( APARTIR DE LOS 40 ANOS)', 'CDI', 'otro', 'Otros estudios', 'Paquete', false, false, 1, true),
	('OT-PRUEBAS-ESFUERZO', 'PRUEBAS DE ESFUERZO', 'CDI', 'otro', 'Otros estudios', 'Cardiologia', false, true, 1, true)
on conflict (clave) do update set
	descripcion = excluded.descripcion,
	empresa_operativa = excluded.empresa_operativa,
	modalidad = excluded.modalidad,
	area = excluded.area,
	region_anatomica = excluded.region_anatomica,
	requiere_contraste = excluded.requiere_contraste,
	requiere_interpretacion = excluded.requiere_interpretacion,
	dias_proceso = excluded.dias_proceso,
	activo = excluded.activo,
	updated_at = now();
