-- Precios de laboratorio de particular, tomados de la lista de precios vigente.
-- La mayoría ya estaban capturados; esta siembra corrige los que quedaron con
-- otro importe, así que primero se borra lo que haya de esas claves para ese
-- cliente y se vuelve a insertar. Eso la deja re-ejecutable y de paso limpia
-- los renglones repetidos que traía la lista.

delete from public.precios_estudios
where cliente = 'Particular'
	and clave in (
		'17ALFA',
		'2ME',
		'A1TRIP',
		'AAC',
		'AACLA',
		'AACLG',
		'AACLM',
		'AAN18',
		'AAP',
		'ACC',
		'ACITR',
		'ACL',
		'ACLE',
		'ACLY',
		'ACM',
		'ACPG',
		'ACSA',
		'ACSMITH',
		'ACT',
		'ACTA',
		'ACTB',
		'ACTG',
		'ACTH',
		'ACTM',
		'ADA',
		'ADENO',
		'ADNA',
		'ADRE',
		'ADRO',
		'ADST',
		'ADT',
		'AELO1',
		'AFOL',
		'AFP',
		'AGCOVID',
		'AGG',
		'AGT',
		'AH',
		'ALB',
		'ALBO',
		'ALDO',
		'AMI',
		'AMIF',
		'AMON',
		'ANA',
		'ANCA',
		'ANFETA',
		'ANG',
		'APM',
		'APOA1',
		'APOB',
		'ARNA',
		'ARRTSH',
		'AT3',
		'AU',
		'AUO',
		'AVMO',
		'AcEBARR',
		'AcEBG',
		'AcEBM',
		'AcEBN',
		'AcHI',
		'AcHepC',
		'AcI',
		'AcMG',
		'AcMIT',
		'AcMYC',
		'AcRAC',
		'AcRM',
		'AcRO',
		'AcRUB',
		'AcSM',
		'AgEHB',
		'BAAR',
		'BAAR3',
		'BCRABL',
		'BD',
		'BENCE',
		'BETA2',
		'BHC',
		'BHYL',
		'BILIS',
		'BIOCH',
		'BIOESP',
		'BIOG',
		'BIOM',
		'BNP',
		'BT',
		'C1',
		'C3',
		'C4',
		'CA125',
		'CA153',
		'CA199',
		'CA27',
		'CA724',
		'CAIO',
		'CAL',
		'CALACT',
		'CALCI',
		'CARB',
		'CARBOX',
		'CARGA',
		'CARO',
		'CATE',
		'CATEO',
		'CAU',
		'CCP',
		'CD',
		'CEA',
		'CERU',
		'CEXP',
		'CFE',
		'CH50',
		'CHIGG',
		'CHIGM',
		'CI',
		'CICLO',
		'CISTATINA',
		'CITOC',
		'CITOLI',
		'CITOS',
		'CKMB',
		'CLAMY',
		'CLCR',
		'CLIQ',
		'CLOST',
		'CMV',
		'CMVM',
		'CNASA',
		'CNK',
		'CO',
		'COBSER',
		'COL',
		'COLHDL',
		'COLI',
		'COP1',
		'COP2',
		'COP3',
		'COPCUL',
		'COPROL',
		'COPROT',
		'CORT',
		'CORU',
		'CORVES',
		'CPK',
		'CRE',
		'CRIOA',
		'CRIOGLOB',
		'CRISTA',
		'CSEMEN',
		'CTG',
		'CUCH',
		'CULMYC',
		'CUMYC',
		'CUOFT',
		'CURE',
		'CURET',
		'CUSE',
		'CUURE',
		'CVAG',
		'CVAGCH',
		'CVAGUREA',
		'CVC',
		'CVIH',
		'CVIRAL',
		'Culcat',
		'DENG',
		'DEPU',
		'DHEA',
		'DHEAS',
		'DHL',
		'DHT',
		'DIGO',
		'DIM',
		'DNAN',
		'DOP3',
		'DOP6',
		'DOPA',
		'DXILO',
		'EGO',
		'ELECHB',
		'ELECLIP',
		'ELECPRO',
		'EOS',
		'ES3',
		'ES3OR',
		'ES6',
		'ESP',
		'EST',
		'ESTRO',
		'ETOT',
		'FAC',
		'FAC2',
		'FAC4',
		'FACI',
		'FAR',
		'FEB',
		'FENO',
		'FERR',
		'FIBRI',
		'FIX',
		'FOSFORO',
		'FR',
		'FRC',
		'FROTIS',
		'FRUC',
		'FSH',
		'FTA',
		'FVII',
		'FVIII',
		'FVW',
		'FX',
		'FXI',
		'FXII',
		'GAD65',
		'GALACT',
		'GASART',
		'GAST',
		'GASVEN',
		'GGT',
		'GLOB',
		'GLU',
		'GLUPOS',
		'GOTA',
		'GPO',
		'H1N1',
		'H2G',
		'H2M',
		'HAMU',
		'HAP',
		'HBA1C',
		'HBsAg',
		'HC',
		'HCG',
		'HEMO',
		'HIERRO',
		'HIV1Y2',
		'HIV4',
		'HLAB27',
		'HOMIR',
		'HOMO',
		'HPYH',
		'HSEX',
		'HepAIgG',
		'HepAIgM',
		'HepAT',
		'HerpG',
		'HerpM',
		'IGADIOMI',
		'IGF',
		'IGFBP',
		'IGGDIOMI',
		'IGGTRANS',
		'IGMGLIC',
		'IGS',
		'INH',
		'INHIS',
		'INPOS',
		'INS',
		'ISOCPK',
		'IgA',
		'IgD',
		'IgE',
		'IgG',
		'IgGGLIC',
		'IgGSUB',
		'IgM',
		'K',
		'LAC',
		'LAMO',
		'LE',
		'LH',
		'LINFOCD',
		'LIPA',
		'LIT',
		'MERC',
		'MET24',
		'METAN',
		'MG',
		'MG24',
		'MICRO',
		'MICRO24',
		'MOR',
		'MYCO',
		'NA',
		'NA24',
		'NDP',
		'OSULL',
		'OTI',
		'PAF',
		'PAM',
		'PANCA',
		'PAP',
		'PAPPCR',
		'PAQANTI',
		'PAQCENT',
		'PAQRAG',
		'PAQSEM',
		'PARVB19',
		'PBASICO',
		'PBM',
		'PBMAS1',
		'PBMAS2',
		'PCR',
		'PCRCOVID',
		'PCRUL',
		'PCT',
		'PDIAB',
		'PEPC',
		'PERANDR',
		'PESC',
		'PETS',
		'PFH',
		'PH',
		'PHMASC',
		'PIEO',
		'PIES',
		'PLG',
		'PLIP',
		'PLM',
		'PLO',
		'PLO24',
		'POT24',
		'POV5',
		'POV6',
		'PPD',
		'PPNAT',
		'PPRE',
		'PPREOP',
		'PREG',
		'PREOP',
		'PREUMA',
		'PROG',
		'PROL',
		'PROTC',
		'PROTS',
		'PSAE',
		'PSAF',
		'PSCOMP',
		'PSEG1',
		'PSELE',
		'PSTIR',
		'PTORINA',
		'PTOT',
		'PU',
		'PYIgA',
		'PYIgG',
		'PYIgM',
		'QS12',
		'QS24',
		'QS27',
		'QS3',
		'QS30',
		'QS35',
		'QS3ALT',
		'QS4',
		'QS4ALT',
		'QS6',
		'RALCR',
		'REDU',
		'RENI',
		'RETI',
		'RICKIgG',
		'RICKIgM',
		'ROSA',
		'ROTA',
		'RPN',
		'SERO',
		'SLC70',
		'SOH',
		'SSB',
		'SURG',
		'Se',
		'T3C',
		'T3L',
		'T3T',
		'T3U',
		'T4L',
		'T4T',
		'TAM',
		'TC',
		'TEO',
		'TESTO',
		'TGO',
		'TGP',
		'THC',
		'TIRO',
		'TIROG',
		'TOMDOM',
		'TORCHIII',
		'TOXG',
		'TOXM',
		'TOXO',
		'TP',
		'TRAC',
		'TRANS',
		'TRANSGLUM',
		'TRIG',
		'TRIP',
		'TROI',
		'TS',
		'TSH',
		'TT',
		'TTP',
		'TUBIgG',
		'TUBIgM',
		'URE',
		'UREAO',
		'URO',
		'URONEG',
		'VAG',
		'VALMG',
		'VALP',
		'VAM',
		'VAS',
		'VB12',
		'VDRL',
		'VITA',
		'VITB1',
		'VITB6',
		'VITC',
		'VITD25',
		'VITD3',
		'VITE',
		'VSG',
		'WBHIV2',
		'WBVIH1',
		'YODOB',
		'YODOP',
		'ZIKA',
		'ZINC',
		'aTPO',
		'cov19',
		'testlibre2'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', '17ALFA', '17 ALFA HIDROXIPROGESTERONA EN SUERO', 'Particular', 731.50, now()),
	('Estudio', '2ME', '2-MERCAPTO ETANOL', 'Particular', 1132.00, now()),
	('Estudio', 'A1TRIP', 'ALFA-1 ANTI TRIPSINA', 'Particular', 1215.00, now()),
	('Estudio', 'AAC', 'ANTICUERPOS ANTI-CENTROMERO', 'Particular', 891.00, now()),
	('Estudio', 'AACLA', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgA', 'Particular', 1093.50, now()),
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'Particular', 608.00, now()),
	('Estudio', 'AACLM', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgM', 'Particular', 702.00, now()),
	('Estudio', 'AAN18', 'INMUNOESPECIFICIDAD DE AAN 18 DETERM', 'Particular', 6075.00, now()),
	('Estudio', 'AAP', 'ANTICUERPOS ANTI-PLAQUETARIOS', 'Particular', 2673.00, now()),
	('Estudio', 'ACC', 'AC ANTI CISTICERCO EN LCR', 'Particular', 632.50, now()),
	('Estudio', 'ACITR', 'CITRATO EN ORINA DE 24 HORAS', 'Particular', 608.00, now()),
	('Estudio', 'ACL', 'ANTICOAGULANTE LUPICO', 'Particular', 1012.00, now()),
	('Estudio', 'ACLE', 'ANTICUERPOS ANTI-LEPTOSPIRA', 'Particular', 2430.00, now()),
	('Estudio', 'ACLY', 'ANTICUERPOS ANTI-BORRELIA BURGDORFERI IgG e IgM', 'Particular', 1998.00, now()),
	('Estudio', 'ACM', 'ANTICUERPOS ANTI-MUSCULO LISO', 'Particular', 632.50, now()),
	('Estudio', 'ACPG', 'ANTICUERPOS ANTI-PAROTIDITIS IgG', 'Particular', 1265.00, now()),
	('Estudio', 'ACSA', 'ANTICUERPOS ANTI-SARAMPION IgG', 'Particular', 759.00, now()),
	('Estudio', 'ACSMITH', 'AC. ANTI-SMITH', 'Particular', 677.60, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'Particular', 632.50, now()),
	('Estudio', 'ACTA', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgA', 'Particular', 764.50, now()),
	('Estudio', 'ACTB', 'ANTICUERPOS ANTI-TUBERCULOSIS', 'Particular', 955.90, now()),
	('Estudio', 'ACTG', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgG', 'Particular', 764.50, now()),
	('Estudio', 'ACTH', 'HORMONA ADRENOCORTICOTROFICA ACTH', 'Particular', 665.50, now()),
	('Estudio', 'ACTM', 'ANTICUERPOS ANTI-CHLAMYDIA TRACHOMATIS IgM', 'Particular', 764.50, now()),
	('Estudio', 'ADA', 'ADENOSIN DEAMINASA (ADA)', 'Particular', 2068.00, now()),
	('Estudio', 'ADENO', 'ADENOVIRUS', 'Particular', 1340.00, now()),
	('Estudio', 'ADNA', 'ANTICUERPOS ANTI-DNA DOBLE CADENA', 'Particular', 774.00, now()),
	('Estudio', 'ADRE', 'ADRENALINA EN PLASMA', 'Particular', 880.00, now()),
	('Estudio', 'ADRO', 'ADRENALINA EN ORINA DE 24 HORAS', 'Particular', 605.00, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'Particular', 1053.00, now()),
	('Estudio', 'ADT', 'ANDROSTENEDIONA', 'Particular', 544.50, now()),
	('Estudio', 'AELO1', 'ANTI-ESTREPTOLISINA "O"', 'Particular', 266.20, now()),
	('Estudio', 'AFOL', 'ACIDO FOLICO (FOLATOS)', 'Particular', 890.00, now()),
	('Estudio', 'AFP', 'ALFAFETOPROTEINAS', 'Particular', 392.00, now()),
	('Estudio', 'AGCOVID', 'PRUEBA DE ANTIGENO DE SARS-CoV-2 (COVID-19)', 'Particular', 495.00, now()),
	('Estudio', 'AGG', 'ANTIGENO GIARDIA LAMBLIA', 'Particular', 1330.00, now()),
	('Estudio', 'AGT', 'ACIDOS GRASOS TOTALES', 'Particular', 972.00, now()),
	('Estudio', 'AH', 'ANTICUERPOS HETEROFILOS (PAUL BUNNELL)', 'Particular', 513.00, now()),
	('Estudio', 'ALB', 'ALBUMINA SERICA', 'Particular', 154.00, now()),
	('Estudio', 'ALBO', 'ALBUMINA EN ORINA DE 24 HORAS', 'Particular', 110.00, now()),
	('Estudio', 'ALDO', 'ALDOLASA', 'Particular', 455.40, now()),
	('Estudio', 'AMI', 'AMILASA SERICA', 'Particular', 253.00, now()),
	('Estudio', 'AMIF', 'AMIBA EN FRESCO', 'Particular', 167.20, now()),
	('Estudio', 'AMON', 'AMONIO EN PLASMA', 'Particular', 418.00, now()),
	('Estudio', 'ANA', 'ANTICUERPOS ANTINUCLEARES', 'Particular', 700.00, now()),
	('Estudio', 'ANCA', 'ANTICUERPOS ANTI-CITOPLASMA C-ANCA', 'Particular', 1566.00, now()),
	('Estudio', 'ANFETA', 'ANFETAMINAS EN ORINA', 'Particular', 382.80, now()),
	('Estudio', 'ANG', 'ANGIOTENSINA', 'Particular', 1259.50, now()),
	('Estudio', 'APM', 'ANTICUERPOS ANTI-PAROTIDITIS IgM', 'Particular', 1265.00, now()),
	('Estudio', 'APOA1', 'APOLIPOPROTEINAS A-1', 'Particular', 1080.00, now()),
	('Estudio', 'APOB', 'APOLIPOPROTEINA B', 'Particular', 1080.00, now()),
	('Estudio', 'ARNA', 'ANTICUERPOS ANTI-RNA', 'Particular', 1149.50, now()),
	('Estudio', 'ARRTSH', 'ANTICUERPOS ANTI RECEPTORES DE TSH', 'Particular', 2090.00, now()),
	('Estudio', 'AT3', 'ANTITROMBINA III', 'Particular', 1204.50, now()),
	('Estudio', 'AU', 'ACIDO URICO', 'Particular', 154.00, now()),
	('Estudio', 'AUO', 'ACIDO URICO EN ORINA DE 24 HORAS', 'Particular', 231.00, now()),
	('Estudio', 'AVMO', 'ACIDO VANILMANDELICO EN ORINA DE  24 HORAS', 'Particular', 1080.00, now()),
	('Estudio', 'AcEBARR', 'AC.ANTI-EPSTEIN BARR Ag TEMPRANO IgG(EA)', 'Particular', 1452.00, now()),
	('Estudio', 'AcEBG', 'AC. ANTI-EPSTEIN BARR IgG (CAPSIDE)', 'Particular', 665.50, now()),
	('Estudio', 'AcEBM', 'AC. ANTI-EPSTEIN BARR IgM (CAPSIDE)', 'Particular', 665.50, now()),
	('Estudio', 'AcEBN', 'ANTICUERPOS ANTI-EPSTEIN BARR Ag NUCLEAR IgG (EBNA-IgG)', 'Particular', 1452.00, now()),
	('Estudio', 'AcHI', 'ANTICUERPOS ANTI-HISTOPLASMA', 'Particular', 1557.00, now()),
	('Estudio', 'AcHepC', 'ANTICUERPOS ANTI-HEPATITIS C (CUALITATIVO)', 'Particular', 489.50, now()),
	('Estudio', 'AcI', 'ANTICUERPOS ANTI-INSULINA', 'Particular', 865.70, now()),
	('Estudio', 'AcMG', 'ANTICUERPOS ANTI-MYCOPLASMA PNEUMONIAE IgM', 'Particular', 695.20, now()),
	('Estudio', 'AcMIT', 'ANTICUERPOS ANTI-MITOCONDRIALES', 'Particular', 632.50, now()),
	('Estudio', 'AcMYC', 'ANTICUERPOS ANTI-MYCOPLASMA PNEUMONIAE IgG', 'Particular', 695.20, now()),
	('Estudio', 'AcRAC', 'ANTICUERPOS RECEPTORES DE ACETILCOLINA', 'Particular', 2090.00, now()),
	('Estudio', 'AcRM', 'ANTICUERPOS ANTI-RUBEOLA IgM', 'Particular', 540.00, now()),
	('Estudio', 'AcRO', 'ANTICUERPOS ANTI-SSA Ro', 'Particular', 935.00, now()),
	('Estudio', 'AcRUB', 'ANTICUERPOS ANTI-RUBEOLA IgG', 'Particular', 540.00, now()),
	('Estudio', 'AcSM', 'ANTICUERPOS ANTI-SARAMPION IgM', 'Particular', 759.00, now()),
	('Estudio', 'AgEHB', 'ANTIGENO E DE HEPATITIS B', 'Particular', 702.00, now()),
	('Estudio', 'BAAR', 'BACILOSCOPIA DE 1 MUESTRA (BAAR)', 'Particular', 266.20, now()),
	('Estudio', 'BAAR3', 'BACILOSCOPIA DE 3 MUESTRAS (BAAR)', 'Particular', 671.00, now()),
	('Estudio', 'BCRABL', 'CROMOSOMA FILADELFIA ( BCR/ABL)', 'Particular', 8000.00, now()),
	('Estudio', 'BD', 'BILIRRUBINA DIRECTA', 'Particular', 154.00, now()),
	('Estudio', 'BENCE', 'PROTEINA DE BENCE JONES', 'Particular', 550.00, now()),
	('Estudio', 'BETA2', 'BETA 2 MICROGLOBULINA', 'Particular', 1013.00, now()),
	('Estudio', 'BHC', 'BIOMETRIA HEMATICA COMPLETA (BHC)', 'Particular', 165.00, now()),
	('Estudio', 'BHYL', 'BUSQUEDA RAPIDA DE HONGOS (KOH)', 'Particular', 202.00, now()),
	('Estudio', 'BILIS', 'BILIRRUBINAS', 'Particular', 310.20, now()),
	('Estudio', 'BIOCH', 'BIOPSIA CHICA', 'Particular', 1034.00, now()),
	('Estudio', 'BIOESP', 'BIOPSIA ESPECIAL (ORGANO, FETO, ETC)', 'Particular', 2425.00, now()),
	('Estudio', 'BIOG', 'BIOPSIA GRANDE', 'Particular', 1760.00, now()),
	('Estudio', 'BIOM', 'BIOPSIA MEDIANA', 'Particular', 1378.30, now()),
	('Estudio', 'BNP', 'PEPTIDO NATRIURETICO (BNP)', 'Particular', 2200.00, now()),
	('Estudio', 'BT', 'BILIRRUBINA TOTAL', 'Particular', 151.80, now()),
	('Estudio', 'C1', 'COMPLEMENTO C1', 'Particular', 1500.40, now()),
	('Estudio', 'C3', 'COMPLEMENTO C3', 'Particular', 506.00, now()),
	('Estudio', 'C4', 'COMPLEMENTO C4', 'Particular', 506.00, now()),
	('Estudio', 'CA125', 'AG. CARCINOMA OVARICO CA-125', 'Particular', 695.20, now()),
	('Estudio', 'CA153', 'AG. CARCINOMA DE MAMA CA 15-3', 'Particular', 726.00, now()),
	('Estudio', 'CA199', 'AG. CARCINOMA DE PANCREAS Y COLON CA 19-9', 'Particular', 726.00, now()),
	('Estudio', 'CA27', 'AG. CARCINOMA DE MAMA CA 27-29', 'Particular', 1600.50, now()),
	('Estudio', 'CA724', 'AG. CARCINOMA DE ESTOMAGO CA 72-4', 'Particular', 1210.00, now()),
	('Estudio', 'CAIO', 'CALCIO IOINIZADO', 'Particular', 726.00, now()),
	('Estudio', 'CAL', 'CALCIO SERICO', 'Particular', 183.70, now()),
	('Estudio', 'CALACT', 'CALPROTECTINA Y LACTOFERRINA HUMANA', 'Particular', 1342.00, now()),
	('Estudio', 'CALCI', 'CALCITONINA', 'Particular', 627.00, now()),
	('Estudio', 'CARB', 'CARBAMAZEPINA', 'Particular', 540.00, now()),
	('Estudio', 'CARBOX', 'CARBOXIHEMOGLOBINA', 'Particular', 1283.00, now()),
	('Estudio', 'CARGA', 'CARGA VIRAL HEPATITIS C (RNA-VCH)', 'Particular', 6765.00, now()),
	('Estudio', 'CARO', 'CAROTENOS', 'Particular', 759.00, now()),
	('Estudio', 'CATE', 'CATECOLAMINAS TOTALES', 'Particular', 1080.00, now()),
	('Estudio', 'CATEO', 'CATECOLAMINAS TOTALES EN ORINA 24 HRS', 'Particular', 770.00, now()),
	('Estudio', 'CAU', 'CALCIO EN ORINA DE 24 HORAS', 'Particular', 247.50, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'Particular', 1785.30, now()),
	('Estudio', 'CD', 'COOMBS DIRECTO', 'Particular', 303.60, now()),
	('Estudio', 'CEA', 'ANTIGENO CARCINOEMBRIONARIO', 'Particular', 443.30, now()),
	('Estudio', 'CERU', 'CERULOPLASMINA', 'Particular', 1080.00, now()),
	('Estudio', 'CEXP', 'CULTIVO DE EXPECTORACION', 'Particular', 600.60, now()),
	('Estudio', 'CFE', 'CINETICA DE HIERRO', 'Particular', 1413.50, now()),
	('Estudio', 'CH50', 'COMPLEMENTO HEMOLITICO CH50', 'Particular', 743.00, now()),
	('Estudio', 'CHIGG', 'Ac. ANTI CHIKUNGUNYA (IgG)', 'Particular', 725.00, now()),
	('Estudio', 'CHIGM', 'Ac. ANTI CHIKUNGUNYA (IgM)', 'Particular', 752.00, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'Particular', 322.30, now()),
	('Estudio', 'CICLO', 'CICLOSPORINA TOTAL', 'Particular', 1620.00, now()),
	('Estudio', 'CISTATINA', 'CISTATINA C', 'Particular', 946.00, now()),
	('Estudio', 'CITOC', 'CITOQUIMICO DE LIQUIDO CEFALORRAQUIDEO', 'Particular', 1282.60, now()),
	('Estudio', 'CITOLI', 'CITOLOGICO DE LIQUIDOS', 'Particular', 836.00, now()),
	('Estudio', 'CITOS', 'CITOQUIMICO DE LIQUIDO', 'Particular', 945.00, now()),
	('Estudio', 'CKMB', 'CREATIN-FOSFOQUINASA MB (CK-MB)', 'Particular', 330.00, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'Particular', 1900.00, now()),
	('Estudio', 'CLCR', 'CULTIVO DE LIQUIDO CEFALORRAQUIDEO', 'Particular', 957.00, now()),
	('Estudio', 'CLIQ', 'CULTIVO DE LIQUIDOS CORPORALES', 'Particular', 770.00, now()),
	('Estudio', 'CLOST', 'CLOSTRIDIUM DIFFICILE TOXINA A, TOXINA B, + GDH', 'Particular', 1804.00, now()),
	('Estudio', 'CMV', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgG', 'Particular', 621.00, now()),
	('Estudio', 'CMVM', 'ANTICUERPOS ANTI-CITOMEGALOVIRUS IgM', 'Particular', 621.00, now()),
	('Estudio', 'CNASA', 'CULTIVO DE EXUDADO NASAL', 'Particular', 572.00, now()),
	('Estudio', 'CNK', 'CELULAS NK', 'Particular', 1400.00, now()),
	('Estudio', 'CO', 'CULTIVO DE HONGOS (MYCOLOGICO)', 'Particular', 948.20, now()),
	('Estudio', 'COBSER', 'COBRE SERICO', 'Particular', 610.00, now()),
	('Estudio', 'COL', 'COLESTEROL', 'Particular', 154.00, now()),
	('Estudio', 'COLHDL', 'COLESTEROL HDL', 'Particular', 154.00, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'Particular', 556.60, now()),
	('Estudio', 'COP1', 'COPROPARASITOSCOPICO (1 MUESTRA)', 'Particular', 137.50, now()),
	('Estudio', 'COP2', 'COPROPARASITOSCOPICO (2 MUESTRAS)', 'Particular', 275.00, now()),
	('Estudio', 'COP3', 'COPROPARASITOSCOPICO (3 MUESTRAS)', 'Particular', 382.80, now()),
	('Estudio', 'COPCUL', 'COPROCULTIVO - CULTIVO DE HECES', 'Particular', 792.00, now()),
	('Estudio', 'COPROL', 'COPROLOGICO GENERAL', 'Particular', 275.00, now()),
	('Estudio', 'COPROT', 'COPROLOGICO CON ROTAVIRUS', 'Particular', 599.50, now()),
	('Estudio', 'CORT', 'CORTISOL SERICO', 'Particular', 365.20, now()),
	('Estudio', 'CORU', 'CORTISOL EN ORINA DE 24 HRS', 'Particular', 532.40, now()),
	('Estudio', 'CORVES', 'CORTISOL VESPERTINO', 'Particular', 365.00, now()),
	('Estudio', 'CPK', 'CREATIN-FOSFOQUINASA (CPK)', 'Particular', 275.00, now()),
	('Estudio', 'CRE', 'CREATININA', 'Particular', 154.00, now()),
	('Estudio', 'CRIOA', 'CRIOAGLUTININAS', 'Particular', 696.30, now()),
	('Estudio', 'CRIOGLOB', 'CRIOGLOBULINAS', 'Particular', 632.50, now()),
	('Estudio', 'CRISTA', 'CRISTALOGRAFIA', 'Particular', 556.60, now()),
	('Estudio', 'CSEMEN', 'CULTIVO DE SEMEN (ESPERMOCULTIVO)', 'Particular', 600.60, now()),
	('Estudio', 'CTG', 'CURVA DE TOLERANCIA A LA GLUCOSA 2 HORAS', 'Particular', 550.00, now()),
	('Estudio', 'CUCH', 'CULTIVO DE EXUADO URETRAL C/CHLAMYDIA', 'Particular', 820.00, now()),
	('Estudio', 'CULMYC', 'CULTIVO DE MYCOBACTERIUM TB.', 'Particular', 862.00, now()),
	('Estudio', 'CUMYC', 'CULTIVO URETRAL MYCOPLASMA', 'Particular', 1890.00, now()),
	('Estudio', 'CUOFT', 'CULTIVO OFTALMICO', 'Particular', 572.00, now()),
	('Estudio', 'CURE', 'CULTIVO DE UREAPLASMA', 'Particular', 1045.00, now()),
	('Estudio', 'CURET', 'CULTIVO URETRAL', 'Particular', 600.60, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'Particular', 572.00, now()),
	('Estudio', 'CUURE', 'CULTIVO URETRAL UREPLASMA', 'Particular', 1890.00, now()),
	('Estudio', 'CVAG', 'CULTIVO DE EXUDADO CERVICO VAGINAL', 'Particular', 572.00, now()),
	('Estudio', 'CVAGCH', 'CULTIVO DE EXUDADO CERVICO VAGINAL CON CHLAMYDIA', 'Particular', 840.00, now()),
	('Estudio', 'CVAGUREA', 'EXUDADO VAGINAL UREAPLASMA/MYCOPLASMA', 'Particular', 1890.00, now()),
	('Estudio', 'CVC', 'PCR CARGA VIRAL DE CITOMEGALOVIRUS (CMV)', 'Particular', 5428.50, now()),
	('Estudio', 'CVIH', 'CARGA VIRAL DE VIH-1', 'Particular', 6193.00, now()),
	('Estudio', 'CVIRAL', 'CARGA VIRAL DE HEPATITIS B', 'Particular', 5428.50, now()),
	('Estudio', 'Culcat', 'CULTIVO DE CATETER', 'Particular', 605.00, now()),
	('Estudio', 'DENG', 'DENGUE DUO', 'Particular', 572.00, now()),
	('Estudio', 'DEPU', 'DEPURACION DE CREATININA EN ORINA DE 24 HORAS', 'Particular', 361.90, now()),
	('Estudio', 'DHEA', 'DHEA DEHIDROEPIANDROSTERONA', 'Particular', 466.40, now()),
	('Estudio', 'DHEAS', 'DHEA-S DEHIDROEPIANDROSTERONA SULFATO', 'Particular', 531.30, now()),
	('Estudio', 'DHL', 'DESHIDROGENASA LACTICA DHL', 'Particular', 291.50, now()),
	('Estudio', 'DHT', 'DIHIDROTESTOSTERONA', 'Particular', 743.00, now()),
	('Estudio', 'DIGO', 'DIGOXINA', 'Particular', 608.00, now()),
	('Estudio', 'DIM', 'DIMERO D', 'Particular', 798.60, now()),
	('Estudio', 'DNAN', 'ANTICUERPOS ANTI-DNA', 'Particular', 1148.00, now()),
	('Estudio', 'DOP3', 'ANTIDOPING DE 3 PARAMETROS', 'Particular', 352.00, now()),
	('Estudio', 'DOP6', 'ANTIDOPING DE 6 PARAMETROS', 'Particular', 627.00, now()),
	('Estudio', 'DOPA', 'DOPAMINA EN PLASMA', 'Particular', 975.00, now()),
	('Estudio', 'DXILO', 'D´XILOSA', 'Particular', 1013.00, now()),
	('Estudio', 'EGO', 'EXAMEN GENERAL DE ORINA', 'Particular', 165.00, now()),
	('Estudio', 'ELECHB', 'ELECTROFORESIS ALCALINA DE HEMOGLOBINA', 'Particular', 2277.00, now()),
	('Estudio', 'ELECLIP', 'ELECTROFORESIS DE LIPOPROTEINAS', 'Particular', 786.50, now()),
	('Estudio', 'ELECPRO', 'ELECTROFORESIS DE PROTEINAS', 'Particular', 715.00, now()),
	('Estudio', 'EOS', 'EOSINOFILOS DE MOCO NASAL', 'Particular', 209.00, now()),
	('Estudio', 'ES3', 'ELECTROLITOS SERICOS DE 3 PARAMETROS', 'Particular', 412.50, now()),
	('Estudio', 'ES3OR', 'ELECTROLITOS EN ORINA 24 HRS DE 3 PARAMETROS (Na, K, Cl)', 'Particular', 412.50, now()),
	('Estudio', 'ES6', 'ELECTROLITOS SERICOS DE 6 PARAMETROS', 'Particular', 575.30, now()),
	('Estudio', 'ESP', 'ESPERMATOBIOSCOPIA', 'Particular', 462.00, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'Particular', 392.70, now()),
	('Estudio', 'ESTRO', 'ESTRONA (E1)', 'Particular', 605.00, now()),
	('Estudio', 'ETOT', 'ESTROGENOS TOTALES', 'Particular', 495.00, now()),
	('Estudio', 'FAC', 'FOSFATASA ALCALINA', 'Particular', 154.00, now()),
	('Estudio', 'FAC2', 'FACTOR II DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'FAC4', 'FACTOR V DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'FACI', 'FOSFATASA ACIDA TOTAL', 'Particular', 350.90, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'Particular', 572.00, now()),
	('Estudio', 'FEB', 'REACCIONES FEBRILES', 'Particular', 231.00, now()),
	('Estudio', 'FENO', 'FENOBARBITAL', 'Particular', 1053.00, now()),
	('Estudio', 'FERR', 'FERRITINA', 'Particular', 643.00, now()),
	('Estudio', 'FIBRI', 'FIBRINOGENO', 'Particular', 423.50, now()),
	('Estudio', 'FIX', 'FACTOR IX DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'FOSFORO', 'FOSFORO', 'Particular', 183.70, now()),
	('Estudio', 'FR', 'FACTOR REUMATOIDE (LATEX)', 'Particular', 253.00, now()),
	('Estudio', 'FRC', 'FACTOR REUMATOIDE CUANTITATIVO', 'Particular', 338.00, now()),
	('Estudio', 'FROTIS', 'FROTIS DE SANGRE PERIFERICA', 'Particular', 154.00, now()),
	('Estudio', 'FRUC', 'FRUCTOSA EN SEMEN CUANTITATIVA', 'Particular', 810.00, now()),
	('Estudio', 'FSH', 'HORMONA FOLICULO ESTIMULANTE', 'Particular', 392.70, now()),
	('Estudio', 'FTA', 'AC. ANTI-TREPONEMA PALLIDUM  (FTA-ABS)', 'Particular', 828.30, now()),
	('Estudio', 'FVII', 'FACTOR VII DE LA COAGULACION', 'Particular', 1053.00, now()),
	('Estudio', 'FVIII', 'FACTOR VIII DE LA COAGULACION', 'Particular', 1053.00, now()),
	('Estudio', 'FVW', 'FACTOR VON WILLWBRAND', 'Particular', 2025.00, now()),
	('Estudio', 'FX', 'FACTOR X DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'FXI', 'FACTOR XI DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'FXII', 'FACTOR XII DE LA COAGULACIÓN', 'Particular', 1053.00, now()),
	('Estudio', 'GAD65', 'AC. ANTI GLUTAMATO-DECARBOXILASA(ANTI GAD-65)', 'Particular', 2025.00, now()),
	('Estudio', 'GALACT', 'GALACTOMANANO', 'Particular', 2268.00, now()),
	('Estudio', 'GASART', 'GASOMETRIA ARTERIAL', 'Particular', 1500.00, now()),
	('Estudio', 'GAST', 'GASTRINA', 'Particular', 959.00, now()),
	('Estudio', 'GASVEN', 'GASOMETRIA VENOSA', 'Particular', 1500.00, now()),
	('Estudio', 'GGT', 'GAMA GLUTAMIL TRANSPEPTIDASA (GGT)', 'Particular', 154.00, now()),
	('Estudio', 'GLOB', 'GLOBULINA', 'Particular', 300.00, now()),
	('Estudio', 'GLU', 'GLUCOSA', 'Particular', 154.00, now()),
	('Estudio', 'GLUPOS', 'GLUCOSA PRE Y POST PRANDIAL (2HRS)', 'Particular', 487.30, now()),
	('Estudio', 'GOTA', 'GOTA GRUESA (PLASMODIUM)', 'Particular', 253.00, now()),
	('Estudio', 'GPO', 'GRUPO SANGUINEO', 'Particular', 157.30, now()),
	('Estudio', 'H1N1', 'PRUEBA PARA ANTIGENO DE LA INFLUENZA A, B, H1N1', 'Particular', 814.00, now()),
	('Estudio', 'H2G', 'ANTICUERPOS ANTI-HERPES II IgG', 'Particular', 511.00, now()),
	('Estudio', 'H2M', 'ANTICUERPOS ANTI-HERPES II IgM', 'Particular', 500.00, now()),
	('Estudio', 'HAMU', 'HORMONA ANTIMULLERIANA', 'Particular', 3454.00, now()),
	('Estudio', 'HAP', 'HAPTOGLOBINAS', 'Particular', 743.00, now()),
	('Estudio', 'HBA1C', 'HEMOGLOBINA GLICOSILADA (HbA1c)', 'Particular', 412.50, now()),
	('Estudio', 'HBsAg', 'ANTIGENO DE SUPERFICIE PARA HEPATITIS B (CUALITATIVO)', 'Particular', 489.50, now()),
	('Estudio', 'HC', 'HORMONA DE CRECIMIENTO', 'Particular', 619.30, now()),
	('Estudio', 'HCG', 'CUANTIFICACION DE FRAC. BETA GONADOTROPINA CORIONICA HUMANA (B-HCG)', 'Particular', 385.00, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'Particular', 1215.00, now()),
	('Estudio', 'HIERRO', 'HIERRO SERICO', 'Particular', 367.40, now()),
	('Estudio', 'HIV1Y2', 'AC. ANTI HIV 1 Y HIV 2', 'Particular', 418.00, now()),
	('Estudio', 'HIV4', 'HIV 4TA GENERACIÓN', 'Particular', 540.00, now()),
	('Estudio', 'HLAB27', 'ANTIGENO HLA-B27', 'Particular', 1853.50, now()),
	('Estudio', 'HOMIR', 'INDICE DE RESISTENCIA A LA INSULINA (HOMA-IR)', 'Particular', 500.00, now()),
	('Estudio', 'HOMO', 'HOMOCISTEINA', 'Particular', 1168.20, now()),
	('Estudio', 'HPYH', 'ANTIGENO DE HELICOBACTER PYLORI EN HECES', 'Particular', 957.00, now()),
	('Estudio', 'HSEX', 'GLOBULINA FIJADORA DE HORMONAS SEXUALES', 'Particular', 1340.00, now()),
	('Estudio', 'HepAIgG', 'ANTICUERPOS ANTI-HEPATITIS A IgG', 'Particular', 675.00, now()),
	('Estudio', 'HepAIgM', 'ANTICUERPOS ANTI-HEPATITIS A IgM', 'Particular', 675.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'Particular', 1148.00, now()),
	('Estudio', 'HerpG', 'ANTICUERPOS ANTI-HERPES I IgG', 'Particular', 569.00, now()),
	('Estudio', 'HerpM', 'ANTICUERPOS ANTI-HERPES I IgM', 'Particular', 569.00, now()),
	('Estudio', 'IGADIOMI', 'ANTICUERPOS IgA ANTI-ENDOMISIO', 'Particular', 2050.00, now()),
	('Estudio', 'IGF', 'SOMATOMEDINA C (IGF-1)', 'Particular', 968.00, now()),
	('Estudio', 'IGFBP', 'FACTOR HUMANO DE CRECIMIENTO SIMILAR A LA INSULINA(IGFBP-3)', 'Particular', 1445.00, now()),
	('Estudio', 'IGGDIOMI', 'ANTICUERPOS IgG ANTI-ENDOMISIO', 'Particular', 4400.00, now()),
	('Estudio', 'IGGTRANS', 'Ac. ANTI-TRANSGLUTAMINASA (IgG)', 'Particular', 2180.00, now()),
	('Estudio', 'IGMGLIC', 'BETA 2 GLICOPROTEINA IgM', 'Particular', 1138.50, now()),
	('Estudio', 'IGS', 'INMUNOGLOBULINAS "A", "G","M" Y "E"', 'Particular', 1013.00, now()),
	('Estudio', 'INH', 'INHIBINA A', 'Particular', 2835.00, now()),
	('Estudio', 'INHIS', 'INMUNOHISTOQUIMICA', 'Particular', 6500.00, now()),
	('Estudio', 'INPOS', 'INSULINA POST PANDRIAL', 'Particular', 770.00, now()),
	('Estudio', 'INS', 'INSULINA SERICA', 'Particular', 423.50, now()),
	('Estudio', 'ISOCPK', 'ISOENZIMAS DE CPK', 'Particular', 1380.00, now()),
	('Estudio', 'IgA', 'INMUNOGLOBULINA A IgA', 'Particular', 486.20, now()),
	('Estudio', 'IgD', 'INMUNOGLOBULINA D IgD', 'Particular', 486.20, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'Particular', 486.20, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'Particular', 486.20, now()),
	('Estudio', 'IgGGLIC', 'BETA 2 GLICOPROTEINA IgG', 'Particular', 1138.50, now()),
	('Estudio', 'IgGSUB', 'INMUNOGLOBULINA G SUBCLASES IgG 1,2,3,4', 'Particular', 2451.00, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'Particular', 486.20, now()),
	('Estudio', 'K', 'POTASIO', 'Particular', 412.50, now()),
	('Estudio', 'LAC', 'ACIDO LACTICO', 'Particular', 440.00, now()),
	('Estudio', 'LAMO', 'LAMOTRIGINA', 'Particular', 2430.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'Particular', 347.60, now()),
	('Estudio', 'LH', 'HORMONA LUTEINIZANTE', 'Particular', 392.70, now()),
	('Estudio', 'LINFOCD', 'LINFOCITOS CD4/CD8', 'Particular', 5445.00, now()),
	('Estudio', 'LIPA', 'LIPASA', 'Particular', 253.00, now()),
	('Estudio', 'LIT', 'LITIO', 'Particular', 466.40, now()),
	('Estudio', 'MERC', 'MERCURIO EN SANGRE', 'Particular', 1413.50, now()),
	('Estudio', 'MET24', 'METANEFRINAS TOTALES EN ORINA DE 24 HORAS', 'Particular', 1485.00, now()),
	('Estudio', 'METAN', 'METANEFRINAS EN PLASMA', 'Particular', 2025.00, now()),
	('Estudio', 'MG', 'MAGNESIO SERICO', 'Particular', 183.70, now()),
	('Estudio', 'MG24', 'MAGNESIO EN ORINA DE 24 HORAS', 'Particular', 270.00, now()),
	('Estudio', 'MICRO', 'MICROALBUMINA EN ORINA DE UNA SOLA MICCION', 'Particular', 473.00, now()),
	('Estudio', 'MICRO24', 'MICROALBUMINA EN ORINA DE 24 HORAS', 'Particular', 608.00, now()),
	('Estudio', 'MOR', 'MORFINA EN ORINA', 'Particular', 473.00, now()),
	('Estudio', 'MYCO', 'MYCOBACTERIUM TUBERCULOSIS POR PCR', 'Particular', 7560.00, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'Particular', 412.50, now()),
	('Estudio', 'NA24', 'SODIO EN ORINA DE 24 HORAS', 'Particular', 316.80, now()),
	('Estudio', 'NDP', 'NORADRENALINA EN PLASMA', 'Particular', 945.00, now()),
	('Estudio', 'OSULL', 'PRUEBA O''SULLIVAN', 'Particular', 550.00, now()),
	('Estudio', 'OTI', 'CULTIVO OTICO', 'Particular', 572.00, now()),
	('Paquete', 'PAF', 'PAQUETE ARIES FEMENINO (INCLUYE: TORAX AP, COLUMNA 2 POSICIONES, MASTO, USG MAMARIO, EKG)', 'Particular', 7604.52, now()),
	('Paquete', 'PAM', 'PAQUETE ARIES MASCULINO (INCLUYE: TORAX AP, COLUMNA 2 POSICIONES, USG PROSTATICO,EKG)', 'Particular', 6818.62, now()),
	('Estudio', 'PANCA', 'ANTICUERPOS ANTI-CITOPLASMA P-ANCA', 'Particular', 1566.00, now()),
	('Estudio', 'PAP', 'PAPANICOLAOU', 'Particular', 440.00, now()),
	('Estudio', 'PAPPCR', 'VIRUS DEL PAPILOMA HUMANO POR PCR', 'Particular', 3025.00, now()),
	('Paquete', 'PAQANTI', 'PAQUETE ANTIDOPING + CERTIFICADO MEDICO', 'Particular', 1327.00, now()),
	('Paquete', 'PAQCENT', 'PAQUETE HOMBRE CENTAURO', 'Particular', 1856.00, now()),
	('Paquete', 'PAQRAG', 'PAQUETE RAGASA', 'Particular', 1220.00, now()),
	('Paquete', 'PAQSEM', 'PAQUETE SEMEBA', 'Particular', 3784.00, now()),
	('Estudio', 'PARVB19', 'PARVOVIRUS B19', 'Particular', 4050.00, now()),
	('Paquete', 'PBASICO', 'PERFIL BASICO', 'Particular', 1210.00, now()),
	('Paquete', 'PBM', 'Perfil Básico Masculino (solo lab)', 'Particular', 1280.40, now()),
	('Paquete', 'PBMAS1', 'PAQUETE BASICO MASCULINO 1 **INCLUYE: RX TORAX, USG PROSTATICO', 'Particular', 1500.00, now()),
	('Paquete', 'PBMAS2', 'PAQUETE BASICO MASCULINO 2, INCLUYE: EKG, USG PROSTATICO, RX TORAX', 'Particular', 3000.00, now()),
	('Estudio', 'PCR', 'PROTEINA "C" REACTIVA (LATEX)', 'Particular', 266.20, now()),
	('Estudio', 'PCRCOVID', 'TEST PCR DE SARS-CoV-2 (COVID-19)', 'Particular', 1800.00, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'Particular', 440.00, now()),
	('Estudio', 'PCT', 'PROCALCITONINA', 'Particular', 759.00, now()),
	('Paquete', 'PDIAB', 'PERFIL DIABETICO', 'Particular', 990.00, now()),
	('Estudio', 'PEPC', 'PEPTIDO C', 'Particular', 832.70, now()),
	('Estudio', 'PERANDR', 'PERFIL ANDROGENICO', 'Particular', 1755.00, now()),
	('Paquete', 'PESC', 'PAQUETE ESCOLAR', 'Particular', 600.00, now()),
	('Paquete', 'PETS', 'PERFIL ETS', 'Particular', 1485.00, now()),
	('Estudio', 'PFH', 'PRUEBAS DE FUNCIONAMIENTO HEPATICO', 'Particular', 792.00, now()),
	('Estudio', 'PH', 'PARATHORMONA (MOLECULA INTACTA)', 'Particular', 5730.00, now()),
	('Estudio', 'PHMASC', 'PERFIL HORMONAL MASCULINO', 'Particular', 1850.00, now()),
	('Estudio', 'PIEO', 'PRUEBA DE EMBARAZO EN ORINA', 'Particular', 231.00, now()),
	('Estudio', 'PIES', 'PRUEBA DE EMBARAZO EN SANGRE', 'Particular', 231.00, now()),
	('Estudio', 'PLG', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgG', 'Particular', 695.20, now()),
	('Estudio', 'PLIP', 'PERFIL DE LIPIDOS', 'Particular', 500.50, now()),
	('Estudio', 'PLM', 'ANTICUERPOS ANTI-FOSFOLIPIDOS IgM', 'Particular', 695.20, now()),
	('Estudio', 'PLO', 'PLOMO EN SANGRE', 'Particular', 900.00, now()),
	('Estudio', 'PLO24', 'PLOMO EN ORINA DE 24 HORAS', 'Particular', 907.50, now()),
	('Estudio', 'POT24', 'POTASIO EN ORINA DE 24 HORAS', 'Particular', 411.40, now()),
	('Estudio', 'POV5', 'PERFIL OVARICO 5', 'Particular', 1864.50, now()),
	('Estudio', 'POV6', 'PERFIL OVARICO 6', 'Particular', 2212.10, now()),
	('Estudio', 'PPD', 'PRUEBA CUTANEA DE TUBERCULINA', 'Particular', 2400.00, now()),
	('Paquete', 'PPNAT', 'PERFIL PRENATAL', 'Particular', 1375.00, now()),
	('Paquete', 'PPRE', 'PERFIL PRENUPCIAL', 'Particular', 330.00, now()),
	('Paquete', 'PPREOP', 'PAQUETE PREOPERATORIO, INCLUYE: EKG, RX TORAX', 'Particular', 2035.00, now()),
	('Estudio', 'PREG', 'PREGNENOLONA', 'Particular', 4257.00, now()),
	('Paquete', 'PREOP', 'PERFIL PREOPERATORIO (solo lab)', 'Particular', 1147.30, now()),
	('Paquete', 'PREUMA', 'PERFIL REUMATOLOGICO', 'Particular', 1037.30, now()),
	('Estudio', 'PROG', 'PROGESTERONA', 'Particular', 392.70, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'Particular', 392.70, now()),
	('Estudio', 'PROTC', 'PROTEINA "C" DE LA COAGULACION', 'Particular', 2277.00, now()),
	('Estudio', 'PROTS', 'PROTEINA "S" DE LA COAGULACION', 'Particular', 2541.00, now()),
	('Estudio', 'PSAE', 'ANTIGENO PROSTATICO ESPECIFICO (PSA)', 'Particular', 412.50, now()),
	('Estudio', 'PSAF', 'ANTIGENO PROSTATICO LIBRE', 'Particular', 435.60, now()),
	('Paquete', 'PSCOMP', 'PERFIL SMAC/COMPLETO', 'Particular', 3630.00, now()),
	('Paquete', 'PSEG1', 'PAQUETE SEG 1', 'Particular', 1995.78, now()),
	('Paquete', 'PSELE', 'PERFIL SMAC/ELECTROLITOS', 'Particular', 1650.00, now()),
	('Paquete', 'PSTIR', 'PERFIL SMAC/TIROIDEO', 'Particular', 3168.00, now()),
	('Estudio', 'PTORINA', 'PROTEINAS EN ORINA DE 24 HRS', 'Particular', 392.70, now()),
	('Estudio', 'PTOT', 'PROTEINAS TOTALES SERICAS', 'Particular', 198.00, now()),
	('Estudio', 'PU', 'FOSFORO EN ORINA DE 24 HRS', 'Particular', 316.80, now()),
	('Estudio', 'PYIgA', 'ANTICUERPOS HELICOBACTER PYLORI IgA', 'Particular', 715.00, now()),
	('Estudio', 'PYIgG', 'ANTICUERPOS HELICOBACTER PYLORI IgG', 'Particular', 715.00, now()),
	('Estudio', 'PYIgM', 'ANTICUERPOS HELICOBACTER PYLORI IgM', 'Particular', 715.00, now()),
	('Estudio', 'QS12', 'QUIMICA SANGUINEA DE 12 ELEMENTOS', 'Particular', 986.70, now()),
	('Estudio', 'QS24', 'QUIMICA SANGUINEA DE 24 ELEMENTOS', 'Particular', 1639.00, now()),
	('Estudio', 'QS27', 'QUIMICA SANGUINEA DE 27 ELEMENTOS', 'Particular', 2055.90, now()),
	('Estudio', 'QS3', 'QUIMICA SANGUINEA DE 3 ELEMENTOS', 'Particular', 379.50, now()),
	('Estudio', 'QS30', 'QUIMICA SANGUINEA DE 30 ELEMENTOS', 'Particular', 2400.00, now()),
	('Estudio', 'QS35', 'QUIMICA SANGUINEA DE 35 ELEMENTOS', 'Particular', 4000.00, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'Particular', 379.50, now()),
	('Estudio', 'QS4', 'QUIMICA  SANGUINEA DE 4 ELEMENTOS', 'Particular', 533.50, now()),
	('Estudio', 'QS4ALT', 'QUIMICA SANGUINEA DE 4 ELEMENTOS (COL, TRIG)', 'Particular', 533.50, now()),
	('Estudio', 'QS6', 'QUIMICA SANGUINEA DE 6 ELEMENTOS', 'Particular', 605.00, now()),
	('Estudio', 'RALCR', 'RELACION ALBUMINA/CREATININA', 'Particular', 275.00, now()),
	('Estudio', 'REDU', 'AZUCARES REDUCTORES EN HECES', 'Particular', 167.20, now()),
	('Estudio', 'RENI', 'RENINA EN PLASMA', 'Particular', 715.00, now()),
	('Estudio', 'RETI', 'RETICULOCITOS', 'Particular', 165.00, now()),
	('Estudio', 'RICKIgG', 'ANTICUERPOS ANTI-RICKETTSIA IgG', 'Particular', 2133.00, now()),
	('Estudio', 'RICKIgM', 'ANTICUERPOS ANTI-RICKETTSIA IgM', 'Particular', 2133.00, now()),
	('Estudio', 'ROSA', 'ROSA DE BENGALA', 'Particular', 572.00, now()),
	('Estudio', 'ROTA', 'ROTAVIRUS', 'Particular', 667.00, now()),
	('Estudio', 'RPN', 'ANTICUERPOS ANTI-RNP', 'Particular', 945.00, now()),
	('Estudio', 'SERO', 'SEROTONINA', 'Particular', 1276.00, now()),
	('Estudio', 'SLC70', 'ANTICUERPOS ANTI-SCL-70', 'Particular', 945.00, now()),
	('Estudio', 'SOH', 'SANGRE OCULTA EN HECES', 'Particular', 154.00, now()),
	('Estudio', 'SSB', 'ANTICUERPOS ANTI-SSB La', 'Particular', 764.50, now()),
	('Estudio', 'SURG', 'SERVICIO DE URGENCIA', 'Particular', 495.00, now()),
	('Estudio', 'Se', 'SELENIO', 'Particular', 1650.00, now()),
	('Estudio', 'T3C', 'T3 CAPTACION', 'Particular', 392.70, now()),
	('Estudio', 'T3L', 'TRIYODOTIRONINA LIBRE (T3 libre)', 'Particular', 392.70, now()),
	('Estudio', 'T3T', 'TRIYODOTIRONINA (T3 total)', 'Particular', 392.70, now()),
	('Estudio', 'T3U', 'T3 UPTAKE', 'Particular', 170.00, now()),
	('Estudio', 'T4L', 'TIROXINA LIBRE (T4 libre)', 'Particular', 392.70, now()),
	('Estudio', 'T4T', 'TIROXINA (T4 total)', 'Particular', 392.70, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'Particular', 1424.50, now()),
	('Estudio', 'TC', 'TIEMPO DE COAGULACION', 'Particular', 154.00, now()),
	('Estudio', 'TEO', 'AMINOFILINA(TEOFILINA)', 'Particular', 783.00, now()),
	('Estudio', 'TESTO', 'TESTOSTERONA TOTAL', 'Particular', 435.60, now()),
	('Estudio', 'TGO', 'TRANSAMINASA GLUTAMICO OXALOACETICA (TGO)', 'Particular', 209.00, now()),
	('Estudio', 'TGP', 'TRANSAMINASA GLUTAMICO PIRUVICA (TGP)', 'Particular', 209.00, now()),
	('Estudio', 'THC', 'CANNABINOIDES MARIHUANA', 'Particular', 162.00, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'Particular', 1210.00, now()),
	('Estudio', 'TIROG', 'TIROGLOBULINA', 'Particular', 466.40, now()),
	('Estudio', 'TOMDOM', 'SERVICIO A DOMICILIO', 'Particular', 495.00, now()),
	('Estudio', 'TORCHIII', 'PERFIL DE TORCH III IgM E IgG CUANTITATIVO', 'Particular', 3020.00, now()),
	('Estudio', 'TOXG', 'ANTICUERPOS ANTI-TOXOPLASMA GONDII IgG', 'Particular', 608.00, now()),
	('Estudio', 'TOXM', 'ANTICUERPOS ANTI-TOXOPLASMA GONDII IgM', 'Particular', 534.00, now()),
	('Estudio', 'TOXO', 'ANTICUERPOS ANTI-TOXOCARA', 'Particular', 1215.00, now()),
	('Estudio', 'TP', 'TIEMPO DE PROTROMBINA TP', 'Particular', 253.00, now()),
	('Estudio', 'TRAC', 'TACROLIMUS', 'Particular', 1265.00, now()),
	('Estudio', 'TRANS', 'TRANSFERRINA', 'Particular', 385.00, now()),
	('Estudio', 'TRANSGLUM', 'AC. ANTI TRANSGLUTAMINASA (IgA)', 'Particular', 2750.00, now()),
	('Estudio', 'TRIG', 'TRIGLICERIDOS', 'Particular', 154.00, now()),
	('Estudio', 'TRIP', 'ANTICUERPOS ANTI-TRIPANOSOMA (CHAGAS)', 'Particular', 762.30, now()),
	('Estudio', 'TROI', 'TROPONINA I', 'Particular', 2200.00, now()),
	('Estudio', 'TS', 'TIEMPO DE SANGRADO', 'Particular', 154.00, now()),
	('Estudio', 'TSH', 'HORMONA ESTIMULANTE DE LA TIROIDES', 'Particular', 392.70, now()),
	('Estudio', 'TT', 'TIEMPO DE TROMBINA', 'Particular', 110.00, now()),
	('Estudio', 'TTP', 'TIEMPO DE TROMBOPLASTINA PARCIAL TTP', 'Particular', 253.00, now()),
	('Estudio', 'TUBIgG', 'AC. ANTI MYCOBACTERIUM TUBERCULOSIS (IgG)', 'Particular', 940.00, now()),
	('Estudio', 'TUBIgM', 'AC ANTI MYCOBACTERIUM TUBERCULOSIS IgM', 'Particular', 713.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'Particular', 154.00, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'Particular', 300.00, now()),
	('Estudio', 'URO', 'UROCULTIVO', 'Particular', 572.00, now()),
	('Estudio', 'URONEG', 'UROCULTIVO NEGATIVO', 'Particular', 539.00, now()),
	('Estudio', 'VAG', 'ANTICUERPOS ANTI-VARICELA IgG', 'Particular', 945.00, now()),
	('Estudio', 'VALMG', 'VALPROATO DE MAGNESIO', 'Particular', 495.00, now()),
	('Estudio', 'VALP', 'ACIDO VALPROICO', 'Particular', 500.50, now()),
	('Estudio', 'VAM', 'ANTICUERPOS ANTI-VARICELA IgM', 'Particular', 945.00, now()),
	('Estudio', 'VAS', 'HORMONA ANTIDIURETICA (VASOPRESINA)', 'Particular', 715.00, now()),
	('Estudio', 'VB12', 'VITAMINA B12', 'Particular', 764.50, now()),
	('Estudio', 'VDRL', 'VDRL', 'Particular', 165.00, now()),
	('Estudio', 'VITA', 'VITAMINA "A"', 'Particular', 2594.00, now()),
	('Estudio', 'VITB1', 'TIAMINA (VITAMINA B1)', 'Particular', 3382.00, now()),
	('Estudio', 'VITB6', 'VITAMINA B6', 'Particular', 3348.00, now()),
	('Estudio', 'VITC', 'VITAMINA C', 'Particular', 2659.00, now()),
	('Estudio', 'VITD25', 'VITAMINA D 25-OH', 'Particular', 850.00, now()),
	('Estudio', 'VITD3', 'VITAMINA D3', 'Particular', 2570.00, now()),
	('Estudio', 'VITE', 'VITAMINA E', 'Particular', 1539.00, now()),
	('Estudio', 'VSG', 'VELOCIDAD DE SEDIMENTACION GLOBULAR VSG', 'Particular', 143.00, now()),
	('Estudio', 'WBHIV2', 'WESTERN BLOT VIH 2', 'Particular', 6637.40, now()),
	('Estudio', 'WBVIH1', 'WESTERN BLOT VIH 1', 'Particular', 3537.00, now()),
	('Estudio', 'YODOB', 'YODO BUTANOLICO', 'Particular', 302.50, now()),
	('Estudio', 'YODOP', 'YODO PROTEICO', 'Particular', 302.50, now()),
	('Estudio', 'ZIKA', 'ANTICUERPOS VIRUS DE ZIKA', 'Particular', 4209.00, now()),
	('Estudio', 'ZINC', 'ZINC', 'Particular', 979.00, now()),
	('Estudio', 'aTPO', 'AC. ANTI PEROXIDASA  TIROIDEA (a-TPO)', 'Particular', 632.50, now()),
	('Estudio', 'cov19', 'ANTICUERPOS SARS-CoV-2 (COVID-19) IgM e IgG', 'Particular', 810.00, now()),
	('Estudio', 'testlibre2', 'TESTOSTERONA LIBRE', 'Particular', 544.50, now());

NOTIFY pgrst, 'reload schema';
