insert into public.estudios_imagen_catalogo (
	clave,
	descripcion,
	empresa_operativa,
	modalidad,
	area,
	region_anatomica,
	requiere_contraste,
	requiere_interpretacion,
	dias_proceso,
	activo
)
values
	('RM-ANGIO-CONTRASTADA-CUALQUIER-REGION', 'ANGIO-RESONANCIA CONTRASTADA DE CUALQUIER REGION', 'CDC', 'resonancia', 'Resonancia magnetica', 'Cualquier region', true, true, 1, true),
	('RM-ANGIO-SIMPLE-CUALQUIER-REGION', 'ANGIO-RESONANCIA SIMPLE DE CUALQUIER REGION', 'CDC', 'resonancia', 'Resonancia magnetica', 'Cualquier region', false, true, 1, true),
	('RM-COLANGIO-RESONANCIA', 'COLANGIO-RESONANCIA', 'CDC', 'resonancia', 'Via biliar', 'Via biliar', false, true, 1, true),
	('RM-ABDOMEN-CONTRASTADA', 'RM ABDOMEN CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Abdomen', true, true, 1, true),
	('RM-ABDOMEN-SIMPLE', 'RM ABDOMEN SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Abdomen', false, true, 1, true),
	('RM-ARTICULACION-MANDIBULAR', 'RM ARTICULACION MANDIBULAR', 'CDC', 'resonancia', 'Resonancia magnetica', 'Articulacion mandibular', false, true, 1, true),
	('RM-CODO-SIMPLE', 'RM CODO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Codo', false, true, 1, true),
	('RM-COLUMNA-2-REGIONES', 'RM COLUMNA 2 REGIONES', 'CDC', 'resonancia', 'Columna', 'Columna 2 regiones', false, true, 1, true),
	('RM-COLUMNA-2-REGIONES-CONTRASTADA', 'RM COLUMNA 2 REGIONES CONTRASTADA', 'CDC', 'resonancia', 'Columna', 'Columna 2 regiones', true, true, 1, true),
	('RM-COLUMNA-3-REGIONES', 'RM COLUMNA 3 REGIONES', 'CDC', 'resonancia', 'Columna', 'Columna 3 regiones', false, true, 1, true),
	('RM-COLUMNA-3-REGIONES-CONTRASTADA', 'RM COLUMNA 3 REGIONES CONTRASTADA', 'CDC', 'resonancia', 'Columna', 'Columna 3 regiones', true, true, 1, true),
	('RM-COLUMNA-CERVICAL-CONTRASTADA', 'RM COLUMNA CERVICAL CONTRASTADA', 'CDC', 'resonancia', 'Columna', 'Columna cervical', true, true, 1, true),
	('RM-COLUMNA-CERVICAL-SIMPLE', 'RM COLUMNA CERVICAL SIMPLE', 'CDC', 'resonancia', 'Columna', 'Columna cervical', false, true, 1, true),
	('RM-COLUMNA-DORSAL-CONTRASTADA', 'RM COLUMNA DORSAL CONTRASTADA', 'CDC', 'resonancia', 'Columna', 'Columna dorsal', true, true, 1, true),
	('RM-COLUMNA-DORSAL-SIMPLE', 'RM COLUMNA DORSAL SIMPLE', 'CDC', 'resonancia', 'Columna', 'Columna dorsal', false, true, 1, true),
	('RM-COLUMNA-LUMBAR-CONTRASTADA', 'RM COLUMNA LUMBAR CONTRASTADA', 'CDC', 'resonancia', 'Columna', 'Columna lumbar', true, true, 1, true),
	('RM-COLUMNA-LUMBAR-SIMPLE', 'RM COLUMNA LUMBAR SIMPLE', 'CDC', 'resonancia', 'Columna', 'Columna lumbar', false, true, 1, true),
	('RM-CRANEO-CONTRASTADA', 'RM CRANEO CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Craneo', true, true, 1, true),
	('RM-CRANEO-SIMPLE', 'RM CRANEO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Craneo', false, true, 1, true),
	('RM-CUELLO-CONTRASTADA', 'RM CUELLO CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Cuello', true, true, 1, true),
	('RM-CUELLO-SIMPLE', 'RM CUELLO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Cuello', false, true, 1, true),
	('RM-CORAZON-CONTRASTADA', 'RM DE CORAZON CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Corazon', true, true, 1, true),
	('RM-CORAZON-SIMPLE', 'RM DE CORAZON SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Corazon', false, true, 1, true),
	('RM-FEMUR-MUSLO-SIMPLE', 'RM FEMUR - MUSLO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Femur - muslo', false, true, 1, true),
	('RM-HIPOFISIS-CONTRASTADA', 'RM HIPOFISIS (CONTRASTADA)', 'CDC', 'resonancia', 'Resonancia magnetica', 'Hipofisis', true, true, 1, true),
	('RM-HOMBRO-CONTRASTADO', 'RM HOMBRO CONTRASTADO', 'CDC', 'resonancia', 'Resonancia magnetica', 'Hombro', true, true, 1, true),
	('RM-HOMBRO-SIMPLE', 'RM HOMBRO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Hombro', false, true, 1, true),
	('RM-MAMARIO-CONTRASTADO', 'RM MAMARIO CONTRASTADO', 'CDC', 'resonancia', 'Resonancia magnetica', 'Mamario', true, true, 1, true),
	('RM-MAMARIO-SIMPLE', 'RM MAMARIO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Mamario', false, true, 1, true),
	('RM-MUNECA-MANO-SIMPLE', 'RM MUNECA - MANO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Muneca - mano', false, true, 1, true),
	('RM-MUSCULO-ESQUELETICO-1-REGION-SIMPLE', 'RM MUSCULO ESQUELETICO 1 REGION SIMPLE', 'CDC', 'resonancia', 'Musculo esqueletico', '1 region', false, true, 1, true),
	('RM-MUSCULO-ESQUELETICO-2-REGIONES-SIMPLE', 'RM MUSCULO ESQUELETICO 2 REGIONES SIMPLE', 'CDC', 'resonancia', 'Musculo esqueletico', '2 regiones', false, true, 1, true),
	('RM-MUSCULO-ESQUELETICO-3-REGIONES-SIMPLE', 'RM MUSCULO ESQUELETICO 3 REGIONES SIMPLE', 'CDC', 'resonancia', 'Musculo esqueletico', '3 regiones', false, true, 1, true),
	('RM-NARIZ-SENOS-PARANASALES-SIMPLE', 'RM NARIZ / SENOS PARANASALES', 'CDC', 'resonancia', 'Resonancia magnetica', 'Nariz / senos paranasales', false, true, 1, true),
	('RM-NARIZ-SENOS-PARANASALES-CONTRASTADA', 'RM NARIZ / SENOS PARANASALES CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Nariz / senos paranasales', true, true, 1, true),
	('RM-OIDO-SIMPLE', 'RM OIDO SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Oido', false, true, 1, true),
	('RM-PANORAMICA-SIMPLE-5-NIVELES', 'RM PANORAMICA SIMPLE (CON 5 NIVELES)', 'CDC', 'resonancia', 'Resonancia magnetica', 'Panoramica 5 niveles', false, true, 1, true),
	('RM-PELVIS-CONTRASTADA', 'RM PELVIS CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Pelvis', true, true, 1, true),
	('RM-PELVIS-SIMPLE', 'RM PELVIS SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Pelvis', false, true, 1, true),
	('RM-PROSTATA-CONTRASTADA', 'RM PROSTATA CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Prostata', true, true, 1, true),
	('RM-PROSTATA-SIMPLE', 'RM PROSTATA SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Prostata', false, true, 1, true),
	('RM-RODILLA-PIERNA-CONTRASTADA', 'RM RODILLA - PIERNA CONTRASTADA', 'CDC', 'resonancia', 'Resonancia magnetica', 'Rodilla - pierna', true, true, 1, true),
	('RM-RODILLA-PIERNA-SIMPLE', 'RM RODILLA - PIERNA SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Rodilla - pierna', false, true, 1, true),
	('RM-TOBILLO-PIE-SIMPLE', 'RM TOBILLO - PIE SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Tobillo - pie', false, true, 1, true),
	('RM-TORAX-SIMPLE', 'RM TORAX SIMPLE', 'CDC', 'resonancia', 'Resonancia magnetica', 'Torax', false, true, 1, true)
on conflict (clave) do update set
	descripcion = excluded.descripcion,
	empresa_operativa = excluded.empresa_operativa,
	modalidad = excluded.modalidad,
	area = excluded.area,
	region_anatomica = excluded.region_anatomica,
	requiere_contraste = excluded.requiere_contraste,
	requiere_interpretacion = excluded.requiere_interpretacion,
	dias_proceso = excluded.dias_proceso,
	activo = excluded.activo,
	updated_at = now();
