delete from public.precios_estudios
where cliente = 'SSA'
	and clave in (
		'AACLG',
		'ACSMITH',
		'ACT',
		'ACTH',
		'ADST',
		'AGG',
		'AcEHB',
		'AcRO',
		'BAAR3',
		'CCP',
		'CI',
		'CLAMY',
		'CLCR',
		'COLI',
		'CUCH',
		'CUSE',
		'DHT',
		'DNAN',
		'EST',
		'FAR',
		'HC',
		'HEMO',
		'HepAT',
		'IgA',
		'IgE',
		'IgG',
		'IgM',
		'K',
		'LAC',
		'LE',
		'LIT',
		'NA',
		'PBASICO',
		'PCRUL',
		'PDIAB',
		'PETS',
		'PPNAT',
		'PPRE',
		'PREOP',
		'PREUMA',
		'PROL',
		'PSCOMP',
		'PSELE',
		'PSTIR',
		'QS3ALT',
		'QS4ALT',
		'TAM',
		'TIRO',
		'TRANS',
		'URE',
		'UREAO',
		'VITD25'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'SSA', 608.00, now()),
	('Estudio', 'ACSMITH', 'AC. ANTI-SMITH', 'SSA', 677.00, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'SSA', 632.50, now()),
	('Estudio', 'ACTH', 'HORMONA ADRENOCORTICOTROFICA ACTH', 'SSA', 665.50, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'SSA', 1053.00, now()),
	('Estudio', 'AGG', 'ANTIGENO GIARDIA LAMBLIA', 'SSA', 1330.00, now()),
	('Estudio', 'AcEHB', 'ANTICUERPOS CONTRA EL  ANTIGENO E DE HEPATITIS B', 'SSA', 486.00, now()),
	('Estudio', 'AcRO', 'ANTICUERPOS ANTI-SSA Ro', 'SSA', 720.00, now()),
	('Estudio', 'BAAR3', 'BACILOSCOPIA DE 3 MUESTRAS (BAAR)', 'SSA', 671.00, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'SSA', 1517.51, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'SSA', 273.95, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'SSA', 4700.00, now()),
	('Estudio', 'CLCR', 'CULTIVO DE LIQUIDO CEFALORRAQUIDEO', 'SSA', 813.45, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'SSA', 473.11, now()),
	('Estudio', 'CUCH', 'CULTIVO DE EXUADO URETRAL C/CHLAMYDIA', 'SSA', 820.00, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'SSA', 572.00, now()),
	('Estudio', 'DHT', 'DIHIDROTESTOSTERONA', 'SSA', 743.00, now()),
	('Estudio', 'DNAN', 'ANTICUERPOS ANTI-DNA', 'SSA', 1148.00, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'SSA', 275.00, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'SSA', 486.20, now()),
	('Estudio', 'HC', 'HORMONA DE CRECIMIENTO', 'SSA', 619.00, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'SSA', 1215.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'SSA', 1148.00, now()),
	('Estudio', 'IgA', 'INMUNOGLOBULINA A IgA', 'SSA', 486.00, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'SSA', 486.00, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'SSA', 486.00, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'SSA', 486.00, now()),
	('Estudio', 'K', 'POTASIO', 'SSA', 288.75, now()),
	('Estudio', 'LAC', 'ACIDO LACTICO', 'SSA', 440.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'SSA', 295.46, now()),
	('Estudio', 'LIT', 'LITIO', 'SSA', 396.44, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'SSA', 288.75, now()),
	('Estudio', 'PBASICO', 'PERFIL BASICO', 'SSA', 1089.00, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'SSA', 440.00, now()),
	('Estudio', 'PDIAB', 'PERFIL DIABETICO', 'SSA', 980.10, now()),
	('Estudio', 'PETS', 'PERFIL ETS', 'SSA', 1039.50, now()),
	('Estudio', 'PPNAT', 'PERFIL PRENATAL', 'SSA', 962.50, now()),
	('Estudio', 'PPRE', 'PERFIL PRENUPCIAL', 'SSA', 330.00, now()),
	('Estudio', 'PREOP', 'PERFIL PREOPERATORIO (solo lab)', 'SSA', 803.00, now()),
	('Estudio', 'PREUMA', 'PERFIL REUMATOLOGICO', 'SSA', 726.00, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'SSA', 275.00, now()),
	('Estudio', 'PSCOMP', 'PERFIL SMAC/COMPLETO', 'SSA', 2904.00, now()),
	('Estudio', 'PSELE', 'PERFIL SMAC/ELECTROLITOS', 'SSA', 2075.70, now()),
	('Estudio', 'PSTIR', 'PERFIL SMAC/TIROIDEO', 'SSA', 2534.40, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'SSA', 265.65, now()),
	('Estudio', 'QS4ALT', 'QUIMICA SANGUINEA DE 4 ELEMENTOS (COL, TRIG)', 'SSA', 373.45, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'SSA', 1424.50, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'SSA', 957.00, now()),
	('Estudio', 'TRANS', 'TRANSFERRINA', 'SSA', 385.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'SSA', 107.80, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'SSA', 300.00, now()),
	('Estudio', 'VITD25', 'VITAMINA D 25-OH', 'SSA', 850.00, now());
