delete from public.precios_estudios
where cliente = 'Particular'
	and clave in (
		'VET-RM-CERVICAL-CONTRASTADA',
		'VET-RM-CERVICAL-SIMPLE',
		'VET-RM-CRANEO-CONTRASTADA',
		'VET-RM-CRANEO-SIMPLE',
		'VET-RM-DORSAL-SIMPLE',
		'VET-RM-LUMBAR-SIMPLE',
		'VET-RM-LUMBOSACRA-CONTRASTADA',
		'VET-RM-RODILLA-SIMPLE',
		'VET-RM-TORACOABDOMINAL-CONTRASTADA',
		'VET-RM-TORACOLUMBAR-CONTRASTADA',
		'VET-RM-TORACOLUMBAR-SIMPLE',
		'VET-RX-ABDOMEN',
		'VET-RX-COLUMNA',
		'VET-RX-CRANEO',
		'VET-RX-EXTREMIDADES',
		'VET-RX-MANDIBULA',
		'VET-RX-PELVIS',
		'VET-RX-TORAX',
		'VET-TAC-ABDOMEN',
		'VET-TAC-ABDOMEN-CONTRASTADO',
		'VET-TAC-COLUMNA',
		'VET-TAC-COLUMNA-CONTRASTADA',
		'VET-TAC-CRANEO',
		'VET-TAC-CRANEO-CONTRASTADO',
		'VET-TAC-EXTREMIDADES',
		'VET-TAC-EXTREMIDADES-CONTRASTADO',
		'VET-TAC-MANDIBULA',
		'VET-TAC-MANDIBULA-CONTRASTADA',
		'VET-TAC-PELVIS',
		'VET-TAC-PELVIS-CONTRASTADA',
		'VET-TAC-TORAX-CONTRASTADO',
		'VET-TAC-TORAX-SIMPLE',
		'VET-US-ABDOMEN-COMPLETO',
		'VET-US-HIGADO',
		'VET-US-PELVICO-UTERO-GESTACION',
		'VET-US-PROSTATA-TESTICULOS',
		'VET-US-UTERO-OVARIOS'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'VET-RM-CERVICAL-CONTRASTADA', 'RM CERVICAL CONTRASTADA', 'Particular', 4320.00, now()),
	('Estudio', 'VET-RM-CERVICAL-SIMPLE', 'RM CERVICAL SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RM-CRANEO-CONTRASTADA', 'RM CRANEO CONTRASTADA', 'Particular', 4320.00, now()),
	('Estudio', 'VET-RM-CRANEO-SIMPLE', 'RM CRANEO SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RM-DORSAL-SIMPLE', 'RM DORSAL SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RM-LUMBAR-SIMPLE', 'RM LUMBAR SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RM-LUMBOSACRA-CONTRASTADA', 'RM LUMBOSACRA CONTRASTADA', 'Particular', 4320.00, now()),
	('Estudio', 'VET-RM-RODILLA-SIMPLE', 'RM RODILLA SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RM-TORACOABDOMINAL-CONTRASTADA', 'RM TORACOABDOMINAL CONTRASTADA', 'Particular', 4320.00, now()),
	('Estudio', 'VET-RM-TORACOLUMBAR-CONTRASTADA', 'RM TORACOLUMBAR CONTRASTADA', 'Particular', 4320.00, now()),
	('Estudio', 'VET-RM-TORACOLUMBAR-SIMPLE', 'RM TORACOLUMBAR SIMPLE', 'Particular', 3240.00, now()),
	('Estudio', 'VET-RX-ABDOMEN', 'RX ABDOMEN', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-COLUMNA', 'RX COLUMNA', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-CRANEO', 'RX CRANEO', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-EXTREMIDADES', 'RX EXTREMIDADES', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-MANDIBULA', 'RX MANDIBULA', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-PELVIS', 'RX PELVIS', 'Particular', 530.00, now()),
	('Estudio', 'VET-RX-TORAX', 'RX TORAX', 'Particular', 530.00, now()),
	('Estudio', 'VET-TAC-ABDOMEN', 'TAC ABDOMEN', 'Particular', 3620.00, now()),
	('Estudio', 'VET-TAC-ABDOMEN-CONTRASTADO', 'TAC ABDOMEN CONTRASTADO', 'Particular', 4090.00, now()),
	('Estudio', 'VET-TAC-COLUMNA', 'TAC COLUMNA', 'Particular', 3620.00, now()),
	('Estudio', 'VET-TAC-COLUMNA-CONTRASTADA', 'TAC COLUMNA CONTRASTADA', 'Particular', 3890.00, now()),
	('Estudio', 'VET-TAC-CRANEO', 'TAC CRANEO', 'Particular', 2810.00, now()),
	('Estudio', 'VET-TAC-CRANEO-CONTRASTADO', 'TAC CRANEO CONTRASTADO', 'Particular', 3190.00, now()),
	('Estudio', 'VET-TAC-EXTREMIDADES', 'TAC EXTREMIDADES', 'Particular', 3620.00, now()),
	('Estudio', 'VET-TAC-EXTREMIDADES-CONTRASTADO', 'TAC EXTREMIDADES CONTRASTADO', 'Particular', 3890.00, now()),
	('Estudio', 'VET-TAC-MANDIBULA', 'TAC MANDIBULA', 'Particular', 3620.00, now()),
	('Estudio', 'VET-TAC-MANDIBULA-CONTRASTADA', 'TAC MANDIBULA CONTRASTADA', 'Particular', 3890.00, now()),
	('Estudio', 'VET-TAC-PELVIS', 'TAC PELVIS', 'Particular', 3350.00, now()),
	('Estudio', 'VET-TAC-PELVIS-CONTRASTADA', 'TAC PELVIS CONTRASTADA', 'Particular', 3730.00, now()),
	('Estudio', 'VET-TAC-TORAX-CONTRASTADO', 'TAC TORAX CONTRASTADO', 'Particular', 3460.00, now()),
	('Estudio', 'VET-TAC-TORAX-SIMPLE', 'TAC TORAX SIMPLE', 'Particular', 3620.00, now()),
	('Estudio', 'VET-US-ABDOMEN-COMPLETO', 'US ABDOMEN COMPLETO', 'Particular', 1000.00, now()),
	('Estudio', 'VET-US-HIGADO', 'US HIGADO', 'Particular', 840.00, now()),
	('Estudio', 'VET-US-PELVICO-UTERO-GESTACION', 'US PELVICO (UTERO GESTACION)', 'Particular', 1000.00, now()),
	('Estudio', 'VET-US-PROSTATA-TESTICULOS', 'US PROSTATA Y TESTICULOS', 'Particular', 840.00, now()),
	('Estudio', 'VET-US-UTERO-OVARIOS', 'US UTERO Y OVARIOS', 'Particular', 840.00, now());
