delete from public.precios_estudios
where cliente = 'ISSSTE'
	and clave in (
		'17HC24',
		'17HCO',
		'AACLG',
		'ACT',
		'ADRE',
		'ADST',
		'AH',
		'AMINOOR',
		'ANDRO',
		'ANTIRH',
		'ARNA',
		'AcEBARR',
		'CCP',
		'CI',
		'CLAMY',
		'CLIQ',
		'CNASA',
		'CO',
		'COLI',
		'CSEMEN',
		'CULMYC',
		'CUSE',
		'CVC',
		'CVIB',
		'DEPU',
		'DOPA',
		'ES6',
		'ESPIND',
		'EST',
		'ESTSNOCON',
		'FAC2',
		'FAR',
		'FIX',
		'FX',
		'HEMO',
		'HEPD',
		'HIV4',
		'HepAT',
		'IGFBP',
		'ISOCPK',
		'IgE',
		'IgG',
		'IgM',
		'K',
		'LE',
		'LIT',
		'NA',
		'NDP',
		'OXCARB',
		'PCRUL',
		'PPD',
		'PREUMA',
		'PROL',
		'QS3ALT',
		'RPN',
		'TAM',
		'TEO',
		'TIRO',
		'TRANSGLUM',
		'URE',
		'UREAO',
		'VITD25',
		'WBHIV2',
		'ZIKA'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', '17HC24', '17 HIDROXICORTICOESTEROIDES EN ORINA DE 24 HORAS', 'ISSSTE', 700.00, now()),
	('Estudio', '17HCO', '17 HIDROXICORTICOESTEROIDES EN SUERO', 'ISSSTE', 700.00, now()),
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'ISSSTE', 575.00, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'ISSSTE', 613.00, now()),
	('Estudio', 'ADRE', 'ADRENALINA EN PLASMA', 'ISSSTE', 670.00, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'ISSSTE', 1041.00, now()),
	('Estudio', 'AH', 'ANTICUERPOS HETEROFILOS (PAUL BUNNELL)', 'ISSSTE', 1050.00, now()),
	('Estudio', 'AMINOOR', 'AMINOACIDOS EN ORINA DE 24HRS', 'ISSSTE', 1150.00, now()),
	('Estudio', 'ANDRO', 'ANDROGENOS TOTALES', 'ISSSTE', 1750.00, now()),
	('Estudio', 'ANTIRH', 'ANTICUERPOS ANTI RH', 'ISSSTE', 156.00, now()),
	('Estudio', 'ARNA', 'ANTICUERPOS ANTI-RNA', 'ISSSTE', 950.00, now()),
	('Estudio', 'AcEBARR', 'AC.ANTI-EPSTEIN BARR Ag TEMPRANO IgG(EA)', 'ISSSTE', 778.00, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'ISSSTE', 1100.00, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'ISSSTE', 190.00, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'ISSSTE', 1290.00, now()),
	('Estudio', 'CLIQ', 'CULTIVO DE LIQUIDOS CORPORALES', 'ISSSTE', 455.00, now()),
	('Estudio', 'CNASA', 'CULTIVO DE EXUDADO NASAL', 'ISSSTE', 455.00, now()),
	('Estudio', 'CO', 'CULTIVO DE HONGOS (MYCOLOGICO)', 'ISSSTE', 769.00, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'ISSSTE', 491.00, now()),
	('Estudio', 'CSEMEN', 'CULTIVO DE SEMEN (ESPERMOCULTIVO)', 'ISSSTE', 464.00, now()),
	('Estudio', 'CULMYC', 'CULTIVO DE MYCOBACTERIUM TB.', 'ISSSTE', 769.00, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'ISSSTE', 534.00, now()),
	('Estudio', 'CVC', 'PCR CARGA VIRAL DE CITOMEGALOVIRUS (CMV)', 'ISSSTE', 4200.00, now()),
	('Estudio', 'CVIB', 'CULTIVO PARA VIBRIO CHOLERAE', 'ISSSTE', 570.00, now()),
	('Estudio', 'DEPU', 'DEPURACION DE CREATININA EN ORINA DE 24 HORAS', 'ISSSTE', 200.00, now()),
	('Estudio', 'DOPA', 'DOPAMINA EN PLASMA', 'ISSSTE', 1150.00, now()),
	('Estudio', 'ES6', 'ELECTROLITOS SERICOS DE 6 PARAMETROS', 'ISSSTE', 750.00, now()),
	('Estudio', 'ESPIND', 'AC. ANTI-ESPERMATOZOIDES(INDIRECTOS)', 'ISSSTE', 1509.00, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'ISSSTE', 251.00, now()),
	('Estudio', 'ESTSNOCON', 'ESTRIOL SERICO NO CONJUGADO (E3)', 'ISSSTE', 641.00, now()),
	('Estudio', 'FAC2', 'FACTOR II DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'ISSSTE', 525.00, now()),
	('Estudio', 'FIX', 'FACTOR IX DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'FX', 'FACTOR X DE LA COAGULACIÓN', 'ISSSTE', 1100.00, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'ISSSTE', 1400.00, now()),
	('Estudio', 'HEPD', 'AC.ANTI-HEPATITIS D (HDV)', 'ISSSTE', 3513.00, now()),
	('Estudio', 'HIV4', 'HIV 4TA GENERACIÓN', 'ISSSTE', 357.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'ISSSTE', 669.00, now()),
	('Estudio', 'IGFBP', 'FACTOR HUMANO DE CRECIMIENTO SIMILAR A LA INSULINA(IGFBP-3)', 'ISSSTE', 1050.00, now()),
	('Estudio', 'ISOCPK', 'ISOENZIMAS DE CPK', 'ISSSTE', 1200.00, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'ISSSTE', 453.00, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'ISSSTE', 394.00, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'ISSSTE', 394.00, now()),
	('Estudio', 'K', 'POTASIO', 'ISSSTE', 149.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'ISSSTE', 282.00, now()),
	('Estudio', 'LIT', 'LITIO', 'ISSSTE', 378.00, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'ISSSTE', 334.00, now()),
	('Estudio', 'NDP', 'NORADRENALINA EN PLASMA', 'ISSSTE', 1150.00, now()),
	('Estudio', 'OXCARB', 'OXCARBAZEPINA', 'ISSSTE', 2300.00, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'ISSSTE', 540.00, now()),
	('Estudio', 'PPD', 'PRUEBA CUTANEA DE TUBERCULINA', 'ISSSTE', 1800.00, now()),
	('Estudio', 'PREUMA', 'PERFIL REUMATOLOGICO', 'ISSSTE', 741.00, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'ISSSTE', 250.00, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'ISSSTE', 239.00, now()),
	('Estudio', 'RPN', 'ANTICUERPOS ANTI-RNP', 'ISSSTE', 810.00, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'ISSSTE', 1695.00, now()),
	('Estudio', 'TEO', 'AMINOFILINA(TEOFILINA)', 'ISSSTE', 1307.00, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'ISSSTE', 780.00, now()),
	('Estudio', 'TRANSGLUM', 'AC. ANTI TRANSGLUTAMINASA (IgA)', 'ISSSTE', 1820.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'ISSSTE', 111.00, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'ISSSTE', 260.00, now()),
	('Estudio', 'VITD25', 'VITAMINA D 25-OH', 'ISSSTE', 890.00, now()),
	('Estudio', 'WBHIV2', 'WESTERN BLOT VIH 2', 'ISSSTE', 4050.00, now()),
	('Estudio', 'ZIKA', 'ANTICUERPOS VIRUS DE ZIKA', 'ISSSTE', 3600.00, now());
