delete from public.precios_estudios
where cliente = 'Particular'
	and clave in (
		'AACLG',
		'ACT',
		'ADST',
		'AGG',
		'AcEBARR',
		'CCP',
		'CI',
		'CLAMY',
		'CLCR',
		'CLIQ',
		'CNASA',
		'CO',
		'COLHDL',
		'COLI',
		'CSEMEN',
		'CUCH',
		'CULMYC',
		'CURE',
		'CUSE',
		'ES3OR',
		'EST',
		'FAR',
		'HAP',
		'HEMO',
		'HepAT',
		'IGGTRANS',
		'ISOCPK',
		'IgE',
		'IgG',
		'IgGSUB',
		'IgM',
		'K',
		'LAC',
		'LE',
		'LIT',
		'MG24',
		'NA',
		'PAF',
		'PAM',
		'PAQANTI',
		'PAQCENT',
		'PAQRAG',
		'PAQSEM',
		'PBASICO',
		'PBM',
		'PBMAS1',
		'PBMAS2',
		'PCRUL',
		'PDIAB',
		'PESC',
		'PETS',
		'POT24',
		'PPNAT',
		'PPRE',
		'PPREOP',
		'PREOP',
		'PREUMA',
		'PROL',
		'PSCOMP',
		'PSEG1',
		'PSELE',
		'PSTIR',
		'QS3ALT',
		'QS4ALT',
		'RPN',
		'Se',
		'TAM',
		'TEO',
		'TIRO',
		'TRANS',
		'TRANSGLUM',
		'URE',
		'UREAO'
	);

insert into public.precios_estudios (
	tipo,
	clave,
	descripcion,
	cliente,
	precio,
	fecha
)
values
	('Estudio', 'AACLG', 'ANTICUERPOS ANTI-CARDIOLIPINAS IgG', 'Particular', 608.00, now()),
	('Estudio', 'ACT', 'ANTICUERPOS ANTI-TIROGLOBULINA', 'Particular', 632.50, now()),
	('Estudio', 'ADST', 'ALDOSTERONA', 'Particular', 1053.00, now()),
	('Estudio', 'AGG', 'ANTIGENO GIARDIA LAMBLIA', 'Particular', 1330.00, now()),
	('Estudio', 'AcEBARR', 'AC.ANTI-EPSTEIN BARR Ag TEMPRANO IgG(EA)', 'Particular', 1452.00, now()),
	('Estudio', 'CCP', 'ANTI-PEPTIDO CICLICO CITRULINADO', 'Particular', 1785.30, now()),
	('Estudio', 'CI', 'COOMBS INDIRECTO', 'Particular', 322.30, now()),
	('Estudio', 'CLAMY', 'ANTIGENO CHLAMYDIA  TRACHOMATIS  POR PCR', 'Particular', 1900.00, now()),
	('Estudio', 'CLCR', 'CULTIVO DE LIQUIDO CEFALORRAQUIDEO', 'Particular', 957.00, now()),
	('Estudio', 'CLIQ', 'CULTIVO DE LIQUIDOS CORPORALES', 'Particular', 770.00, now()),
	('Estudio', 'CNASA', 'CULTIVO DE EXUDADO NASAL', 'Particular', 572.00, now()),
	('Estudio', 'CO', 'CULTIVO DE HONGOS (MYCOLOGICO)', 'Particular', 948.20, now()),
	('Estudio', 'COLHDL', 'COLESTEROL HDL', 'Particular', 154.00, now()),
	('Estudio', 'COLI', 'COLINESTERASA EN SUERO', 'Particular', 556.60, now()),
	('Estudio', 'CSEMEN', 'CULTIVO DE SEMEN (ESPERMOCULTIVO)', 'Particular', 600.60, now()),
	('Estudio', 'CUCH', 'CULTIVO DE EXUADO URETRAL C/CHLAMYDIA', 'Particular', 820.00, now()),
	('Estudio', 'CULMYC', 'CULTIVO DE MYCOBACTERIUM TB.', 'Particular', 862.00, now()),
	('Estudio', 'CURE', 'CULTIVO DE UREAPLASMA', 'Particular', 1045.00, now()),
	('Estudio', 'CUSE', 'CULTIVO DE SECRECION', 'Particular', 572.00, now()),
	('Estudio', 'ES3OR', 'ELECTROLITOS EN ORINA 24 HRS DE 3 PARAMETROS (Na, K, Cl)', 'Particular', 412.50, now()),
	('Estudio', 'EST', 'ESTRADIOL', 'Particular', 392.70, now()),
	('Estudio', 'FAR', 'CULTIVO DE EXUDADO FARINGEO', 'Particular', 572.00, now()),
	('Estudio', 'HAP', 'HAPTOGLOBINAS', 'Particular', 743.00, now()),
	('Estudio', 'HEMO', 'CULTIVO DE SANGRE (HEMOCULTIVO)', 'Particular', 1215.00, now()),
	('Estudio', 'HepAT', 'ANTICUERPOS ANTI-HEPATITIS A TOTAL', 'Particular', 1148.00, now()),
	('Estudio', 'IGGTRANS', 'Ac. ANTI-TRANSGLUTAMINASA (IgG)', 'Particular', 2180.00, now()),
	('Estudio', 'ISOCPK', 'ISOENZIMAS DE CPK', 'Particular', 1380.00, now()),
	('Estudio', 'IgE', 'INMUNOGLOBULINA E SERICA (IgE)', 'Particular', 486.20, now()),
	('Estudio', 'IgG', 'INMUNOGLOBULINA G IgG', 'Particular', 486.20, now()),
	('Estudio', 'IgGSUB', 'INMUNOGLOBULINA G SUBCLASES IgG 1,2,3,4', 'Particular', 2451.00, now()),
	('Estudio', 'IgM', 'INMUNOGLOBULINA M  IgM', 'Particular', 486.20, now()),
	('Estudio', 'K', 'POTASIO', 'Particular', 412.50, now()),
	('Estudio', 'LAC', 'ACIDO LACTICO', 'Particular', 440.00, now()),
	('Estudio', 'LE', 'CELULAS LE', 'Particular', 347.60, now()),
	('Estudio', 'LIT', 'LITIO', 'Particular', 466.40, now()),
	('Estudio', 'MG24', 'MAGNESIO EN ORINA DE 24 HORAS', 'Particular', 270.00, now()),
	('Estudio', 'NA', 'SODIO SERICO', 'Particular', 412.50, now()),
	('Estudio', 'PAF', 'PAQUETE ARIES FEMENINO (INCLUYE: TORAX AP, COLUMNA 2 POSICIONES, MASTO, USG MAMARIO, EKG)', 'Particular', 7604.52, now()),
	('Estudio', 'PAM', 'PAQUETE ARIES MASCULINO (INCLUYE: TORAX AP, COLUMNA 2 POSICIONES, USG PROSTATICO,EKG)', 'Particular', 6818.62, now()),
	('Estudio', 'PAQANTI', 'PAQUETE ANTIDOPING + CERTIFICADO MEDICO', 'Particular', 1327.00, now()),
	('Estudio', 'PAQCENT', 'PAQUETE HOMBRE CENTAURO', 'Particular', 1856.00, now()),
	('Estudio', 'PAQRAG', 'PAQUETE RAGASA', 'Particular', 1220.00, now()),
	('Estudio', 'PAQSEM', 'PAQUETE SEMEBA', 'Particular', 3784.00, now()),
	('Estudio', 'PBASICO', 'PERFIL BASICO', 'Particular', 1210.00, now()),
	('Estudio', 'PBM', 'Perfil Básico Masculino (solo lab)', 'Particular', 1280.40, now()),
	('Estudio', 'PBMAS1', 'PAQUETE BASICO MASCULINO 1 **INCLUYE: RX TORAX, USG PROSTATICO', 'Particular', 1500.00, now()),
	('Estudio', 'PBMAS2', 'PAQUETE BASICO MASCULINO 2, INCLUYE: EKG, USG PROSTATICO, RX TORAX', 'Particular', 3000.00, now()),
	('Estudio', 'PCRUL', 'PROTEINA "C" REACTIVA ULTRASENSIBLE', 'Particular', 440.00, now()),
	('Estudio', 'PDIAB', 'PERFIL DIABETICO', 'Particular', 990.00, now()),
	('Estudio', 'PESC', 'PAQUETE ESCOLAR', 'Particular', 600.00, now()),
	('Estudio', 'PETS', 'PERFIL ETS', 'Particular', 1485.00, now()),
	('Estudio', 'POT24', 'POTASIO EN ORINA DE 24 HORAS', 'Particular', 411.40, now()),
	('Estudio', 'PPNAT', 'PERFIL PRENATAL', 'Particular', 1375.00, now()),
	('Estudio', 'PPRE', 'PERFIL PRENUPCIAL', 'Particular', 330.00, now()),
	('Estudio', 'PPREOP', 'PAQUETE PREOPERATORIO, INCLUYE: EKG, RX TORAX', 'Particular', 2035.00, now()),
	('Estudio', 'PREOP', 'PERFIL PREOPERATORIO (solo lab)', 'Particular', 1147.30, now()),
	('Estudio', 'PREUMA', 'PERFIL REUMATOLOGICO', 'Particular', 1037.30, now()),
	('Estudio', 'PROL', 'PROLACTINA', 'Particular', 392.70, now()),
	('Estudio', 'PSCOMP', 'PERFIL SMAC/COMPLETO', 'Particular', 3630.00, now()),
	('Estudio', 'PSEG1', 'PAQUETE SEG 1', 'Particular', 1995.78, now()),
	('Estudio', 'PSELE', 'PERFIL SMAC/ELECTROLITOS', 'Particular', 1650.00, now()),
	('Estudio', 'PSTIR', 'PERFIL SMAC/TIROIDEO', 'Particular', 3168.00, now()),
	('Estudio', 'QS3ALT', 'QUIMICA SANGUINEA DE 3(COL,TRIG)', 'Particular', 379.50, now()),
	('Estudio', 'QS4ALT', 'QUIMICA SANGUINEA DE 4 ELEMENTOS (COL, TRIG)', 'Particular', 533.50, now()),
	('Estudio', 'RPN', 'ANTICUERPOS ANTI-RNP', 'Particular', 945.00, now()),
	('Estudio', 'Se', 'SELENIO', 'Particular', 1650.00, now()),
	('Estudio', 'TAM', 'TAMIZ METABOLICO AMPLIADO', 'Particular', 1424.50, now()),
	('Estudio', 'TEO', 'AMINOFILINA(TEOFILINA)', 'Particular', 783.00, now()),
	('Estudio', 'TIRO', 'PERFIL TIROIDEO', 'Particular', 1210.00, now()),
	('Estudio', 'TRANS', 'TRANSFERRINA', 'Particular', 385.00, now()),
	('Estudio', 'TRANSGLUM', 'AC. ANTI TRANSGLUTAMINASA (IgA)', 'Particular', 2750.00, now()),
	('Estudio', 'URE', 'UREA SERICA', 'Particular', 154.00, now()),
	('Estudio', 'UREAO', 'DEPURACION DE UREA EN ORINA DE 24 HORAS', 'Particular', 300.00, now());
